### ISSUE TITLE
[问题]有关训练可视化

### ISSUE THREAD

**Issue by RickMeow** [InternLM/xtuner#104]
感谢您对于项目的贡献！

**问题描述**

对于微调训练过程来说，xtuner有 可视化实时训练进展、曲线的方式吗？

**期待您的回复！**

**Comment by pppppM** [comment]
可以在 config 中设置 `visualizer` 字段，mmengine 支持 TensorBoard、WanDB 等可视化后端，可以根据需求在 `vis_backends` 中灵活添加或移除

https://github.com/open-mmlab/mmengine/blob/45ee96d0c4643bafcc64f94e761a65159ef31083/docs/zh_cn/common_usage/visualize_training_log.md

下面是一个在 xtuner 中使用 TensorBoard 的例子，

```
# set visualizer
from mmengine.visualization import Visualizer,WandbVisBackend, TensorboardVisBackend
visualizer = dict(
    type=Visualizer, 
    vis_backends=[
        dict(type=TensorboardVisBackend),
        dict(type=WandbVisBackend)
        ]
)
```

tensorboard 产生的相关文件会存在 `vis_data` 中，通过 tensorboard 命令可以启动进行实时可视化
![image](https://github.com/InternLM/xtuner/assets/67539920/abacb28f-5afd-46d0-91b2-acdd20887969)

```
tensorboard --logdir=$PATH_TO_VIS_DATA 
```

**Comment by LZHgrla** [comment]
上游代码库 mmengine 在将 lazy config ( XTuner 普遍使用的一个 feature ) 转换到 json 时有 bug。所以 wandb 暂时用不上，可以关注这个issue https://github.com/open-mmlab/mmengine/issues/1342

tensorboard 可以正常使用

```python
# set visualizer
from mmengine.visualization import Visualizer, TensorboardVisBackend
visualizer = dict(
    type=Visualizer, 
    vis_backends=[dict(type=TensorboardVisBackend)]
)
```

**Comment by iFe1er** [comment]
请问xtuner能建一个官方微信交流群吗，起到推广xtuner的作用，也方便开发者们请教问题和交流经验~^ ^

**Comment by pppppM** [comment]
README 主页有链接~
https://cdn.vansin.top/internlm/xtuner.jpg

**Comment by RickMeow** [comment]
非常有效的方法，同时感谢对于wandb的说明，确实纠结过报错的问题。

在目前测试阶段，tensorboard可以满足实验需求，非常感谢！

**Comment by pppppM** [comment]
> README 主页有链接~ https://cdn.vansin.top/internlm/xtuner.jpg

@iFe1er

**Comment by LZHgrla** [comment]
> 可以在 config 中设置 `visualizer` 字段，mmengine 支持 TensorBoard、WanDB 等可视化后端，可以根据需求在 `vis_backends` 中灵活添加或移除
> 
> https://github.com/open-mmlab/mmengine/blob/45ee96d0c4643bafcc64f94e761a65159ef31083/docs/zh_cn/common_usage/visualize_training_log.md
> 
> 下面是一个在 xtuner 中使用 TensorBoard 的例子，
> 
> ```
> # set visualizer
> from mmengine.visualization import Visualizer,WandbVisBackend, TensorboardVisBackend
> visualizer = dict(
>     type=Visualizer, 
>     vis_backends=[dict(type=TensorboardVisBackend]
> )
> ```
> 
> tensorboard 产生的相关文件会存在 `vis_data` 中，通过 tensorboard 命令可以启动进行实时可视化 ![image](https://user-images.githubusercontent.com/67539920/266201877-abacb28f-5afd-46d0-91b2-acdd20887969.png)
> 
> ```
> tensorboard --logdir=$PATH_TO_VIS_DATA 
> ```

**Comment by zxjhellow2** [comment]
> 可以在 config 中设置 `visualizer` 字段，mmengine 支持 TensorBoard、WanDB 等可视化后端，可以根据需求在 `vis_backends` 中灵活添加或移除
> 
> https://github.com/open-mmlab/mmengine/blob/45ee96d0c4643bafcc64f94e761a65159ef31083/docs/zh_cn/common_usage/visualize_training_log.md
> 
> 下面是一个在 xtuner 中使用 TensorBoard 的例子，
> 
> ```
> # set visualizer
> from mmengine.visualization import Visualizer,WandbVisBackend, TensorboardVisBackend
> visualizer = dict(
>     type=Visualizer, 
>     vis_backends=[dict(type=TensorboardVisBackend)]
> )
> ```
> 
> tensorboard 产生的相关文件会存在 `vis_data` 中，通过 tensorboard 命令可以启动进行实时可视化 ![image](https://github.com/InternLM/xtuner/assets/67539920/abacb28f-5afd-46d0-91b2-acdd20887969)
> 
> ```
> tensorboard --logdir=$PATH_TO_VIS_DATA 
> ```

你好，请问这里的$PATH_TO_VIS_DATA  的路径得具体到vis_data这个文件夹吗？但是这个文件夹是随着实验生成的，在实验之前不确定
