### ISSUE TITLE
[feature] how to set num_workers to speed loading dataset?

### ISSUE THREAD

**Issue by amulil** [InternLM/xtuner#113]
When I run `NPROC_PER_NODE=8 xtuner train llama2_7b_qlora_moss_sft_all_e2_gpu8`, the speed of loading moss data is slow:
```
708it [00:02, 355.86it/s]09/11 13:02:29 - mmengine - INFO - Loading MOSS SFT data...
555779it [36:16, 237.63it/s]
```

**Comment by LZHgrla** [comment]
So sorry for that, but at present, we do not support parallel processing of MOSS dataset.

However, this long time processing (about 1 hour) only needs to be done one time. After the first processing, the cache will be automatically saved to the dataset path, and will be automatically loaded and used in the future.
