### ISSUE TITLE
[feature] how to change save strategy in xtuner?

### ISSUE THREAD

**Issue by amulil** [InternLM/xtuner#117]
Now, the default strategy is epoch.

**Comment by LZHgrla** [comment]
You can change it with this [docs](https://github.com/open-mmlab/mmengine/blob/main/docs/en/common_usage/epoch_to_iter.md)

If some parameters are not set in our config (e.g., `log_processor`), you can directly set them to override the default value.

**Comment by amulil** [comment]
> You can change it with this [docs](https://github.com/open-mmlab/mmengine/blob/main/docs/en/common_usage/epoch_to_iter.md)
> 
> If some parameters are not set in our config (e.g., `log_processor`), you can directly set them to override the default value.
> 
> `param_scheduler` is hard to understand, and you can follow this [docs](https://github.com/open-mmlab/mmengine/blob/main/docs/en/tutorials/param_scheduler.md) to set it!

Thank you, I will check these documents to learn.
