### ISSUE TITLE
[feature] how to use multiple dataset to sft model in xtuner?

### ISSUE THREAD

**Issue by amulil** [InternLM/xtuner#119]
I want to mix orca and open platypus data to sft llama2 at the same time.

**Comment by LZHgrla** [comment]
https://github.com/InternLM/xtuner/blob/c7559d14e5d5e3913306aeb46e822171ee9b37d2/xtuner/configs/internlm/internlm_7b/internlm_7b_full_alpaca_enzh_oasst1_e3.py#L67-L105

We implement the ConcatDataset for mixing multiple datasets. Please follow the above code to set your custom ConcatDataset

**Comment by amulil** [comment]
I have a similar porblem about mix datasets. The openorca dataset is too big, how can I use the small set of it by changing config? @LZHgrla

**Comment by amulil** [comment]
Thanks, it's very helpful for me.
