### ISSUE TITLE
[feature] how to reuse epoch_1.pth in xtuner?

### ISSUE THREAD

**Issue by amulil** [InternLM/xtuner#120]
When I finish llama2-7b fine-tuning, I need to reuse it's checkpoint.

**Comment by LZHgrla** [comment]
You can use `--resume YOUR_PTH` for `xtuner train`.

But, we find there is a bug for resume `PagedAdamW32bit` or  `DeepSpeed` PTH, we will fix it in future version. So, if you want to resume one PTH, please use `torch.optim.AdamW` instead of `PagedAdamW32bit ` and do not use DeepSpeed

**Comment by amulil** [comment]
> You can use `--resume YOUR_PTH` for `xtuner train`.
> 
> But.. we find there is a bug for resume `PagedAdamW32bit` or `DeepSpeed` PTH, we will fix it in future version. So, if you want to resume one PTH, please use `torch.optim.AdamW` instead of `PagedAdamW32bit` and do not use DeepSpeed

Thanks, It's helpful.I'll try it.

**Comment by lllsy12138** [comment]
Has this bug been fixed?
i still can't resume from deepspeed pth，even i convert it to fp32 pth.

**Comment by LZHgrla** [comment]
Hi! @amulil @lllsy12138 
We've developed a solution that lets users `resume` from a DeepSpeed checkpoint, although it may seem a bit complicated.

The `resume` is made possible through these two PRs (https://github.com/open-mmlab/mmengine/pull/1424, https://github.com/microsoft/DeepSpeed/pull/4587), and setting `exclude_frozen_parameters=True` for `DeepSpeedStrategy` in `xtuner/tools/train.py`.

The most straightforward way to implement these steps is installing the related libraries from my forked repos (as these two PRs have yet to be merged) 
```shell
pip install 'git+https://github.com/LZHgrla/mmengine.git@lzh/fix_ds_resume'
pip install 'git+https://github.com/LZHgrla/DeepSpeed@lzh/enhance'
```
and manually modifying the `xtuner/tools/train.py` as depicted here:
https://github.com/InternLM/xtuner/blob/0a9e4800354c78a6779323f3327921bb2a783846/xtuner/tools/train.py#L227-L233

Once these two PRs are merged, we'll incorporate support for the `resume` into the main branch.
I will update on any news regarding the `resume` feature in this issue!

**Comment by LZHgrla** [comment]
Now all these PRs have been merged.
We can install latest xtuner (>=0.1.9), mmengine (>=0.10.0), deepspeed (>=0.12.3) to access the `resume` feature!

```
pip install 'xtuner>=0.1.9' 'mmengine>=0.10.0' 'deepspeed>=0.12.3'
```
