### ISSUE TITLE
chat answer has no space character

### ISSUE THREAD

**Issue by maxchiron** [InternLM/xtuner#122]
#### I want to compare the original model performance, so I run:

```bash
xtuner chat THUDM/chatglm2-6b
```

#### And the response has no space character. Same issue also occures when ```--adapter``` is added. How could I fix this?
![image](https://github.com/InternLM/xtuner/assets/85681332/09df69bd-e829-4348-91c5-38a895b7e90d)

**Comment by LZHgrla** [comment]
We should add `--prompt-template` for a specific model

Try
```bash
xtuner chat THUDM/chatglm2-6b --prompt-template chatglm
```

**Comment by maxchiron** [comment]
> We should add `--prompt-template` for a specific model
> 
> Try
> 
> ```shell
> xtuner chat THUDM/chatglm2-6b --prompt-template chatglm
> ```

Sorry, it not works.
![image](https://github.com/InternLM/xtuner/assets/85681332/42e88c66-4d86-4cb4-a552-0757f3d442e2)

**Comment by LZHgrla** [comment]
Yes, you are right, we find that our streamer cannot add space for generated English text from ChatGLM2.

You can close the streamer by
```python
xtuner chat THUDM/chatglm2-6b --prompt-template chatglm --no-streamer
```

**Comment by maxchiron** [comment]
> Yes, you are right, we find that our streamer cannot add space for English text from ChatGLM2.
> 
> You can close the streamer by
> 
> ```python
> xtuner chat THUDM/chatglm2-6b --prompt-template chatglm --no-streamer
> ```

Thank you very much. **It works properly.** Thanks for the distribution and fast reply.
