### ISSUE TITLE
lmdeploy error. TypeError: 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by maxchiron** [InternLM/xtuner#125]
### I'm following the readme. And stuck at the **Deploy** part:
I have done these steps:
1. **fine tune** chatglm2 with self dataset.json --> get the epoch_05.pth
2. done **pth2hf** --> get the adapter folder
3. **merge** the adapter to chatglm2 --> get the merged hf model folder (merged-hf, containg 7 .bin files)

### Then I ran the command:
```python -m lmdeploy.pytorch.chat ./merged-hf --max_new_tokens 256 --temperture 0.8 --top_p 0.95 --seed 0```
in which the ./merged-hf is the step.3 result.
And then I got error:
![image](https://github.com/InternLM/xtuner/assets/85681332/c01b55ca-ecc5-4ea5-83cd-02764d3c9835)

**Comment by LZHgrla** [comment]
Currently, `lmdeploy` doesn't support ChatGLM right now. Also, when using lmdeploy, you should convert llm to the type of lmdeploy first. More details can be found on [lmdeploy](https://github.com/InternLM/lmdeploy)

Though, you can use `xtuner chat` to chat with your model!
