### ISSUE TITLE
Huggingface website crushed

### ISSUE THREAD

**Issue by ALEX13679173326** [InternLM/xtuner#127]
I have this error. 'We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like internlm/internlm-7b is not the path to a directory containing a file named config.json'. How can I solve this problem. Is there any code to change?

**Comment by pppppM** [comment]
You can download through Model Scope, and then change the model path in Config to the downloaded folder.

``` 
from modelscope import snapshot_download
model_dir = snapshot_download("Shanghai_AI_Laboratory/internlm-7b", revision='v1.0.0')
print(model_dir)
```

**Comment by ALEX13679173326** [comment]
> You can download through Model Scope, and then change the model path in Config to the downloaded folder.
> 
> ```
> from modelscope import snapshot_download
> model_dir = snapshot_download("Shanghai_AI_Laboratory/internlm-7b", revision='v1.0.0')
> print(model_dir)
> ```

Thanks a lot !!
BYW, can I download the other models (Baichuan .etc) in the same way and change the model path?

**Comment by pppppM** [comment]
Sure
