### ISSUE TITLE
加载本地模型报错

### ISSUE THREAD

**Issue by gaoasi** [InternLM/xtuner#130]
您好，这边将internLM-7b的模型下载到本地之后，按照xtuner 增量训练的模式 xtuner train 之后，报错了，报错信息如下：

Unable to load weights from pytorch checkpoint file for '/gemini/pretrain/pytorch_model-00001-of-00008.bin'
![image](https://github.com/InternLM/xtuner/assets/43560964/656897ec-47eb-4e49-bcf8-951c0a18986d)
![image](https://github.com/InternLM/xtuner/assets/43560964/e12b0230-0b0b-4377-97ec-c43547956a8f)
我的配置是：
[config.txt](https://github.com/InternLM/xtuner/files/12672108/config.txt)

另外：我单独用transformers.AutoTokenizer.from_pretrained('/gemini/pretrain',trust_remote_code=True)加载没有问题的
![image](https://github.com/InternLM/xtuner/assets/43560964/ff5260a3-797f-4c76-9645-15f6c81b8d56)

这个是什么原因啊

**Comment by LZHgrla** [comment]
@gaoasi  可以试一下模型的load会不会报错
```
transformers.AutoModelForCausalLM.from_pretrained('/gemini/pretrain',trust_remote_code=True)
```

**Comment by gaoasi** [comment]
> @gaoasi 可以试一下模型的load会不会报错
> 
> ```
> transformers.AutoModelForCausalLM.from_pretrained('/gemini/pretrain',trust_remote_code=True)
> ```

抱歉，模型文件损坏了
