### ISSUE TITLE
evaluation freq和evaluation_inputs的作用是什么，跟验证集数据比例有关系吗

### ISSUE THREAD

**Issue by starkgao** [InternLM/xtuner#134]
在LLaMA-Efficient-Tuning有个验证集数据比例设置是按抽取总训练数据当中的百分之几来设置，例如：0.05就是百分之5，我不知道在配置文件里面应该怎么设置，只看到样例配置里面有这两个设置，不是很明白怎么使用。我的目的是想设置验证集数据大小。

**Comment by LZHgrla** [comment]
`evaluation_freq`和`evaluation_inputs`是用于训练过程中测试生成效果的，分别表示测试频率和测试的输入。

如果要设置数据比例，可以通过`process_hf_dataset`的`max_dataset_length`参数来设置，它表示随机选取当前数据集的样本个数. [Code](https://github.com/InternLM/xtuner/blob/main/xtuner/dataset/huggingface.py#L19C24-L19C48)

**Comment by starkgao** [comment]
> `evaluation_freq`和`evaluation_inputs`是用于训练过程中测试生成效果的，分别表示测试频率和测试的输入。
> 
> 如果要设置数据比例，可以通过`process_hf_dataset`的`max_dataset_length`参数来设置，它表示随机选取当前数据集的样本个数. [Code](https://github.com/InternLM/xtuner/blob/main/xtuner/dataset/huggingface.py#L19C24-L19C48)

这是用于验证集的吗，还是设置总训练集数据大小？

**Comment by starkgao** [comment]
框架是否可以达到，设置训练数据当中一定比例用于验证集的参数

**Comment by LZHgrla** [comment]
> > `evaluation_freq`和`evaluation_inputs`是用于训练过程中测试生成效果的，分别表示测试频率和测试的输入。
> > 如果要设置数据比例，可以通过`process_hf_dataset`的`max_dataset_length`参数来设置，它表示随机选取当前数据集的样本个数. [Code](https://github.com/InternLM/xtuner/blob/main/xtuner/dataset/huggingface.py#L19C24-L19C48)
> 
> 这是用于验证集的吗，还是设置总训练集数据大小？

训练集数据大小

**Comment by LZHgrla** [comment]
> 框架是否可以达到，设置训练数据当中一定比例用于验证集的参数，例如：给的数据200w，其中5%会用于验证集并且不会参与训练，还是说框架有自己的验证方式。

指令微调目前没有比较合适的定量评判标准，故没有对于验证集处理的设置。目前xtuner是通过测试训练过程中的生成效果来作为一种验证

**Comment by starkgao** [comment]
这两个 evaluation_freq和evaluation_inputs 参数不设置会有影响吗

**Comment by LZHgrla** [comment]
> 这两个 evaluation_freq和evaluation_inputs 参数不设置会有影响吗

不设置的话，那就是把这个hook关了（直接删掉即可），不影响训练
https://github.com/InternLM/xtuner/blob/5a4f9fdd7f6e7ae77ab56ee508b265dc280e0600/xtuner/configs/internlm/internlm_7b/internlm_7b_full_alpaca_e3.py#L114-L119

**Comment by starkgao** [comment]
还有一个就是模型输出路径有没有参数设置

**Comment by starkgao** [comment]
我用LLaMA-Efficient-Tuning 想训练baichuan2 13B 显存不够无法训练，不知道xtuner可否训练，我想尝试训练baichuan2 13B和InternLM 20B 硬件是A6000 48G

**Comment by LZHgrla** [comment]
> 还有一个就是模型输出路径有没有参数设置
```
xtuner train XXX --work-dir $YOUR_PATH
```

**Comment by LZHgrla** [comment]
> 我用LLaMA-Efficient-Tuning 想训练baichuan2 13B 显存不够无法训练，不知道xtuner可否训练，我想尝试训练baichuan2 13B和InternLM 20B 硬件是A6000 48G

这两个，使用QLoRA 的话训练没问题，24GB就够

**Comment by starkgao** [comment]
save_strategy是怎么设置的，有没有那种设置间隔几个step保存一次的那种。就像 LLaMA-Efficient-Tuning 和 chatglm2 项目里面都有这个参数。

**Comment by LZHgrla** [comment]
> save_strategy是怎么设置的，有没有那种设置间隔几个step保存一次的那种。就像 LLaMA-Efficient-Tuning 和 chatglm2 项目里面都有这个参数。

xtuner默认的config基本都是epoch-base的训练配置，如果需要修改为step-base（或iter-base），可以参考 https://github.com/InternLM/xtuner/issues/117 

同时，xtuner的训练流程基本都是依赖MMEngine实现的（可以类比为transformers.trainer），可以关注MMEngine所提供的[文档](https://github.com/open-mmlab/mmengine/tree/main/docs/zh_cn)
