### ISSUE TITLE
OSError: ./work_dirs/internlm_7b_qlora_alpaca_e3_copy/pth2huggingface does not appear to have a file named config.json. 

### ISSUE THREAD

**Issue by RyanWu31** [InternLM/xtuner#135]
I've followed the tutorial in the readme to complete the fine-tuning of internlm_7b on the alpaca, and then I used the

xtuner convert pth_to_hf . /work_dirs/internlm_7b_qlora_alpaca_e3_copy/internlm_7b_qlora_alpaca_e3_copy.py . /work_dirs/internlm_7b_qlora_alpaca_e3_copy/epoch_1.pth . /work_dirs/internlm_7b_qlora_alpaca_e3_copy/pth2huggingface

After converting to a huggingface model, I next want to chat to the larger model that I've finished fine-tuning, but the generated folder doesn't have a config.json file, do I need to copy the config.json from internlm_7b into it? Or is there something wrong with the previous operation

**Comment by LZHgrla** [comment]
This command will generate an adapter file, which only contains the `adapter_config.json` and `adapter_model.bin`

You can chat with this adapter by 
```
xtuner chat $LLM --adapter $ADAPTER --prompt-template alpaca
```

Or, you can first merge this adapter to LLM by
```
xtuner convert merge $LLM $ADAPTER $SAVE_DIR
```
This will generate a LLM file, and you can chat with it by 
```
xtuner chat $LLM --prompt-template alpaca
```

**Comment by RyanWu31** [comment]
Got it. Thanks for your help.
