### ISSUE TITLE
xtuner convert pth_to_hf ${CONFIG_NAME_OR_PATH} ${PTH} ${SAVE_PATH} 参数不知道如何获取

### ISSUE THREAD

**Issue by racecdj** [InternLM/xtuner#145]
请问 ${PTH} 是什么？在运行完train后，如何获取${PTH}参数的值

**Comment by LZHgrla** [comment]
默认在执行命令的位置，`work_dirs/CONFIG_NAME`，存储着log文件，里面有训练所得的参数，比如`epoch_1.pth`就是对应的${PTH}参数
