### ISSUE TITLE
请问训练时如何设置动态system

### ISSUE THREAD

**Issue by 81549361** [InternLM/xtuner#146]
你好，我正在使用xtuner训练InternLM 20b qlora。
但是我只能在模板文件中修改system，而数据集每一段对话分别对应不同的提示词，我不知道如何设置。
我使用的是羊驼模板。
数据集格式是xtuner标准多轮对话格式。

**Comment by LZHgrla** [comment]
现阶段可以考虑在map_fn中实现，比如 https://github.com/InternLM/xtuner/blob/main/xtuner/dataset/map_fns/dataset_map_fns/openai_map_fn.py

同时，我们正在重构数据处理逻辑，后续对于`system`、`user`、`bot`这种数据格式有更好、更便利的支持，敬请期待～

**Comment by 81549361** [comment]
> 现在阶段可以考虑在map_fn中实现，比如https://github.com/InternLM/xtuner/blob/main/xtuner/dataset/map_fns/dataset_map_fns/openai_map_fn.py
> 
> 同时，我们正在重构数据处理这种逻辑，对于后续`system`、数据格式有更好、更方便的期待，我们～`user``bot`

我看到程序在使用moss数据集时会调用meta_instruction，我是否可以将数据集转为moss的格式来不修改代码实现这个功能？

**Comment by LZHgrla** [comment]
@81549361  
有一些挑战，MOSS的格式是一个自定义数据集（torch.utils.data.Dataset 类）对MOSS数据集做了深度适配（比如插件的处理）。但是，MOSS是一个很好的示例，如果您需要深度定制，也可以参照`MOSSSFTDataset`自己实现一个Dataset，只需要给出设计好`__geiitem__`和`__len__`接口即可
```python
    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return {'input_ids': self.data[index], 'labels': self.labels[index]}

```

**Comment by 81549361** [comment]
谢谢，另外我看了一下你发的[openai_map_fn.py](https://github.com/InternLM/xtuner/blob/main/xtuner/dataset/map_fns/dataset_map_fns/openai_map_fn.py)
是把system放在首个input中，并追加首个问题。
目前我也是这样来实现的，这种格式训练应该能达到多轮对话的效果是吗？

**Comment by LZHgrla** [comment]
我们在`oasst1`数据集上有实际测试，是能够实现多轮对话的～ 

可以在HuggingFace Hub找我们训练好的模型测试一下效果
https://huggingface.co/xtuner

**Comment by 81549361** [comment]
> 我们在`oasst1`数据集上有实际测试，是能够实现多轮对话的～
> 
> 可以在HuggingFace Hub找我们训练好的模型测试一下效果 https://huggingface.co/xtuner

谢谢！
