### ISSUE TITLE
[Bug] Can't the qwen model chane the target modules in xtuner?

### ISSUE THREAD

**Issue by amulil** [InternLM/xtuner#148]
```
ValueError: Target modules ['gate_proj', 'down_proj', 'up_proj'] not found in the base model. Please check the target modules and try again.
```

what's the reason of it?When I use this kind of target modules in llama2-7b which is ok.But When I use it in qwen-7b-chat.There is a error.

**Comment by pppppM** [comment]
The corresponding module name for Qwen is not `gate_proj `, `down_proj `, `up_proj`, but rather `w1`, `w2`, and `c_proj`.

https://huggingface.co/Qwen/Qwen-7B/blob/main/modeling_qwen.py#L255-L259

**Comment by amulil** [comment]
> The corresponding module name for Qwen is not `gate_proj `, `down_proj `, `up_proj`, but rather `w1`, `w2`, and `c_proj`.
> 
> https://huggingface.co/Qwen/Qwen-7B/blob/main/modeling_qwen.py#L255-L259

thanks, I'll try it.
