### ISSUE TITLE
docker容器里，pip install xtuner后，提示bash: xtuner: command not found

### ISSUE THREAD

**Issue by chelovek21** [InternLM/xtuner#157]
docker容器里，按照如下方式安装了xtuner
git clone https://github.com/InternLM/xtuner.git
cd xtuner
pip install -e '.[all]'
其它依赖环境都以配置好了，
在xtuner安装路径下，执行命令 xtuner list-cfg
提示错误：
bash: xtuner: command not found
这是什么原因，还需要配置软连接之类的吗？
pip list可以看到xtuner，本地安装成功了0.1.4版本。

**Comment by chelovek21** [comment]
尝试直接用train.py脚本直接调用也会解析config文件错误。
执行
NPROC_PER_NODE=4 python xtuner/tools/train.py  xtuner/configs/qwen/qwen_7b_chat/qwen_7b_chat_qlora_oasst1_e3.py

显示错误如下：
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/mmengine/config/config.py", line 1477, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style)
  File "/opt/conda/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 201, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
yapf.yapflib.errors.YapfError: <unknown>:13:14: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/LLM/workspace/internLM/xtuner/xtuner/tools/train.py", line 246, in <module>
    main()
  File "/mnt/LLM/workspace/internLM/xtuner/xtuner/tools/train.py", line 235, in main
    runner = Runner.from_cfg(cfg)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/runner.py", line 445, in from_cfg
    runner = cls(
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/runner.py", line 386, in __init__
    self._log_env(env_cfg)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/runner.py", line 2356, in _log_env
    self.logger.info(f'Config:\n{self.cfg.pretty_text}')
  File "/opt/conda/lib/python3.10/site-packages/mmengine/config/config.py", line 1482, in pretty_text
    raise SyntaxError('Failed to format the config file, please '
SyntaxError: Failed to format the config file, please check the syntax of:

**Comment by LZHgrla** [comment]
https://github.com/open-mmlab/mmengine/issues/1364

这个应该是与您遇到了类似的问题，可以从源码安装mmengine（相关pr尚未发版），或安装低版本yapf解决
```
pip uninstall mmengine; pip install git+https://github.com/open-mmlab/mmengine.git
```
```
pip install yapf==0.40.1
```

**Comment by LZHgrla** [comment]
> docker容器里，按照如下方式安装了xtuner git clone https://github.com/InternLM/xtuner.git cd xtuner pip install -e '.[all]' 其它依赖环境都以配置好了， 在xtuner安装路径下，执行命令 xtuner list-cfg 提示错误： bash: xtuner: command not found 这是什么原因，还需要配置软连接之类的吗？ pip list可以看到xtuner，本地安装成功了0.1.4版本。

xtuner 会安装到pip、python对应的那个bin文件夹（例如`~/anaconda3/envs/my_env/bin/`），可以查看一下该文件夹下是否有对应的程序

**Comment by chelovek21** [comment]
> [open-mmlab/mmengine#1364](https://github.com/open-mmlab/mmengine/issues/1364)
> 
> 这个应该是与您遇到了类似的问题，可以从源码安装mmengine（相关pr尚未发版），或安装低版本yapf解决
> 
> ```
> pip uninstall mmengine; pip install git+https://github.com/open-mmlab/mmengine.git
> ```
> 
> ```
> pip install yapf==0.40.1
> ```

首先感谢您的及时回复，已尝试过前面两种方法，源码安装mmengine，yapf==0.40.1、yapf==0.40.0、yapf==0.33.0均试过，还是报这个解析不了的错误。
![image](https://github.com/InternLM/xtuner/assets/33109344/c2e7d777-c6f0-4f8d-94b1-fe431137ac95)

**Comment by chelovek21** [comment]
> [open-mmlab/mmengine#1364](https://github.com/open-mmlab/mmengine/issues/1364)
> 
> 这个应该是与您遇到了类似的问题，可以从源码安装mmengine（相关pr尚未发版），或安装低版本yapf解决
> 
> ```
> pip uninstall mmengine; pip install git+https://github.com/open-mmlab/mmengine.git
> ```
> 
> ```
> pip install yapf==0.40.1
> ```

是的，按照这种方式就可以解决了，感谢您的及时回复。

**Comment by chelovek21** [comment]
> > docker容器里，按照如下方式安装了xtuner git clone https://github.com/InternLM/xtuner.git cd xtuner pip install -e '.[all]' 其它依赖环境都以配置好了， 在xtuner安装路径下，执行命令 xtuner list-cfg 提示错误： bash: xtuner: command not found 这是什么原因，还需要配置软连接之类的吗？ pip list可以看到xtuner，本地安装成功了0.1.4版本。
> 
> xtuner 会安装到pip、python对应的那个bin文件夹（例如`~/anaconda3/envs/my_env/bin/`），可以查看一下该文件夹下是否有对应的程序

确实，输入绝对路径即可启动xtuner命令了，我建个软链到系统bin即可使用，谢谢
