### ISSUE TITLE
按照教程安装运行，出现以下错误：   AttributeError: 'InternLMTokenizer' object has no attribute 'sp_model'

### ISSUE THREAD

**Issue by yrhub** [InternLM/xtuner#162]
安装教程安装运行，出现以下错误：   AttributeError: 'InternLMTokenizer' object has no attribute 'sp_model'

请问什么原因？谢谢！

**Comment by LZHgrla** [comment]
尝试更新LLM权重（InternLM HuggingFace最新版）可以解决这一问题

或者，尝试安装4.33.x版本的transformers
```shell
pip install transformers==4.33.3
```
