### ISSUE TITLE
是否支持TP模式下的lora训练

### ISSUE THREAD

**Issue by awmthink** [InternLM/xtuner#165]
目前想在多卡上采用lora训练更大的模型，比如20b以上，希望冻结的base模型能够能TP的形式并行，请问，在xtuner是否支持这种模式呢？

**Comment by LZHgrla** [comment]
目前暂不支持Tensor Parallel训练，但是可以使用DeepSpeed ZeRO-3 的切片策略，能够达到类似TP的效果
7B LoRA: 45GB * 8 -> with ZeRO-3 13GB * 8

同时，如果显存仍紧缺，可以考虑结合Offload

命令
```
NPROC_PER_NODE=${GPU_NUM} xtuner train $CONFIG --deepspeed deepspeed_zero3
NPROC_PER_NODE=${GPU_NUM} xtuner train $CONFIG --deepspeed deepspeed_zero3_offload
```
