### ISSUE TITLE
当一张GPU卡的大小不够大时，如何使用多张GPU卡一起参与merge步骤？

### ISSUE THREAD

**Issue by yrhub** [InternLM/xtuner#169]
当一张GPU卡的大小不够大时，如何使用多张GPU卡一起参与merge步骤？比如用多张3090卡来参与llama-70b与lora的merge步骤。谢谢！

**Comment by LZHgrla** [comment]
merge在创建模型时，使用的是`AutoModelForCausalLM.from_pretrained()`这一函数，里面使用的`device_map='auto'`，会自动将模型放到多张卡
https://github.com/InternLM/xtuner/blob/b1af677639d41df2956e46bd31836cde7cb133bb/xtuner/tools/model_converters/merge.py#L33-L39
