### ISSUE TITLE
能否给出一份对config文件中各参数的说明文档，非常感谢。

### ISSUE THREAD

**Issue by x2zz007** [InternLM/xtuner#174]
能否给出一份对config文件中各参数的说明文档，非常感谢。比如：llama2_7b_qlora_alpaca_zh_e3.py文件中的各个参数的含义。

**Comment by LZHgrla** [comment]
我们会尽快增加一份config介绍的文档，敬请期待

**Comment by LZHgrla** [comment]
@x2zz007 
https://github.com/InternLM/xtuner/pull/212
