### ISSUE TITLE
请问支持CodeLlama微调吗？

### ISSUE THREAD

**Issue by bank010** [InternLM/xtuner#179]

**Comment by LZHgrla** [comment]
可以支持。CodeLlama 的基础模型就是正常的 Llama 模型，可以基于 Llama 的 config 进行修改
https://github.com/InternLM/xtuner/issues/90

**Comment by xiaohangguo** [comment]
支持的，我试过了

**Comment by LZHgrla** [comment]
Closing this issue, feel free to reopen if you have more questions.
