### ISSUE TITLE
请教一个问题：xtuner/dataset/map_fns/template_map_fn.py文件中的template_map_fn()函数

### ISSUE THREAD

**Issue by yrhub** [InternLM/xtuner#180]
请教一个问题：xtuner/dataset/map_fns/template_map_fn.py文件中的template_map_fn()函数由原来的
def template_map_fn(example, template):
    conversation = example.get('conversation', [])
    for i, single_turn_conversation in enumerate(conversation):
        input = single_turn_conversation['input']
        if i == 0:
            single_turn_conversation['input'] = template.INSTRUCTION_START.format(input=input, round=i + 1)
        else:
            single_turn_conversation['input'] = template.INSTRUCTION.format(input=input, round=i + 1)
    return {'conversation': conversation}
	
	
更新为：
def template_map_fn(example, template):
    conversation = example.get('conversation', [])
    for i, single_turn_conversation in enumerate(conversation):
        input_text = ''
        input = single_turn_conversation.get('input', '')
        if input != '' and input is not None:
            input = template.INSTRUCTION.format(input=input, round=i + 1)
            input_text += input
            instruction_postfix = ''
        else:
            instruction_postfix = template.INSTRUCTION.split('{input}')[-1]
        system = single_turn_conversation.get('system', '')
        if system != '' and system is not None:
            system = template.SYSTEM.format(system=system)
            input_text = system + input_text
        single_turn_conversation['input'] = input_text + instruction_postfix
    return {'conversation': conversation}

是不是可以这么理解：
	原来的代码效果是：多轮对话的第1轮对话的input前会加上prompt文本，之后轮次的input前就不加了；
	更新后的代码效果是：多轮对话的每一轮对话的input前都会加上相应的prompt文本。

这么改有什么考虑吗？如果训练的时候多轮对话的每一轮对话的input前都加上prompt，那么推理的时候是不是每一次输入input时也要加上相应的prompt？谢谢解答！

**Comment by LZHgrla** [comment]
原先的 prompt_template 跟任务相关的 prompt，所以只在第一轮加。现在v0.1.5后的 prompt_template 是与模型对话模板相关的 prompt，所以每一轮都要加，而与任务相关的 prompt 单独处理为了 system_prompt。
