### ISSUE TITLE
V0.1.6版加载数据时出现：Loading a dataset cached in a LocalFileSystem is not supported.

### ISSUE THREAD

**Issue by yrhub** [InternLM/xtuner#181]
V0.1.6版加载数据时出现：Loading a dataset cached in a LocalFileSystem is not supported.

**Comment by LZHgrla** [comment]
@yrhub 
这个issue与你遇到的问题相似 https://github.com/huggingface/datasets/issues/6352
请尝试
```
pip install -U datasets
```
