### ISSUE TITLE
will to add qwen-vl ? Thanks

### ISSUE THREAD

**Issue by FDInSky** [InternLM/xtuner#182]

**Comment by LZHgrla** [comment]
Now, we are woking on the reproduction of Llava and minigpt, (including Pre-training and fine-tuning!).
Thus, other multi-modal LLMs have not been considered yet.


However, we greatly welcome any ideas of the designing of Qwen-VL fine-tuning,  such as "how to use open-source dataset formats to fine-tune Qwen-VL", "which down-stream datasets can be used to fine-tune Qwen-VL", and so on. If anyone have some thoughts, please let us know!

**Comment by FDInSky** [comment]
> Now, we are woking on the reproduction of Llava and minigpt, (including Pre-training and fine-tuning!). Thus, other multi-modal LLMs have not been considered yet.
> 
> However, we greatly welcome any ideas of the designing of Qwen-VL fine-tuning, such as "how to use open-source dataset formats to fine-tune Qwen-VL", "which down-stream datasets can be used to fine-tune Qwen-VL", and so on. If anyone have some thoughts, please let us know!

When will open llava or minigpt4，we can follow them to add qwen-vl.

**Comment by LZHgrla** [comment]
@FDInSky  The support of Llava is expected within about one week (at most two weeks :)), and as for the minigpt-4, we needs more time.
