### ISSUE TITLE
xtuner train qlora 微调后 只生成了pth文件，使用xtuner convert pth_to_hf 提示缺少 adapter_config.json文件

### ISSUE THREAD

**Issue by zhangxinfang520** [InternLM/xtuner#185]

**Comment by LZHgrla** [comment]
请张贴一下完整的命令，我们仔细看一下～

**Comment by zhangxinfang520** [comment]
> 请张贴一下完整的命令，我们仔细看一下～

xtuner train chatglm3_6b_base_qlora_sql_e3_copy.py 这个是指令 chatglm3_6b_base_qlora_sql_e3_copy.py 来源于 执行 xtuner copy-cfg  chatglm3_6b_base_qlora_sql_e3  修改了加载本地模型 和自定义数据集 训练了3epoch work_dirs 里面有三个pt文件 但是没有adapter_config.json 导致 xtuner convert pth_to_hf 失败

**Comment by LZHgrla** [comment]
xtuner convert pth_to_hf 无需 adapter_config.json

```
xtuner convert pth_to_hf ${CONFIG_NAME_OR_PATH} ${PTH} ${SAVE_PATH}
```

**Comment by happened** [comment]
我也遇到了同样的问题，缺失一个文件。
![image](https://github.com/InternLM/xtuner/assets/20530955/45c3d1f9-1052-4409-81e1-07a57092fc18)

**Comment by zhangxinfang520** [comment]
> xtuner convert pth_to_hf 无需 adapter_config.json
> 
> ```
> xtuner convert pth_to_hf ${CONFIG_NAME_OR_PATH} ${PTH} ${SAVE_PATH}

> ```

CONFIG_NAME_OR_PATH 是代表原大模型的路径吧？ 我的模型权重是修改了路径加载进来

**Comment by happened** [comment]
> 我也遇到了同样的问题，缺失一个文件。 ![image](https://user-images.githubusercontent.com/20530955/279002021-45c3d1f9-1052-4409-81e1-07a57092fc18.png) ![image](https://user-images.githubusercontent.com/20530955/279002158-22573049-c962-44b5-944b-827809c95649.png)
这是微调阶段的脚本log
![image](https://github.com/InternLM/xtuner/assets/20530955/7bf6a041-fd15-4fda-84ee-7bc8264e4a30)

**Comment by zhangxinfang520** [comment]
> > 我也遇到了同样的问题，缺失一个文件。 ![image](https://user-images.githubusercontent.com/20530955/279002021-45c3d1f9-1052-4409-81e1-07a57092fc18.png) ![image](https://user-images.githubusercontent.com/20530955/279002158-22573049-c962-44b5-944b-827809c95649.png)
> > 这是微调阶段的脚本log
> > ![image](https://user-images.githubusercontent.com/20530955/279003444-cf30c012-378f-40aa-b716-92c107b4c946.png)
> 
> chat的命令如下 `xtuner convert pth_to_hf internlm_chat_7b_qlora_alpaca_e3_copy.py work_dirs/internlm_chat_7b_qlora_alpaca_e3_copy/ /data2/models/internlm-chat-7b-ft/`

我试了 使用他们脚本不copy配置文件 然后大模型在训练的时候download下来了 不用dapter_config.json 是可以合并的 但是想我们这样 copy配置文件 修改里面的路径配置 就合并不了

**Comment by LZHgrla** [comment]
> > 我也遇到了同样的问题，缺失一个文件。 ![image](https://user-images.githubusercontent.com/20530955/279002021-45c3d1f9-1052-4409-81e1-07a57092fc18.png) ![image](https://user-images.githubusercontent.com/20530955/279002158-22573049-c962-44b5-944b-827809c95649.png)
> > 这是微调阶段的脚本log
> > ![image](https://user-images.githubusercontent.com/20530955/279003444-cf30c012-378f-40aa-b716-92c107b4c946.png)
> 
> chat的命令如下 `xtuner convert pth_to_hf internlm_chat_7b_qlora_alpaca_e3_copy.py work_dirs/internlm_chat_7b_qlora_alpaca_e3_copy/ /data2/models/internlm-chat-7b-ft/`

$PTH 不对，需要到epoch_xxx.pth这一层级的路径

**Comment by LZHgrla** [comment]
> > > 我也遇到了同样的问题，缺失一个文件。 ![image](https://user-images.githubusercontent.com/20530955/279002021-45c3d1f9-1052-4409-81e1-07a57092fc18.png) ![image](https://user-images.githubusercontent.com/20530955/279002158-22573049-c962-44b5-944b-827809c95649.png)
> > > 这是微调阶段的脚本log
> > > ![image](https://user-images.githubusercontent.com/20530955/279003444-cf30c012-378f-40aa-b716-92c107b4c946.png)
> > 
> > 
> > chat的命令如下 `xtuner convert pth_to_hf internlm_chat_7b_qlora_alpaca_e3_copy.py work_dirs/internlm_chat_7b_qlora_alpaca_e3_copy/ /data2/models/internlm-chat-7b-ft/`
> 
> 我试了 使用他们脚本不copy配置文件 然后大模型在训练的时候download下来了 不用dapter_config.json 是可以合并的 但是想我们这样 copy配置文件 修改里面的路径配置 就合并不了

你们好像不是同一个问题... 在convert pth_to_hf 阶段，是不需要adapter_config.json这个文件的，

> > xtuner convert pth_to_hf 无需 adapter_config.json
> > ```
> > xtuner convert pth_to_hf ${CONFIG_NAME_OR_PATH} ${PTH} ${SAVE_PATH}
> > ```
> 
> > 
> 
> CONFIG_NAME_OR_PATH 是代表原大模型的路径吧？ 我的模型权重是修改了路径加载进来

CONFIG_NAME_OR_PATH 是config的路径，不是大模型

**Comment by LZHgrla** [comment]
> > xtuner convert pth_to_hf 无需 adapter_config.json
> > ```
> > xtuner convert pth_to_hf ${CONFIG_NAME_OR_PATH} ${PTH} ${SAVE_PATH}
> > ```
> 
> > 
> 
> CONFIG_NAME_OR_PATH 是代表原大模型的路径吧？ 我的模型权重是修改了路径加载进来

CONFIG_NAME_OR_PATH 代表 config路径，不是模型路径

**Comment by happened** [comment]
好的，切换了下命令
`xtuner convert pth_to_hf internlm_chat_7b_qlora_alpaca_e3_copy.py work_dirs/internlm_chat_7b_qlora_alpaca_e3_copy/epoch_3.pth /data2/models/internlm-chat-7b-ft/1`  $PATH得指定具体的pth
