### ISSUE TITLE
chat模式下使用InternLM7B 一直生成

### ISSUE THREAD

**Issue by lionelmessigoat** [InternLM/xtuner#186]
`xtuner chat ./models/internlm-7b/ --prompt-template internlm_chat`

![yAf3LVkYs8](https://github.com/InternLM/xtuner/assets/149141465/47f122d4-4fb9-4793-95d3-58ec9a29279a)

**Comment by LZHgrla** [comment]
这是base模型，需要经过chat微调才可以，或者您可以尝试跟chat模型(internlm/internlm-chat-7b)对话

**Comment by lionelmessigoat** [comment]
> 这是base模型，需要经过chat微调才可以，或者您可以尝试跟chat模型(internlm/internlm-chat-7b)对话

解决了，谢谢

**Comment by lionelmessigoat** [comment]
> 这是base模型，需要经过chat微调才可以，或者您可以尝试跟chat模型(internlm/internlm-chat-7b)对话

解决了，谢谢
