### ISSUE TITLE
how to fix : grad_norm: nan

### ISSUE THREAD

**Issue by leoluopy** [InternLM/xtuner#187]
10/30 22:18:02 - mmengine - INFO - Epoch(train) [1][200/735]  lr: 1.9870e-04  eta: 2:46:39  time: 2.8906  data_time: 0.0042  memory: 10762  loss: 2.7522  grad_norm: 3.0608
10/30 22:18:30 - mmengine - INFO - Epoch(train) [1][210/735]  lr: 1.9857e-04  eta: 2:46:12  time: 2.8865  data_time: 0.0041  memory: 10762  loss: 2.6150  grad_norm: 2.7647
10/30 22:18:59 - mmengine - INFO - Epoch(train) [1][220/735]  lr: 1.9843e-04  eta: 2:45:44  time: 2.8826  data_time: 0.0040  memory: 10762  loss: 2.6687  grad_norm: 2.7647
10/30 22:19:28 - mmengine - INFO - Epoch(train) [1][230/735]  lr: 1.9828e-04  eta: 2:45:16  time: 2.8833  data_time: 0.0040  memory: 10762  loss: 2.7682  grad_norm: 2.5099
10/30 22:19:57 - mmengine - INFO - Epoch(train) [1][240/735]  lr: 1.9813e-04  eta: 2:44:49  time: 2.8874  data_time: 0.0042  memory: 10762  loss: 2.5128  grad_norm: nan
10/30 22:20:26 - mmengine - INFO - Epoch(train) [1][250/735]  lr: 1.9797e-04  eta: 2:44:21  time: 2.8906  data_time: 0.0039  memory: 10762  loss: 2.4566  grad_norm: nan

**Comment by leoluopy** [comment]
10/30 22:19:28 - mmengine - INFO - Epoch(train) [1][230/735]  lr: 1.9828e-04  eta: 2:45:16  time: 2.8833  data_time: 0.0040  memory: 10762  loss: 2.7682  grad_norm: 2.5099
10/30 22:19:57 - mmengine - INFO - Epoch(train) [1][240/735]  lr: 1.9813e-04  eta: 2:44:49  time: 2.8874  data_time: 0.0042  memory: 10762  loss: 2.5128  grad_norm: nan
10/30 22:20:26 - mmengine - INFO - Epoch(train) [1][250/735]  lr: 1.9797e-04  eta: 2:44:21  time: 2.8906  data_time: 0.0039  memory: 10762  loss: 2.4566  grad_norm: nan
10/30 22:20:55 - mmengine - INFO - Epoch(train) [1][260/735]  lr: 1.9780e-04  eta: 2:43:54  time: 2.8882  data_time: 0.0041  memory: 10762  loss: 2.5883  grad_norm: nan
10/30 22:21:24 - mmengine - INFO - Epoch(train) [1][270/735]  lr: 1.9763e-04  eta: 2:43:26  time: 2.8905  data_time: 0.0040  memory: 10762  loss: 2.3131  grad_norm: nan
10/30 22:21:52 - mmengine - INFO - Epoch(train) [1][280/735]  lr: 1.9745e-04  eta: 2:42:58  time: 2.8837  data_time: 0.0039  memory: 10762  loss: 2.6378  grad_norm: nan
10/30 22:22:21 - mmengine - INFO - Epoch(train) [1][290/735]  lr: 1.9727e-04  eta: 2:42:30  time: 2.8840  data_time: 0.0040  memory: 10762  loss: 2.0521  grad_norm: nan
10/30 22:22:50 - mmengine - INFO - Epoch(train) [1][300/735]  lr: 1.9708e-04  eta: 2:42:01  time: 2.8837  data_time: 0.0041  memory: 10762  loss: 2.4867  grad_norm: nan
10/30 22:23:19 - mmengine - INFO - Epoch(train) [1][310/735]  lr: 1.9688e-04  eta: 2:41:33  time: 2.8831  data_time: 0.0041  memory: 10762  loss: 2.2350  grad_norm: nan
10/30 22:23:48 - mmengine - INFO - Epoch(train) [1][320/735]  lr: 1.9667e-04  e

**Comment by LZHgrla** [comment]
Try to use a small learning rate, e.g., 2e-5?

**Comment by LZHgrla** [comment]
Closing this issue, feel free to reopen if you have more questions.
