### ISSUE TITLE
how to disable weight saving or lower the  weight saving frequency  ?

### ISSUE THREAD

**Issue by leoluopy** [InternLM/xtuner#192]
as title has mentioned , how should i modify the config like chatglm2_6b_qlora_alpaca_zh_e3_copy.py .

**Comment by leoluopy** [comment]
@LZHgrla  , hi , do you have  any idea about the question mentioned .

**Comment by LZHgrla** [comment]
https://github.com/InternLM/xtuner/blob/b1647a75005528db4f254bb9163c29f88abb25e6/xtuner/configs/internlm/internlm_7b/internlm_7b_qlora_oasst1_e3.py#L154

We use MMEngine to implement the trainer and utilize its CheckpointHook. The related docs can be found here [zh_cn](https://github.com/open-mmlab/mmengine/blob/main/docs/zh_cn/tutorials/hook.md#checkpointhook), [en](https://github.com/open-mmlab/mmengine/blob/main/docs/en/tutorials/hook.md#checkpointhook).

**Comment by leoluopy** [comment]
thanks .
