### ISSUE TITLE
tuning failed 微调失败

### ISSUE THREAD

**Issue by creegon** [InternLM/xtuner#193]
https://github.com/InternLM/xtuner/discussions/153
按照上面这个教程进行的，然后顺利执行了每一个步骤，没有报错。
但是在合并完，进行推理时，微调的数据集全都没有效果了（大模型完全不知道，和微调前输出完全一样）。尝试更改了超参数，比如把max_epochs调到100，但是仍然无效。
想问一下可能会是什么原因？感激不尽！

**Comment by LZHgrla** [comment]
在训练过程中有使用`EvaluateChatHook`中的`evaluation_inputs`测试生成效果吗？

**Comment by creegon** [comment]
训练数据集是这样的：
[{
    "conversation":[
        {
            "system": "",
            "input": "你好! ",
            "output": "你好!  有什么我能帮助你的呢! "
        },
        {
            "input": "请介绍一下 XTuner",
            "output": "XTuner 是上海AI实验室书生·浦语大模型开源工具链中的轻量级低成本微调工具"
        },
        {
            "input": "谢谢!",
            "output": "不用客气! "
        }
    ]
}

**Comment by LZHgrla** [comment]
数据量太少了（从log看，每个epoch只有一个iteration）。这使得参数更新的次数很少，学不到数据集的信息

**Comment by creegon** [comment]
那如果我只是想测试一下这个数据的话，能否通过把这个数据复制粘贴数十次的方式来让数据量增大？

**Comment by LZHgrla** [comment]
可以再夸张一点，比如5000次

**Comment by creegon** [comment]
好的，谢谢谢谢！
