### ISSUE TITLE
How to use multi node to fine-tuned model in xtuner?

### ISSUE THREAD

**Issue by amulil** [InternLM/xtuner#197]
.

**Comment by LZHgrla** [comment]
https://github.com/InternLM/xtuner#fine-tune-

You can use slurm to launch xtuner
srun ${SRUN_ARGS} xtuner train internlm_7b_qlora_oasst1_e3 --launcher slurm

**Comment by amulil** [comment]
> https://github.com/InternLM/xtuner#fine-tune-
> 
> You can use slurm to launch xtuner srun ${SRUN_ARGS} xtuner train internlm_7b_qlora_oasst1_e3 --launcher slurm

thanks, I will try it.

**Comment by amulil** [comment]
@LZHgrla I'm not familiar with slurm, do you have any examples for it?Such as, I have 2-nodes(8*A800-80G * 2), how should I set ${SRUN_ARGS}, I didn't find how to set it in the README.md.

**Comment by LZHgrla** [comment]
```
srun -p ${PARTION} --job-name=${JOB_NAME} --nodes=2 --gres=gpu:8 --ntasks-per-node=8 --kill-on-bad-exit=1 xtuner train ${CONFIG} --launcher slurm
```

**Comment by amulil** [comment]
> ```
> srun -p ${PARTITION} --job-name=${JOB_NAME} --nodes=2 --gres=gpu:8 --ntasks-per-node=8 --kill-on-bad-exit=1 xtuner train ${CONFIG} --launcher slurm
> ```

@LZHgrla thanks, do you have an example of `slurm.conf` and which version of slurm should I use?

**Comment by LZHgrla** [comment]
> > ```
> > srun -p ${PARTITION} --job-name=${JOB_NAME} --nodes=2 --gres=gpu:8 --ntasks-per-node=8 --kill-on-bad-exit=1 xtuner train ${CONFIG} --launcher slurm
> > ```
> 
> @LZHgrla thanks, do you have an example of `slurm.conf` and which version of slurm should I use?

Sorry, I have no ideas about the setup of slurm. Maybe you can search the related docs!

**Comment by amulil** [comment]
> > > ```
> > > srun -p ${PARTITION} --job-name=${JOB_NAME} --nodes=2 --gres=gpu:8 --ntasks-per-node=8 --kill-on-bad-exit=1 xtuner train ${CONFIG} --launcher slurm
> > > ```
> > 
> > 
> > @LZHgrla thanks, do you have an example of `slurm.conf` and which version of slurm should I use?
> 
> Sorry, I have no ideas about the setup of slurm. Maybe you can search the related docs!

I use slurm succesfully, and the log has the output as the below
```
11/07 18:52:38 - mmengine - INFO - Exp name: yi_6b_qlora_alpaca_enzh_oasst1_medical_e3_sync_params_gpu8_4k_20231107_152147
11/07 18:52:38 - mmengine - INFO - Saving checkpoint at 3 epochs
```
But,there is no file in the work_dirs. Do you know what's the resaon of it? Is it a bug of `xtuner`?

**Comment by LZHgrla** [comment]
@amulil  
Is there nothing in `work_dirs` or is  there no `epoch_3.pth`?

**Comment by amulil** [comment]
> @amulil Is there nothing in `work_dirs` or is there no `epoch_3.pth`?

nothing, the whole dir is empty.

**Comment by LZHgrla** [comment]
@amulil 
Please try to exec these code with multi-node slurm and then check the dir
```python
import os.path as osp
import mmengine
work_dir = osp.abspath('./work_dirs/test_dir')
mmengine.mkdir_or_exist(work_dir)
```

**Comment by amulil** [comment]
> ```python
> import os.path as osp
> import mmengine
> work_dir = osp.abspath('./work_dirs/test_dir')
> mmengine.mkdir_or_exist(work_dir)
> ```

I execute the program in the node2(control machine), the result is saved at the node1.It seems that which node is choosen firstly, the result will be saved at that machine.

**Comment by LZHgrla** [comment]
Congrats!

> > ```python
> > import os.path as osp
> > import mmengine
> > work_dir = osp.abspath('./work_dirs/test_dir')
> > mmengine.mkdir_or_exist(work_dir)
> > ```
> 
> I execute the program in the node2(control machine), the result is saved at the node1.It seems that which node is choosen firstly, the result will be saved at that machine. And I found pth file in the node1.
