### ISSUE TITLE
增量预训练数据集是否需要拆分

### ISSUE THREAD

**Issue by wkqscut** [InternLM/xtuner#198]
{
    "conversation":[
        {
            "system": "",
            "input": "",
            "output": "I am an artificial intelligence (AI) assistant named Puyu. I was created by the Shanghai AI Laboratory and my purpose is to assist users with various tasks through natural language processing technology."
        }
    ]
}

增量预训练数据格式中的output内容可以放一个长文档（比如一本书）吗，还是需要切分成一定的长度

**Comment by LZHgrla** [comment]
需要提前切分

**Comment by wkqscut** [comment]
> 需要提前切分

每个对话可以切分到最长多少呢

**Comment by LZHgrla** [comment]
> > 需要提前切分
> 
> 好的，每个对话最长多少呢，是会截断到配置里的max_length么

切分的时候长度可以短一点，后续`pack_to_max_length`会自动将多条样本拼接到max_length

**Comment by wkqscut** [comment]
> > > 需要提前切分
> > 
> > 
> > 好的，每个对话最长多少呢，是会截断到配置里的max_length么
> 
> 切分的时候长度可以短一点，后续`pack_to_max_length`会自动将多条样本拼接到max_length

好的，谢谢大佬

**Comment by maxchiron** [comment]
> > > 需要提前切分
> > 
> > 
> > 好的，每个对话最长多少呢，是会截断到配置里的max_length么
> 
> 切分的时候长度可以短一点，后续`pack_to_max_length`会自动将多条样本拼接到max_length

大佬请问拼接的时候需要进行一定程度的上下文重合吗？以保证上下文的连贯性？比如：
```
{
"conversation":[
{
"system": "",
"input": "",
"output": "I am Puyu. I was created by the Shanghai AI Laboratory."
}
]
}
```

```
{
"system": "",
"input": "",
"output": "I was created by the Shanghai AI Laboratory. My purpose is to assist users."
}
]
}
```

**Comment by LZHgrla** [comment]
@maxchiron  当然可以。但请务必在dataset上设置`shuffle_before_pack=False`，以避免顺序被打乱

**Comment by maxchiron** [comment]
> @maxchiron 当然可以。但请务必在dataset上设置`shuffle_before_pack=False`，以避免顺序被打乱

谢谢回复。那如果这样的话，在后续`pack_to_max_length`使，中间重复的部分是不是就会在拼接后的数据中被重复两次了吖？比如：
```
{
"system": "",
"input": "",
"output": "I am Puyu. I was created by the Shanghai AI Laboratory. I was created by the Shanghai AI Laboratory. My purpose is to assist users."
}
]
}
```

**Comment by LZHgrla** [comment]
@maxchiron  是的，所以在切分时 windows 大小和 step_size 一致即可

**Comment by LZHgrla** [comment]
@maxchiron  跟config无关，就是随便的一个说法，windows表示切片大小，step_size可以理解成步长。 windows > step_size 就会导致文本重叠
