### ISSUE TITLE
chatglm3-6b和chatglm3-6b-base训练后合并模型，加载报错

### ISSUE THREAD

**Issue by sd49124800** [InternLM/xtuner#199]
有人知道是什么原因吗？
Traceback (most recent call last):
  File "/root/autodl-tmp/ChatGLM3/cli_demo.py", line 7, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b-train", trust_remote_code=True)
  File "/root/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 678, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/root/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/root/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-train/tokenization_chatglm.py", line 93, in __init__
    super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=clean_up_tokenization_spaces, **kwargs)
  File "/root/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 347, in __init__
    super().__init__(**kwargs)
  File "/root/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1548, in __init__
    super().__init__(**kwargs)
  File "/root/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 842, in __init__
    setattr(self, key, value)
AttributeError: can't set attribute 'eos_token'

**Comment by LZHgrla** [comment]
1. 使用的 tokenizer 有点问题，可以将合并得到的`tokenizer_config.json` 与 ChatGLM3 开源的 `tokenizer_config.json` 对比一下，是否多了 `eos_token` 这个参数？我们实测时一切是正常的，如果确实多了这个参数您可以将您所使用的命令贴一下，我们尝试复现一下问题。

2. 除此之外，您也可以尝试直接使用原模型的tokenizer。

**Comment by ioir123ju** [comment]
我也遇到了同样的问题，以下是两个tokenizer对比
原版
`{
  "name_or_path": "THUDM/chatglm3-6b-base",
  "remove_space": false,
  "do_lower_case": false,
  "tokenizer_class": "ChatGLMTokenizer",
  "auto_map": {
    "AutoTokenizer": [
      "tokenization_chatglm.ChatGLMTokenizer",
      null
      ]
  }
}
`
合并后
`{
  "added_tokens_decoder": {},
  "auto_map": {
    "AutoTokenizer": [
      "tokenization_chatglm.ChatGLMTokenizer",
      null
    ]
  },
  "clean_up_tokenization_spaces": false,
  "do_lower_case": false,
  "eos_token": "</s>",
  "model_max_length": 1000000000000000019884624838656,
  "pad_token": "<unk>",
  "padding_side": "left",
  "remove_space": false,
  "tokenizer_class": "ChatGLMTokenizer",
  "unk_token": "<unk>"
}
`

**Comment by LZHgrla** [comment]
> 我也遇到了同样的问题，以下是两个tokenizer对比
> 
> 原版
> 
> `{
> 
>   "name_or_path": "THUDM/chatglm3-6b-base",
> 
>   "remove_space": false,
> 
>   "do_lower_case": false,
> 
>   "tokenizer_class": "ChatGLMTokenizer",
> 
>   "auto_map": {
> 
>     "AutoTokenizer": [
> 
>       "tokenization_chatglm.ChatGLMTokenizer",
> 
>       null
> 
>       ]
> 
>   }
> 
> }
> 
> `
> 
> 合并后
> 
> `{
> 
>   "added_tokens_decoder": {},
> 
>   "auto_map": {
> 
>     "AutoTokenizer": [
> 
>       "tokenization_chatglm.ChatGLMTokenizer",
> 
>       null
> 
>     ]
> 
>   },
> 
>   "clean_up_tokenization_spaces": false,
> 
>   "do_lower_case": false,
> 
>   "eos_token": "</s>",
> 
>   "model_max_length": 1000000000000000019884624838656,
> 
>   "pad_token": "<unk>",
> 
>   "padding_side": "left",
> 
>   "remove_space": false,
> 
>   "tokenizer_class": "ChatGLMTokenizer",
> 
>   "unk_token": "<unk>"
> 
> }
> 
> `

transformers的版本是多少呀

**Comment by LZHgrla** [comment]
@sd49124800  @ioir123ju 
我在transformers v4.35.0 release版本上复现出了这一问题
暂时可以尝试安装低版本 transformers ，重新保存tokenizer，就可以解决这一问题
```
pip install transformers==4.34.0
```

**Comment by LZHgrla** [comment]
在 ChatGLM3 官方 repo 提了一个相关的 issue，可以关注
https://github.com/THUDM/ChatGLM3/issues/152

**Comment by sd49124800** [comment]
> 1. 使用的 tokenizer 有点问题，可以将合并得到的`tokenizer_config.json` 与 ChatGLM3 开源的 `tokenizer_config.json` 对比一下，是否多了 `eos_token` 这个参数？我们实测时一切是正常的，如果确实多了这个参数您可以将您所使用的命令贴一下，我们尝试复现一下问题。
> 2. 除此之外，您也可以尝试直接使用原模型的tokenizer。

按照此方法模型可用了，但是出现一些新的小问题，跟模型对话时候经常抛异常，提示无法分割\n这样的，cli_demo和web_demo都会这样

**Comment by LZHgrla** [comment]
> > 1. 使用的 tokenizer 有点问题，可以将合并得到的`tokenizer_config.json` 与 ChatGLM3 开源的 `tokenizer_config.json` 对比一下，是否多了 `eos_token` 这个参数？我们实测时一切是正常的，如果确实多了这个参数您可以将您所使用的命令贴一下，我们尝试复现一下问题。
> > 2. 除此之外，您也可以尝试直接使用原模型的tokenizer。
> 
> 按照此方法模型可用了，但是出现一些新的小问题，跟模型对话时候经常抛异常，提示无法分割\n这样的，cli_demo和web_demo都会这样

官方模型会有这个问题吗？

**Comment by sd49124800** [comment]
> > > 1. 使用的 tokenizer 有点问题，可以将合并得到的`tokenizer_config.json` 与 ChatGLM3 开源的 `tokenizer_config.json` 对比一下，是否多了 `eos_token` 这个参数？我们实测时一切是正常的，如果确实多了这个参数您可以将您所使用的命令贴一下，我们尝试复现一下问题。
> > > 2. 除此之外，您也可以尝试直接使用原模型的tokenizer。
> > 
> > 
> > 按照此方法模型可用了，但是出现一些新的小问题，跟模型对话时候经常抛异常，提示无法分割\n这样的，cli_demo和web_demo都会这样
> 
> 官方模型会有这个问题吗？

官方模型没有这个问题

**Comment by LZHgrla** [comment]
> > > > 1. 使用的 tokenizer 有点问题，可以将合并得到的`tokenizer_config.json` 与 ChatGLM3 开源的 `tokenizer_config.json` 对比一下，是否多了 `eos_token` 这个参数？我们实测时一切是正常的，如果确实多了这个参数您可以将您所使用的命令贴一下，我们尝试复现一下问题。
> > > > 2. 除此之外，您也可以尝试直接使用原模型的tokenizer。
> > > 
> > > 
> > > 按照此方法模型可用了，但是出现一些新的小问题，跟模型对话时候经常抛异常，提示无法分割\n这样的，cli_demo和web_demo都会这样
> > 
> > 
> > 官方模型会有这个问题吗？
> 
> 官方模型没有这个问题

报错信息贴一下吧，命令也贴一下，我们尝试复现一下看看问题在哪

**Comment by sd49124800** [comment]
> > > > > 1. 使用的 tokenizer 有点问题，可以将合并得到的`tokenizer_config.json` 与 ChatGLM3 开源的 `tokenizer_config.json` 对比一下，是否多了 `eos_token` 这个参数？我们实测时一切是正常的，如果确实多了这个参数您可以将您所使用的命令贴一下，我们尝试复现一下问题。
> > > > > 2. 除此之外，您也可以尝试直接使用原模型的tokenizer。
> > > > 
> > > > 
> > > > 按照此方法模型可用了，但是出现一些新的小问题，跟模型对话时候经常抛异常，提示无法分割\n这样的，cli_demo和web_demo都会这样
> > > 
> > > 
> > > 官方模型会有这个问题吗？
> > 
> > 
> > 官方模型没有这个问题
> 
> 报错信息贴一下吧，命令也贴一下，我们尝试复现一下看看问题在哪

好的稍等我去复现一下

**Comment by sd49124800** [comment]
> > > > > 1. 使用的 tokenizer 有点问题，可以将合并得到的`tokenizer_config.json` 与 ChatGLM3 开源的 `tokenizer_config.json` 对比一下，是否多了 `eos_token` 这个参数？我们实测时一切是正常的，如果确实多了这个参数您可以将您所使用的命令贴一下，我们尝试复现一下问题。
> > > > > 2. 除此之外，您也可以尝试直接使用原模型的tokenizer。
> > > > 
> > > > 
> > > > 按照此方法模型可用了，但是出现一些新的小问题，跟模型对话时候经常抛异常，提示无法分割\n这样的，cli_demo和web_demo都会这样
> > > 
> > > 
> > > 官方模型会有这个问题吗？
> > 
> > 
> > 官方模型没有这个问题
> 
> 报错信息贴一下吧，命令也贴一下，我们尝试复现一下看看问题在哪

我发现是因为推理返回内容是空导致的，模型合并后有概率会返回为空的推理，同样的问题重复提交几次才会正确响应

**Comment by LZHgrla** [comment]
> > > > > > 1. 使用的 tokenizer 有点问题，可以将合并得到的`tokenizer_config.json` 与 ChatGLM3 开源的 `tokenizer_config.json` 对比一下，是否多了 `eos_token` 这个参数？我们实测时一切是正常的，如果确实多了这个参数您可以将您所使用的命令贴一下，我们尝试复现一下问题。
> > > > > > 2. 除此之外，您也可以尝试直接使用原模型的tokenizer。
> > > > > 
> > > > > 
> > > > > 按照此方法模型可用了，但是出现一些新的小问题，跟模型对话时候经常抛异常，提示无法分割\n这样的，cli_demo和web_demo都会这样
> > > > 
> > > > 
> > > > 官方模型会有这个问题吗？
> > > 
> > > 
> > > 官方模型没有这个问题
> > 
> > 
> > 报错信息贴一下吧，命令也贴一下，我们尝试复现一下看看问题在哪
> 
> 我发现是因为推理返回内容是空导致的，模型合并后有概率会返回为空的推理，同样的问题重复提交几次才会正确响应

可能是prompt不同导致的。建议还是用xtuner chat来对话：
```
xtuner chat $LLM --prompt-template default
xtuner chat $LLM --adapter $ADAPTER --prompt-template default 
```

同时也可以使用 `--bits 4` 或 `--bits 8` 来进一步降低显存开销！

**Comment by sd49124800** [comment]
> > > > > > > 1. 使用的 tokenizer 有点问题，可以将合并得到的`tokenizer_config.json` 与 ChatGLM3 开源的 `tokenizer_config.json` 对比一下，是否多了 `eos_token` 这个参数？我们实测时一切是正常的，如果确实多了这个参数您可以将您所使用的命令贴一下，我们尝试复现一下问题。
> > > > > > > 2. 除此之外，您也可以尝试直接使用原模型的tokenizer。
> > > > > > 
> > > > > > 
> > > > > > 按照此方法模型可用了，但是出现一些新的小问题，跟模型对话时候经常抛异常，提示无法分割\n这样的，cli_demo和web_demo都会这样
> > > > > 
> > > > > 
> > > > > 官方模型会有这个问题吗？
> > > > 
> > > > 
> > > > 官方模型没有这个问题
> > > 
> > > 
> > > 报错信息贴一下吧，命令也贴一下，我们尝试复现一下看看问题在哪
> > 
> > 
> > 我发现是因为推理返回内容是空导致的，模型合并后有概率会返回为空的推理，同样的问题重复提交几次才会正确响应
> 
> 可能是prompt不同导致的。建议还是用xtuner chat来对话：
> 
> ```
> xtuner chat $LLM --prompt-template default
> xtuner chat $LLM --adapter $ADAPTER --prompt-template default 
> ```
> 
> 同时也可以使用 `--bits 4` 或 `--bits 8` 来进一步降低显存开销！

应该不是显存的原因，显存占用不到一半，我是在v100的卡上跑的，32G显存才用了12G，还有20G的空闲显存

**Comment by LZHgrla** [comment]
> > > > > > > > 1. 使用的 tokenizer 有点问题，可以将合并得到的`tokenizer_config.json` 与 ChatGLM3 开源的 `tokenizer_config.json` 对比一下，是否多了 `eos_token` 这个参数？我们实测时一切是正常的，如果确实多了这个参数您可以将您所使用的命令贴一下，我们尝试复现一下问题。
> > > > > > > > 2. 除此之外，您也可以尝试直接使用原模型的tokenizer。
> > > > > > > 
> > > > > > > 
> > > > > > > 按照此方法模型可用了，但是出现一些新的小问题，跟模型对话时候经常抛异常，提示无法分割\n这样的，cli_demo和web_demo都会这样
> > > > > > 
> > > > > > 
> > > > > > 官方模型会有这个问题吗？
> > > > > 
> > > > > 
> > > > > 官方模型没有这个问题
> > > > 
> > > > 
> > > > 报错信息贴一下吧，命令也贴一下，我们尝试复现一下看看问题在哪
> > > 
> > > 
> > > 我发现是因为推理返回内容是空导致的，模型合并后有概率会返回为空的推理，同样的问题重复提交几次才会正确响应
> > 
> > 
> > 可能是prompt不同导致的。建议还是用xtuner chat来对话：
> > ```
> > xtuner chat $LLM --prompt-template default
> > xtuner chat $LLM --adapter $ADAPTER --prompt-template default 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 同时也可以使用 `--bits 4` 或 `--bits 8` 来进一步降低显存开销！
> 
> 应该不是显存的原因，显存占用不到一半，我是在v100的卡上跑的，32G显存才用了12G，还有20G的空闲显存
