### ISSUE TITLE
llama2中文版微调失败

### ISSUE THREAD

**Issue by ismsgithub** [InternLM/xtuner#202]
报错是`NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.`.复制的llama2-alpaca-chat python文件，修改了模型地址，指定了自己的json数据路径。显示模型导入成功，然后在运行的时候会复制到家目录下.cache里面，`Dataset json downloaded and prepared to file: ~/.cache`然后就不行了。

**Comment by LZHgrla** [comment]
fsspec版本问题，请尝试
```
pip install fsspec==2023.6.0
```
