### ISSUE TITLE
能否提供验证和测试的配置样例，目前的配置中只有训练的配置

### ISSUE THREAD

**Issue by rcejzibjks38** [InternLM/xtuner#206]

**Comment by LZHgrla** [comment]
目前没有比较好的、统一的微调评测指标，因此xtuner内也没有内嵌通用的评价指标。现阶段只能通过EvaluateChatHook监测训练中的对话效果

**Comment by LZHgrla** [comment]
如果想要自己实现评价指标，这有一个使用MMLU评测的例子，可以参考
https://github.com/InternLM/xtuner/pull/208
