### ISSUE TITLE
请问目前支持多轮对话，多次使用action，实现思维链么？

### ISSUE THREAD

**Issue by xiaohangguo** [InternLM/xtuner#207]
https://github.com/InternLM/lagent/issues/71

**Comment by LZHgrla** [comment]
Lagent中的ReAct应该是支持多轮action的，具体的请在Lagent仓库提问
https://github.com/InternLM/lagent/blob/50641c27c237b59e5b14edaf8b76d56e4c254b0e/lagent/agents/react.py#L218
