### ISSUE TITLE
[feature] why are all the default dtypes float16?

### ISSUE THREAD

**Issue by amulil** [InternLM/xtuner#209]
In my opinion, bfloat16 is a better default value.

**Comment by LZHgrla** [comment]
To be as compatible as possible with all GPUs, we use `float16` in provided configs.
If you want to use `bflaot16`, one convenient way is to utilize `deepspeed`, `--deepspeed deepspeed_zero2`, and the dtype will be automatically chosen from `bfloat16` and `float16`.

https://github.com/InternLM/xtuner/blob/0badead00dd43b5e25d1ea6edb0a52bd2626c856/xtuner/configs/deepspeed/deepspeed_zero2.json#L11-L18

**Comment by amulil** [comment]
> To be as compatible as possible with all GPUs, we use `float16` in provided configs. If you want to use `bflaot16`, one convenient way is to utilize `deepspeed`, `--deepspeed deepspeed_zero2`, and the dtype will be automatically chosen from `bfloat16` and `float16`.
> 
> https://github.com/InternLM/xtuner/blob/0badead00dd43b5e25d1ea6edb0a52bd2626c856/xtuner/configs/deepspeed/deepspeed_zero2.json#L11-L18

https://github.com/InternLM/xtuner/issues/120#issuecomment-1717598724  Is this bug fixed when I use deepspeed?

**Comment by LZHgrla** [comment]
> > To be as compatible as possible with all GPUs, we use `float16` in provided configs. If you want to use `bflaot16`, one convenient way is to utilize `deepspeed`, `--deepspeed deepspeed_zero2`, and the dtype will be automatically chosen from `bfloat16` and `float16`.
> > https://github.com/InternLM/xtuner/blob/0badead00dd43b5e25d1ea6edb0a52bd2626c856/xtuner/configs/deepspeed/deepspeed_zero2.json#L11-L18
> 
> [#120 (comment)](https://github.com/InternLM/xtuner/issues/120#issuecomment-1717598724) Is this bug fixed when I use deepspeed?

Sorry for that and this issue has not been resolved yet due to manpower reasons. I have reopened this issue and am trying to solve it.

**Comment by amulil** [comment]
> > > To be as compatible as possible with all GPUs, we use `float16` in provided configs. If you want to use `bflaot16`, one convenient way is to utilize `deepspeed`, `--deepspeed deepspeed_zero2`, and the dtype will be automatically chosen from `bfloat16` and `float16`.
> > > https://github.com/InternLM/xtuner/blob/0badead00dd43b5e25d1ea6edb0a52bd2626c856/xtuner/configs/deepspeed/deepspeed_zero2.json#L11-L18
> > 
> > 
> > [#120 (comment)](https://github.com/InternLM/xtuner/issues/120#issuecomment-1717598724) Is this bug fixed when I use deepspeed?
> 
> This issue has not been resolved yet due to manpower reasons. So sorry for that, and I have reopened this issue and am trying to solve it.

If I don't use deepspeed, only change the dtype in the conf file, such as `yi_6b_qlora_alpaca_enzh_oasst1_medical_e3_sync_params_gpu8_4k`, does it mean traing by dtype of bfloat16

**Comment by LZHgrla** [comment]
Without deepspeed:

1. If using QLoRA, LLM's weights are in int4/int8, and the LoRA's weights are in float32 with AmpOptimizer. So it won't work

    https://github.com/huggingface/peft/blob/ed4ce9fc94662a4825ef869c98e6de8c16d8ef28/src/peft/utils/other.py#L93-L97

2. If not using QLoRA, the whole model is in float32 with AmpOptimizer.

**Comment by amulil** [comment]
> @amulil Without deepspeed:
> 
> 1. If using QLoRA, LLM's weights are in int4/int8, and the LoRA's weights are in float32 with AmpOptimizer. So it won't work
>    https://github.com/huggingface/peft/blob/ed4ce9fc94662a4825ef869c98e6de8c16d8ef28/src/peft/utils/other.py#L93-L97
> 2. If not using QLoRA, the whole model is in float32 with AmpOptimizer.

@LZHgrla Thanks, I see it.
