### ISSUE TITLE
怎么同时调用服务器的4个gpu训练?

### ISSUE THREAD

**Issue by rcejzibjks38** [InternLM/xtuner#214]

**Comment by LZHgrla** [comment]
@rcejzibjks38 
增加 `NPROC_PER_NODE` 环境变量
```
NPROC_PER_NODE=4 xtuner train internlm_7b_qlora_oasst1_e3
```

**Comment by rcejzibjks38** [comment]
> @rcejzibjks38 增加 `NPROC_PER_NODE` 环境变量
> 
> ```
> NPROC_PER_NODE=4 xtuner train internlm_7b_qlora_oasst1_e3
> ```

能否指定使用某号GPU呢
