### ISSUE TITLE
如何从本地磁盘加载数据集？

### ISSUE THREAD

**Issue by liudonglei** [InternLM/xtuner#241]
通过datasets下载的数据集，存放在本地磁盘。
如何从本地磁盘加载数据集？修改config.py里load_dataset为load_from_disk后 报错

**Comment by zszzszzszz** [comment]
https://github.com/InternLM/xtuner/blob/main/docs/en/user_guides/single_turn_conversation.md

**Comment by liudonglei** [comment]
尝试成功了，
在config.py开头 from datasets import load_from_disk 
将 dataset=dict(type=load_dataset, path=data_path) 改为 ：
     dataset=dict(type=load_from_disk, dataset_path=data_path)
就可以load从huggingface官网下载后save到本地磁盘的数据集

**Comment by LZHgrla** [comment]
Closing this issue, feel free to reopen if you have more questions.
