### ISSUE TITLE
PagedAdamW32bit,优化器报错

### ISSUE THREAD

**Issue by kaoyansoft123** [InternLM/xtuner#247]
环境：
cuda11.8
bitsandbytes==0.41.2.post2
torch==2.0.1
transformers==4.34.0
transformers_stream_generator
错误如下：
Error operation not supported at line 380 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/pythonInterface.c
/arrow/cpp/src/arrow/filesystem/s3fs.cc:2904:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit

**Comment by xiaohangguo** [comment]
我也遇到过这个问题，换`AdamW`吧
`from torch.optim import AdamW`
`optim_type = AdamW`

**Comment by kaoyansoft123** [comment]
@xiaohangguo 这个是能用，我目前也是用的这个，既然config文件已提供了，但分页优化器不能用，实在是不应该！

**Comment by xiaohangguo** [comment]
> @xiaohangguo 这个是能用，我目前也是用的这个，既然config文件已提供了，但分页优化器不能用，实在是不应该！

bitsandbytes 确实有时候有问题

**Comment by LZHgrla** [comment]
由于 bitsandbytes 的 optimizer 在使用、resume 时在部分环境会出问题，目前默认优化器均替换为了`torch.optim.AdamW`～
https://github.com/InternLM/xtuner/pull/318
