### ISSUE TITLE
关于P-tuning和全参数tuning

### ISSUE THREAD

**Issue by creegon** [InternLM/xtuner#248]
关于全参数，请问有什么案例代码可以参考的吗？还是说直接把configs代码（类似https://github.com/InternLM/xtuner/discussions/153这样的）中的lora部分删掉即可？

关于p-tuning，xtuner似乎不支持。。？但如果我想用xtuner框架来实现的话，可能需要更改哪些底层代码呢？

感激不尽！！

**Comment by LZHgrla** [comment]
全量参数直接修改 config 即可，可以参考 https://github.com/InternLM/xtuner/blob/main/xtuner/configs/internlm/internlm_7b/internlm_7b_full_oasst1_e3.py


p-tuning 目前并不支持。因为我并没有系统看过 p-tuning 的源码实现，不是很好给出建议。如果有兴趣实现的话，可以尝试修改 `xtuner/model/sft.py` 并结合 peft 库的
