### ISSUE TITLE
xtuner 多机多卡训练时，数据不能同步，之后进程就被杀掉了

### ISSUE THREAD

**Issue by kaoyansoft123** [InternLM/xtuner#251]
deepspeed --hostfile hostfile --include="10.10.253.1:0@10.10.253.2:0" --master_port=11000 xtuner/tools/train.py   chatglm3_6b_32k_qlora.py  --launcher pytorch --deepspeed  xtuner/configs/deepspeed/deepspeed_zero2.json
主节点下（10.10.253.1）：arrow文件是有的。
分节点下（10.10.253.2）：报错如下：
FileNotFoundError: [Errno 2] Failed to open local file '/home/sysadm/.cache/huggingface/datasets/json/finetune-3d2c7fccd95317e1/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-66a5cd42fef01eaa_00000_of_00032.arrow'. Detail: [errno 2] No such file or directory
NCCL INFO [Service thread] Connection closed by localRank 0
NCCL INFO comm 0x24a37dd0 rank 1 nranks 2 cudaDev 0 busId 2010 - Abort COMPLETE
[launch.py:315:sigkill_handler] Killing subprocess 40970
[ERROR] [launch.py:321:sigkill_handler] exits with return code = 1

**Comment by pppppM** [comment]
这个可能是和集群的配置有关，两个机器的存储似乎是不共享的，可以尝试把数据放在两个节点都能访问的路径

**Comment by kaoyansoft123** [comment]
@pppppM 我通过mount的方式把数据挂载到了同一卷下，但是还是报这个错误，通过process_hf_dataset 进程，默认下载到了本地节点，/home/sysadm/.cache/huggingface/，process_hf_dataset 是否支持修改路径呢，还是说不能用mount的方式共享数据呢

**Comment by LZHgrla** [comment]
@kaoyansoft123 
可以通过设置环境变量的方式更改默认的 cache 路径，并请确保此时 cache 路径在计算节点能够访问到
```bash
export TRANSFORMERS_CACHE=/mnt/xxx/cache/huggingface/hub/
export HUGGINGFACE_HUB_CACHE=/mnt/xxx/cache/huggingface/hub/
export HF_HUB_CACHE=/mnt/xxx/cache/huggingface/hub/

export HF_DATASETS_CACHE=/mnt/xxx/cache/huggingface/datasets/
```

**Comment by zhudongwork** [comment]
> @kaoyansoft123 可以通过设置环境变量的方式更改默认的 cache 路径，并请确保此时 cache 路径在计算节点能够访问到
> 
> ```shell
> export TRANSFORMERS_CACHE=/xxx/cache/huggingface/hub/
> export HUGGINGFACE_HUB_CACHE=/xxx/cache/huggingface/hub/
> export HF_HUB_CACHE=/xxx/cache/huggingface/hub/
> 
> export HF_DATASETS_CACHE=/xxx/cache/huggingface/datasets/
> ```

这样设置后还是出现了一样的问题

**Comment by sph116** [comment]
@zhudongwork 您好 我也遇到相同问题 请问你解决了吗
