### ISSUE TITLE
bitsandbytes可以改成>=0.39.0吗？

### ISSUE THREAD

**Issue by zoe-yyx** [InternLM/xtuner#256]
安装bitsandbytes0.41.1的版本报错
AttributeError: module 'bitsandbytes' has no attribute 'nn'，
其他版本0.41.0/0.41.2有类似的报错，
能否在xtuner这边吧版本需求降低到0.39.0 ? 如果可以在哪里调整

**Comment by LZHgrla** [comment]
关于 `bitsandbytes` 的依赖版本，后续在 https://github.com/InternLM/xtuner/pull/277 中将更新为 `bitsandbytes>=0.40.0.post4`
1. 0.40.0 实现更快速的 4bit kernel https://github.com/TimDettmers/bitsandbytes/releases/tag/0.40.0
2. 0.40.0.post4 修复了一个精度 bug https://github.com/TimDettmers/bitsandbytes/commit/90b0ac57b0d8d8f996126deb8bba6b7dc75b4327
