### ISSUE TITLE
请问支持qwen1.8B的微调吗？

### ISSUE THREAD

**Issue by sanbuphy** [InternLM/xtuner#261]
为数不多的小模型，应该能推广到所有人

**Comment by LZHgrla** [comment]
支持的！
https://github.com/InternLM/xtuner/tree/main/xtuner/configs/qwen/qwen_1_8b
https://github.com/InternLM/xtuner/pull/252

**Comment by sanbuphy** [comment]
> 支持的！ https://github.com/InternLM/xtuner/tree/main/xtuner/configs/qwen/qwen_1_8b #252

Thanks
