### ISSUE TITLE
为

### ISSUE THREAD

**Issue by JasonFuuuuuuuu** [InternLM/xtuner#267]
![20231214-162756](https://github.com/InternLM/xtuner/assets/125422548/488d60f7-a883-4b87-af21-991ab40d7839)
pretrained_model_name_or_path = 'DiscoResearch/mixtral-7b-8expert11'
我把pretrained_model_name_or_path的名字改了个错的，然后运行xtuner train mixtral_8x7b_qlora_oasst1_internlm_template_e3 --deepspeed deepspeed_zero2, log里竟然还是原来的那个模型，如何更换模型路径，和data path路径，代码好奇怪啊

**Comment by JasonFuuuuuuuu** [comment]
> 可以查看下 work_dir 里的 log，里面有训练时的 config 详情，看下是否改动生效了

请问到底是怎么让它生效呢？不是改代码里的路径吗？

**Comment by JasonFuuuuuuuu** [comment]
> 可以查看下 work_dir 里的 log，里面有训练时的 config 详情，看下是否改动生效了

相当于我截图中的那些变量完全不起作用，模型路径都改不了

**Comment by JasonFuuuuuuuu** [comment]
应该是代码有一些bug， 期待您的回答

**Comment by LZHgrla** [comment]
@JasonFuuuuuuuu 
查看一下 xtuner 是否是从源码安装的，且该路径是你修改的config所在的xtuner路径
```
pip list |grep xtuner
```

正常情况应该是
```
xtuner                        0.1.10        /xxxx/xxxxxx
```

**Comment by JasonFuuuuuuuu** [comment]
> @JasonFuuuuuuuu 查看一下 xtuner 是否是从源码安装的，且该路径是你修改的config所在的xtuner路径
> 
> ```
> pip list |grep xtuner
> ```
> 
> 正常情况应该是
> 
> ```
> xtuner                        0.1.10        /xxxx/xxxxxx
> ```

OK,那请问config里为什么没有模型保存路径呢，在哪里修改ckp保存路径

**Comment by LZHgrla** [comment]
之前的问题是解决了吗？ 什么问题导致的。

模型保存的话，默认在./work_dirs

**Comment by JasonFuuuuuuuu** [comment]
> 之前的问题是解决了吗？ 什么问题导致的。
> 
> 模型保存的话，默认在./work_dirs

是的，默认的我知道。好像没法改哈

**Comment by JasonFuuuuuuuu** [comment]
> 之前的问题是解决了吗？ 什么问题导致的。
> 
> 模型保存的话，默认在./work_dirs

解决了谢谢

**Comment by LZHgrla** [comment]
> > 之前的问题是解决了吗？ 什么问题导致的。
> 
> > 
> 
> > 模型保存的话，默认在./work_dirs
> 
> 
> 
> 是的，默认的我知道。好像没法改哈

xtuner train $CONFiG --work-dir ANY_PATH

**Comment by XDeepAzure** [comment]
> @JasonFuuuuuuuu 查看一下 xtuner 是否是从源码安装的，且该路径是你修改的config所在的xtuner路径
> 
> ```
> pip list |grep xtuner
> ```
> 
> 正常情况应该是
> 
> ```
> xtuner                        0.1.10        /xxxx/xxxxxx
> ```

这意思是每次改完config都要重新pip一下是吗？

**Comment by LZHgrla** [comment]
@XDeepAzure 不用，只是为了排除下非源码安装的情况。如果非源码安装，config肯定是默认去找发版包里的

**Comment by XDeepAzure** [comment]
> @XDeepAzure 不用，只是为了排除下非源码安装的情况。如果非源码安装，config肯定是默认去找发版包里的

哦哦明白了，谢谢

**Comment by JasonFuuuuuuuu** [comment]
> @XDeepAzure 不用，只是为了排除下非源码安装的情况。如果非源码安装，config肯定是默认去找发版包里的

您这个数据只能是hugging face上的数据集吗？自己路径为什么一直找不到数据呢，很奇怪，没法用自己的数据训练啊

**Comment by LZHgrla** [comment]
@JasonFuuuuuuuu 

https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/single_turn_conversation.md#使用自定义数据集
