### ISSUE TITLE
chat 时添加 --lagent 出现  got multiple values for keyword argument "trust renote code

### ISSUE THREAD

**Issue by ooooo-create** [InternLM/xtuner#268]
运行 `xtuner chat ./internlm-chat-7b --adapter internlm-7b-qlora-msagent-react --lagent`
![5a9b0358d9dd2dd8bd8d047e78aaa9d](https://github.com/InternLM/xtuner/assets/106524776/6fac239d-fd12-4a86-bee8-5bf972f4839b)
出现
![00004acff03e0a8ce250c84bba00764](https://github.com/InternLM/xtuner/assets/106524776/fdb63319-0069-4fec-8c97-89bcf72428b9)
发现是lagent.llms.HFTransformerCasualLM
![5f059641230a5cd5f196aedd2a04127](https://github.com/InternLM/xtuner/assets/106524776/0d43a543-9d54-4839-b8fd-840acfd7f861)
然后把chat.py文件注释了一下,就没问题了
![f5e8e9dd33518e51189dc1b39f5e668](https://github.com/InternLM/xtuner/assets/106524776/9608cfe2-a8af-4ee1-9fd2-b76be2aa28e5)

是不是要修改一下 model_kwargs ，在--lagent不传入 `trust renote code`.
I am willing to do this ~

**Comment by LZHgrla** [comment]
#269 感谢！相关PR已被merge～
