### ISSUE TITLE
不管使用单卡还是多卡训练都会报错blockingioerror:resource temporarily unavailable，请问这咋回事

### ISSUE THREAD

**Issue by Kaiwen6** [InternLM/xtuner#276]
![屏幕截图 2023-12-22 174336](https://github.com/InternLM/xtuner/assets/71768682/454e5298-bc60-4d77-a923-1b46a40e1ad2)

**Comment by LZHgrla** [comment]
@Kaiwen6 
看起来像处理数据的时候被kill了，请尝试给dataset增加`map_num_proc=1`这个参数
```diff
train_dataset = dict(
    type=process_hf_dataset,
    xxxxxxx
+   map_num_proc=1)
```

**Comment by Kaiwen6** [comment]
找到原因了，我把internlm20模型里面py文件更新成internlm20chat模型里的了
