### ISSUE TITLE
逆天！！！

### ISSUE THREAD

**Issue by Kaiwen6** [InternLM/xtuner#279]
![image](https://github.com/InternLM/xtuner/assets/71768682/427e0771-e06b-4a3c-878e-da2a60b63fbb)
强调！！！我用的数据集很纯，没有杂质！！！

**Comment by LZHgrla** [comment]
请贴一下完整的chat命令

**Comment by HIT-cwh** [comment]
我有点怀疑你提前敲了回车，导致模型根据一个空输入在生成

**Comment by Kaiwen6** [comment]
![image](https://github.com/InternLM/xtuner/assets/71768682/57990dd5-db01-448c-92ec-b9fa9e2355e6)
用的下面的chat命令，没有加其他参数，执行命令，加载模型完毕后，直接生成上面图片中的内容

> 请贴一下完整的chat命令

**Comment by LZHgrla** [comment]
@Kaiwen6 
https://github.com/InternLM/xtuner#chat-

看起来没有加--prompt-template？

**Comment by Kaiwen6** [comment]
> 我有点怀疑你提前敲了回车，导致模型根据一个空输入在生成

我没有打字，可能确实敲了回车，重启后，恢复正常了

**Comment by Kaiwen6** [comment]
> @Kaiwen6 https://github.com/InternLM/xtuner#chat-
> 
> 看起来没有加--prompt-template？

没有

**Comment by LZHgrla** [comment]
得加 --prompt-template的
`--prompt-template internlm_chat`

**Comment by Kaiwen6** [comment]
> 得加 --prompt-template的 `--prompt-template internlm_chat`

了解，添加prompt后能正常对话了，感谢解答
