### ISSUE TITLE
微调internLM 7B后，Chat输出异常

### ISSUE THREAD

**Issue by canglangzhishuiz** [InternLM/xtuner#284]
<img width="1109" alt="屏幕截图 2023-12-28 102546" src="https://github.com/InternLM/xtuner/assets/64078820/37e112de-e540-412f-be99-f74e99c211cc">

**Comment by LZHgrla** [comment]
请贴一下 xtuner chat的完整命令

同时，请检查一下训练log，在训练过程中的对话评测是否正常

**Comment by canglangzhishuiz** [comment]
xtuner chat命令：
xtuner chat internlm/7b --adapter ./internlm/finetune_1228 --prompt-template internlm_chat --system-template alpaca

训练log中，对话时正常的，这是最后一个epoch的输出：
![Uploading 屏幕截图 2023-12-28 103508.png…]()

**Comment by canglangzhishuiz** [comment]
xtuner chat命令：
xtuner chat internlm/7b --adapter ./internlm/finetune_1228 --prompt-template internlm_chat --system-template alpaca

训练log中，对话是正常的，这是最后一个epoch的输出：
<img width="1118" alt="屏幕截图 2023-12-28 103508" src="https://github.com/InternLM/xtuner/assets/64078820/eb97d563-2054-4190-86ad-4eb03d15c1fd">

**Comment by canglangzhishuiz** [comment]
出现了这种很奇怪的重复回复的情况，问题是我随便问的，可能是数据集中没有这方面的知识
<img width="745" alt="屏幕截图 2023-12-28 104631" src="https://github.com/InternLM/xtuner/assets/64078820/8064240b-9c33-479e-9cab-accfdd76058a">

**Comment by LZHgrla** [comment]
> 出现了这种很奇怪的重复回复的情况，问题是我随便问的，可能是数据集中没有这方面的知识
> 
> <img width="745" alt="屏幕截图 2023-12-28 104631" src="https://github.com/InternLM/xtuner/assets/64078820/8064240b-9c33-479e-9cab-accfdd76058a">
> 
> 

命令是没问题的，所以应该是数据的问题。还有一个可以尝试的地方是使用chat模型（internlm-chat-7b） 进行微调，而非base模型（internlm-7b）

**Comment by canglangzhishuiz** [comment]
> > 出现了这种很奇怪的重复回复的情况，问题是我随便问的，可能是数据集中没有这方面的知识
> > <img alt="屏幕截图 2023-12-28 104631" width="745" src="https://private-user-images.githubusercontent.com/64078820/293127533-8064240b-9c33-479e-9cab-accfdd76058a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTkxMjEsIm5iZiI6MTcwMzgxODgyMSwicGF0aCI6Ii82NDA3ODgyMC8yOTMxMjc1MzMtODA2NDI0MGItOWMzMy00NzllLTljYWItYWNjZmRkNzYwNThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAzMDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZTc4NzEzNTgyYTMwYTkzNDM5OWVlZTk4ODZmOTBiMDkwZGYyNWNmNzJkYjYzMzAwZTExNGQ3MWEwZDc5YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KrfrJI5IZrsF_v4gAjprF_yyER9MLcJ9xPJ615J7Cwc">
> 
> 命令是没问题的，所以应该是数据的问题。还有一个可以尝试的地方是使用chat模型（internlm-chat-7b） 进行微调，而非base模型（internlm-7b）

好的，那我准备一个自己的数据集，再尝试一下。
