### ISSUE TITLE
TypeError: EvaluateChatHook.__init__() got an unexpected keyword argument 'instruction'

### ISSUE THREAD

**Issue by xichie** [InternLM/xtuner#288]
Alpaca微调llama2-7b,出现这个错误。数据格式是这样的
`[
"conversation": [
            {
                "input": "”
                "output": ""
            }
        ]
]`

**Comment by LZHgrla** [comment]
应该跟数据没有关系，是在config内给EvaluateChatHook传递的参数有问题，请张贴一下config中 EvaluateChatHook 的相关部分

**Comment by LZHgrla** [comment]
正确的参数格式应该类似这个样子

https://github.com/InternLM/xtuner/blob/5962cc87d2893870f5ccdd112a3adfe3883fb14d/xtuner/configs/llama/llama2_7b/llama2_7b_qlora_oasst1_e3.py#L147-L153

**Comment by xichie** [comment]
按照这个解决了。 我这个格式的数据，dataset_map_fn应该设置成None ，建议文档里说明一下。:)

https://github.com/InternLM/xtuner/issues/270#issuecomment-1862580932

``
alpaca_en = dict(
    type=process_hf_dataset,
    # dataset=dict(type=load_dataset, path=alpaca_en_path),
    dataset=dict(type=load_dataset, path='json', data_files=dict(train=alpaca_en_path)),
    tokenizer=tokenizer,
    max_length=max_length,
    dataset_map_fn=None,
....
