### ISSUE TITLE
Runtime Error: attn_mask.dtype: float and  query.dtype: c10::Half

### ISSUE THREAD

**Issue by StarCycle** [InternLM/xtuner#289]
I use xtuner to pretrain LLava-internlm-7b. I prepared the pretain data according to this [link](https://github.com/InternLM/xtuner/tree/main/docs/zh_cn/user_guides/dataset_prepare.md#llava-dataset), and used the config file llava_internlm_chat_7b_clip_vit_large_p14_336_e1_gpu8_pretrain_copy.py. I got the config file by "xtuner copy-cfg" and I only modified the batch size from 32 to 1.

And then I got the following error:
`File "/opt/conda/lib/python3.10/site-packages/xtuner/model/modules/dispatch/in
ternlm.py", line 66, in internlm_attn_forward
    attn_output = F.scaled_dot_product_attention(
RuntimeError: Expected attn_mask dtype to be bool or to match query dtype, but g
ot attn_mask.dtype: float and  query.dtype: c10::Half instead.`

I checked line 66 in internlm.py, and found `query_states`, `key_states` , and `value_states` are all torch.float16. 

I am using an instance from Vast.ai with single 4090 GPU.

Could you please check this error and tell me how to fix it?

**Comment by LZHgrla** [comment]
Please post the full command you used. I think you are not using deepspeed?

If that is, please try to use `xtuner train $CFG --deepspeed deepspeed_zero2`

**Comment by StarCycle** [comment]
Thanks! It does work now
