### ISSUE TITLE
如何自定义初始化LoRA参数

### ISSUE THREAD

**Issue by xichie** [InternLM/xtuner#291]
比如我有一个训练过的LoRA模块，如何将它重新加载，继续训练？

**Comment by LZHgrla** [comment]
现在的代码暂不支持这一功能，您可以考虑如下方案进行解决

1. 先将 LoRA merge 到 LLM 中，后直接使用这个 LLM 进行新的 LoRA 微调
2. 将 LoRA 作为预训练权重，传递给初始化好的 LLM + LoRA 模型。此时需要修改一定量的代码，在 `SupervisedFinetune` 类的 self._init = True 前利用 torch 的 load 等方法将 LoRA 的 bin 模型载入进来

**Comment by xichie** [comment]
请问这么操作，是不是可以将训练过的LoRA参数加载进来
`lora=dict(
        type=LoraConfig,
        r=64,
        lora_alpha=16,
        lora_dropout=0.1,
        bias='none',
        task_type='CAUSAL_LM'),
    peft_model='LoRA_PATH'  # 加载训练好的LoRA `

运行的Log，应该是把LoRA参数加载了，base model参数没变
![1704167450731](https://github.com/InternLM/xtuner/assets/30527824/7653f433-483f-45b6-8a84-f1ff7b902272)

**Comment by LZHgrla** [comment]
'LoRA_PATH' 如果是 xtuner 训出来的 pth 权重，是可以的。
但是如果是huggingface的 bin权重，因为有可能key-value对不齐，所以是不行的。

**Comment by xichie** [comment]
感谢，就是xtuner训出来的。:>
