### ISSUE TITLE
warning: Import flash-att failed.

### ISSUE THREAD

**Issue by shengyuwoo** [InternLM/xtuner#295]
训练或者做推理的时候，总是 Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm，通过重装、打补丁等方式安装之后，却出现了其他的报错，只有卸载flashAttention，不使用flashAttention才能进行正常训练和推理。 请问这主要是什么问题呢？在哪些方面入手排查呢？  我的卡是NVIDIA-A800，CUDA11.7，pytorch是2.0.1版本，transformers是4.32.0版本。

**Comment by LZHgrla** [comment]
应该是在训练qwen模型？
qwen模型会在未安装flash-attn时报warning，但不影响微调、推理等功能

如果需要解决这一warning，得正确安装flash-attn
https://github.com/Dao-AILab/flash-attention#installation-and-features
