### ISSUE TITLE
使用原始的chatglm3_6b_qlora_lawyer_e3配置微调时，报错TypeError: 'list' object is not callable

### ISSUE THREAD

**Issue by rcejzibjks38** [InternLM/xtuner#296]
复制了chatglm3_6b_qlora_lawyer_e3配置后微调：
```bash
CUDA_VISIBLE_DEVICES=3 xtuner train configs/chatglm3_6b_qlora_lawyer_e3_copy.py
```
报错TypeError: 'list' object is not callable
![image](https://github.com/InternLM/xtuner/assets/138190647/92fb08ee-5655-4563-b306-46865899fb93)

**Comment by LZHgrla** [comment]
确实是一个bug，我正在尝试修复

**Comment by LZHgrla** [comment]
https://github.com/InternLM/xtuner/pull/298 will solve this issue
