### ISSUE TITLE
无法复现llava

### ISSUE THREAD

**Issue by KooSung** [InternLM/xtuner#308]
按照llava/internlm_chat_7b_clip_vit_large_p14_336的pretrain、finetune的config自己训练，发现效果很差。
pretrain的loss看上去没问题
![image](https://github.com/InternLM/xtuner/assets/34935911/a2a901a4-28b0-4c18-9d3c-a9f48a71f965)

但是finetune的loss有问题
![image](https://github.com/InternLM/xtuner/assets/34935911/99a097db-1776-481f-a113-c0ce6b8e525d)

MMBench DEV EN的分数为0
![image](https://github.com/InternLM/xtuner/assets/34935911/44fa5edf-1793-4e62-8a7d-515d8db73c5f)

此外在评测MMBench DEV EN时发现自己训练的模型需要1个多小时, qps为1左右，但是官方的[xtuner/llava-internlm-7b](https://huggingface.co/xtuner/llava-internlm-7b)只需要16分钟， qps大概为4.5。

使用mistral替换internlm也是一样的问题。

**Comment by LZHgrla** [comment]
请张贴一下所有相关的命令

**Comment by KooSung** [comment]
> 请张贴一下所有相关的命令

pretrain
```bash
NPROC_PER_NODE=8 xtuner train llava_internlm_chat_7b_clip_vit_large_p14_336_e1_gpu8_pretrain --deepspeed deepspeed_zero2
```

finetune 
```bash
NPROC_PER_NODE=8 xtuner train llava_internlm_chat_7b_qlora_clip_vit_large_p14_336_lora_e1_gpu8_finetune --deepspeed deepspeed_zero2
```

训练结束后进行转换
```bash
FINETUNE_CFG="llava_internlm_chat_7b_qlora_clip_vit_large_p14_336_lora_e1_gpu8_finetune"
PTH_PATH="./work_dirs/llava_internlm_chat_7b_qlora_clip_vit_large_p14_336_lora_e1_gpu8_finetune/epoch_1.pth"
SAVE_PATH="./work_dirs/llava_internlm_chat_7b_qlora_clip_vit_large_p14_336_lora_e1_gpu8_finetune/epoch_1_hf"

xtuner convert pth_to_hf $FINETUNE_CFG $PTH_PATH $SAVE_PATH
```

eval
```bash
xtuner mmbench internlm-chat-7b路径 \
  --visual-encoder openai/clip-vit-large-patch14-336 \
  --llava ./work_dirs/llava_internlm_chat_7b_qlora_clip_vit_large_p14_336_lora_e1_gpu8_finetune/epoch_1_hf \
  --prompt-template internlm_chat \
  --data-path $DATA_PATH \
  --work-dir $RESULT_PATH
```

**Comment by KooSung** [comment]
补充一下一些依赖包的版本
```
transformers==4.33.2
torch==2.0.1
deepspeed==0.12.6
mmengine==0.10.2
```

**Comment by LZHgrla** [comment]
命令看起来没问题，有一些检查项可以试一下

1. 确保官方开源的 llava-internlm-7b 精度可复现
2. finetune config 中的 pretrained_pth 已填写并正确载入
3. 多次运行finetune，查看loss是否仍异常。我这边finetune的loss如下图

<img width="1442" alt="image" src="https://github.com/InternLM/xtuner/assets/36994684/b493b9b0-9aa5-4576-857c-dba6f4b0ad8f">

**Comment by KooSung** [comment]
好的，我重新finetune一下。请问一下推理比官方的慢很多是什么原因？

**Comment by LZHgrla** [comment]
这个有点摸不清，正常来说上述步骤和产出官方模型的步骤是完全一致的。

可以检查一下lora adapter的config.json是否与官方模型参数一致

**Comment by pppppM** [comment]
> 好的，我重新finetune一下。请问一下推理比官方的慢很多是什么原因？

@KooSung 可以检查下 mmbench 输出的 excel 文件里，prediction 是不是很长的乱码；可能是模型训崩了，不会结束，一直生成到 max tokens

**Comment by KooSung** [comment]
> > 好的，我重新finetune一下。请问一下推理比官方的慢很多是什么原因？
> 
> @KooSung 可以检查下 mmbench 输出的 excel 文件里，prediction 是不是很长的乱码；可能是模型训崩了，不会结束，一直生成到 max tokens

好的，感谢，我重新finetune下再看看有没有问题

**Comment by KooSung** [comment]
请问如何使用多机多卡进行训练？比如使用accelerate

**Comment by LZHgrla** [comment]
支持torchrun、slurm 执行 multi-node

torchrun + deepspeed_zero2
```
# excuete on node 0
NPROC_PER_NODE=8 NNODES=2 PORT=29600 ADDR=$NODE_0_ADDR NODE_RANK=0 xtuner train XXX --deepspeed deepspeed_zero2
# excuete on node 1
NPROC_PER_NODE=8 NNODES=2 PORT=29600 ADDR=$NODE_0_ADDR NODE_RANK=1 xtuner train XXX --deepspeed deepspeed_zero2
```

slurm + deepspeed_zero2
```
srun -p $PARTITION --job-name=llava--nodes=2 --gres=gpu:8 --ntasks-per-node=8 xtuner train XXX --deepspeed deepspeed_zero2 --launcher slurm
```
