### ISSUE TITLE
NPROC_PER_NODE=8 xtuner train多卡训练报错

### ISSUE THREAD

**Issue by ggfengxuan** [InternLM/xtuner#314]
NPROC_PER_NODE=8 xtuner train internlm_chat_7b_qlora_antibody_e3.py --deepspeed deepspeed_zero2
使用上述命令进行多卡训练会出现以下错误
torch.distributedtorch.distributed..DistBackendError: DistBackendErrorNCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'invalid argument':
NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'invalid argument'

**Comment by LZHgrla** [comment]
1. 可以尝试一下所提供的默认 config，比如`internlm_chat_7b_qlora_oasst1_e3`，查看是否出现类似错误。如果也会出现类似错误，则大概率是多卡通信有问题。
2. 可以尝试关闭 deepspeed，查看是否会有问题。
