### ISSUE TITLE
QLoRA  failed

### ISSUE THREAD

**Issue by zmingchun** [InternLM/xtuner#320]
ERROR:
ValueError: We need an `offload_dir` to dispatch this model according to this `device_map`, the following submodules need to be offloaded
![image](https://github.com/InternLM/xtuner/assets/1988270/93b43e4e-3ae4-42be-80e7-b2caa8ec3f0c)

Repeat path：https://mp.weixin.qq.com/s/pbNiOVJjptuI7wKdk7qXAA
```
# 加载 Adapter 模型对话
xtuner chat ./internlm-chat-7b --adapter ./hf --prompt-template internlm_chat

```

**Comment by zmingchun** [comment]
version : v0.1.9
env: dsw-registry-vpc.cn-shenzhen.cr.aliyuncs.com/pai-training-algorithm/llm_deepspeed:v0.2.1
![image](https://github.com/InternLM/xtuner/assets/1988270/48729862-ac9b-4fee-a160-c130a6f05cdc)

**Comment by LZHgrla** [comment]
It seems that the GPU is not enough for chatting.

Two options
1. Try to use 4bit, as `--bits 4`
2. Pass a `offload_dir `, as `--offload-folder ./temp`

**Comment by zmingchun** [comment]
Well, I‘ll try. It‘s this?
```
xtuner chat ./internlm-chat-7b --adapter ./hf --prompt-template internlm_chat --bits 4
xtuner chat ./internlm-chat-7b --adapter ./hf --prompt-template internlm_chat --offload-folder ./temp
```
