### ISSUE TITLE
xtuner chat速度非常慢

### ISSUE THREAD

**Issue by zhanghui-china** [InternLM/xtuner#331]
一个字一个字的吐出来。。
![image](https://github.com/InternLM/xtuner/assets/63148804/ac8cbf4e-6112-4282-9af2-eab8a18cc1b2)

**Comment by zhanghui-china** [comment]
有人说会不会没走GPU。。。但是gpu有占用。。。

**Comment by LZHgrla** [comment]
```
WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu.
```
显存不足，模型被offload到了内存上，所以速度会很慢
可以试试加`--bits 4` 量化后，应该可以缓解一下

**Comment by zhanghui-china** [comment]
加了--bit 4确实速度变快了。谢谢·
