### ISSUE TITLE
Merge adaptor to CLIP-L/14 error

### ISSUE THREAD

**Issue by yiyexy** [InternLM/xtuner#335]
Thanks for greate work!
You put the adaptor weight on the hugging face, and give the shell code to merge adaptor into LLM.
```
xtuner convert merge \
    ${NAME_OR_PATH_TO_LLM} \
    ${NAME_OR_PATH_TO_ADAPTER} \
    ${SAVE_PATH} \
    --max-shard-size 2GB
```
I used this code merge LLM model successful. But when I want to merge CLIP-L/14, I got the message as:

<img width="957" alt="image" src="https://github.com/InternLM/xtuner/assets/35927125/a671f5d1-a474-46e9-8cf1-1c4de27b77bf">

How can merge vision model?

**Comment by LZHgrla** [comment]
@yiyexy  HI!
Please specify `--is-clip` for your merge command
