### ISSUE TITLE
LLaVA Pretrain Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.

### ISSUE THREAD

**Issue by maxchiron** [InternLM/xtuner#350]
/envs/xtuner/lib/python3.10/site-packages/torch/cuda/__init__.py:611: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
[2024-01-23 08:58:33,898] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
01/23 08:58:34 - mmengine - WARNING - Use random port: 21723
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
        Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.

**Comment by maxchiron** [comment]
`export MKL_SERVICE_FORCE_INTEL=1`
`export MKL_THREADING_LAYER = GNU`

**Comment by StarCycle** [comment]
I had a similar problem. Perhaps you can uninstall numpy and reinstall it.

**Comment by StarCycle** [comment]
OK I have exactly the same problem in issue #354. Reinstalling numpy will also solve this problem

**Comment by StarCycle** [comment]
OK I have exactly the same problem in issue #354. Reinstalling numpy will also solve this problem
