### ISSUE TITLE
When finetuning llava-internlm2 (with dinov2), xtuner suddenly exits without error

### ISSUE THREAD

**Issue by StarCycle** [InternLM/xtuner#354]
I am fintuning llava-internlm2 (but replacing clip with dinov2, see #297). I finish the pretraining phase successfully. But during the finetuning phase, xtuner will suddenly quits without any error reported:

![image](https://github.com/InternLM/xtuner/assets/33491471/5eaacde4-63f0-4613-a690-28d4839a0f63)

I monitor the RAM used with the top command, and there isn't an OOM error. Since the dataloading is not finished, I guess it is not a problem of Dinov2. 

My command is 
```
xtuner train llava_internlm2_chat_7b_qlora_clip_vit_large_p14_336_lora_e1_gpu8_finetune_copy.py --deepspeed deepspeed_zero2
```

the modified [config file](https://github.com/InternLM/xtuner/files/14038381/llava_internlm2_chat_7b_qlora_clip_vit_large_p14_336_lora_e1_gpu8_finetune_copy.txt) and the [log](https://github.com/InternLM/xtuner/files/14038289/20240124_203031.log) is attatched.

**Comment by LZHgrla** [comment]
Hi! Please modify the map_num_proc to 1 and try again

https://github.com/InternLM/xtuner/blob/26d333f83bcd84122ffe68459dbbe292a80b5c03/xtuner/dataset/huggingface.py#L29

**Comment by StarCycle** [comment]
The problem is solved! But then it reports "no enough CUDA memory". I am using a 4090 and set batch size = 1. Is it normal?

**Comment by LZHgrla** [comment]
Yes. 24GB is not enough for fine-tuning. Because the length of fine-tuning's data are much longer than those for pre-training.

**Comment by StarCycle** [comment]
I switch to A6000 on vast.ai (A6000 has 48GB RAM). When I finetune with a single A6000, it's fine. But when I use 4 A6000 gpu, the program is stuck here:

![2ab9eff7f0103b2f7c92f80cff383d1](https://github.com/InternLM/xtuner/assets/33491471/6e1d3e9c-5322-4e99-a22c-26b21642e59d)

All GPU are utilized but the GPU memory is not much allocated:

![ed510c494d6c5cfd2fb778562abe071](https://github.com/InternLM/xtuner/assets/33491471/e9a757a0-dafc-4728-aa9b-aabaa9e6cefc)

The command is still
`xtuner train llava_internlm2_chat_7b_qlora_clip_vit_large_p14_336_lora_e1_gpu8_finetune_copy.py --deepspeed deepspeed_zero2`

The log is [20240128_073714.log](https://github.com/InternLM/xtuner/files/14075345/20240128_073714.log).

There was an error about multi-process communication:
```
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
```

When I `export MKL_SERVICE_FORCE_INTEL=1`, the error message does not show up again.

**Comment by StarCycle** [comment]
After half an hour I get:

```
[E ProcessGroupNCCL.cpp:828] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpT
ype=BROADCAST, Timeout(ms)=1800000) ran for 1806937 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpT
ype=BROADCAST, Timeout(ms)=1800000) ran for 1806980 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpT
ype=BROADCAST, Timeout(ms)=1800000) ran for 1807185 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature
 of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature
 of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature
 of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 12534 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 1 (pid: 12535) of binary: /opt/conda/bin/python
Traceback (most recent call last):                                                               [12/1967]
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.
py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_ag
ent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/opt/conda/lib/python3.10/site-packages/xtuner/tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-01-28_08:07:25
  host      : 08cdfabdfec3
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 12536)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 12536
[2]:
  time      : 2024-01-28_08:07:25
  host      : 08cdfabdfec3
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 12537)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 12537
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-28_08:07:25
  host      : 08cdfabdfec3
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 12535)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 12535
============================================================

```

**Comment by LZHgrla** [comment]
NPROC_PER_NODE=4 xtuner train XXX

Add NPROC_PER_NOD=4 to use multi-gpu DDP training.

**Comment by StarCycle** [comment]
I forgot to mention it...The full command is `NPROC_PER_NODE=4 xtuner train llava_internlm2_chat_7b_qlora_dinov2_large_p14_336_lora_e1_gpu8_finetune_copy.py --deepspeed deepspeed_zero2`

**Comment by StarCycle** [comment]
There will be the problem with `NPROC_PER_NODE=4`. If I simply use `xtuner train llava_internlm2_chat_7b_qlora_dinov2_large_p14_336_lora_e1_gpu8_finetune_copy.py --deepspeed deepspeed_zero2`, the program can successfully run with single A6000. @LZHgrla

**Comment by LZHgrla** [comment]
@StarCycle 
It seems that it is an error during the loading of model.

How many GPUs were used for pre-training? 1 or 4?

**Comment by StarCycle** [comment]
Thank you. The problem has been solved by switching to another docker image (even in the same machine)...Perhaps there are some problems with the docker image
