### ISSUE TITLE
app.py如何传递--repetition-penalty 1.002 参数

### ISSUE THREAD

**Issue by zhanghui-china** [InternLM/xtuner#355]
在 issue [https://github.com/InternLM/xtuner/issues/343](url) 中，
已经能够成功通过 xtuner chat ./merged --temperature 0.8 --top-p 0.8 --repetition-penalty 1.002 --prompt-template internlm2_chat 参数解决 循环输出的问题。

现在app.py中，如何将 repetition-penalty 放入调用的参数中。

目前代码如下：```

"""
This script refers to the dialogue example of streamlit, the interactive generation code of chatglm2 and transformers.
We mainly modified part of the code logic to adapt to the generation of our model.
Please refer to these links below for more information:
    1. streamlit chat example: https://docs.streamlit.io/knowledge-base/tutorials/build-conversational-apps
    2. chatglm2: https://github.com/THUDM/ChatGLM2-6B
    3. transformers: https://github.com/huggingface/transformers
"""

from dataclasses import asdict

from modelscope import AutoModelForCausalLM, AutoTokenizer
#from modelscope import GenerationConfig

import streamlit as st
import torch
import re  
#from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.utils import logging

from tools.transformers.interface import GenerationConfig, generate_interactive

logger = logging.get_logger(__name__)

def on_btn_click():
    del st.session_state.messages

@st.cache_resource
def load_model():
    model = (
        AutoModelForCausalLM.from_pretrained("zhanghuiATchina/zhangxiaobai_shishen", trust_remote_code=True)
        .to(torch.bfloat16)
        .cuda()
    )
    tokenizer = AutoTokenizer.from_pretrained("zhanghuiATchina/zhangxiaobai_shishen", trust_remote_code=True)
    return model, tokenizer

def prepare_generation_config():
    with st.sidebar:
        max_length = st.slider("Max Length", min_value=32, max_value=2048, value=2048)
        top_p = st.slider("Top P", 0.0, 1.0, 0.8, step=0.01)
        temperature = st.slider("Temperature", 0.0, 1.0, 0.7, step=0.01)
        st.button("Clear Chat History", on_click=on_btn_click)

    generation_config = GenerationConfig(max_length=max_length, top_p=top_p, temperature=temperature)

    return generation_config

user_prompt = "<|User|>:{user}\n"
robot_prompt = "<|Bot|>:{robot}<eoa>\n"
cur_query_prompt = "<|User|>:{user}<eoh>\n<|Bot|>:"

def combine_history(prompt):
    messages = st.session_state.messages
    total_prompt = ""
    for message in messages:
        cur_content = message["content"]
        if message["role"] == "user":
            cur_prompt = user_prompt.replace("{user}", cur_content)
        elif message["role"] == "robot":
            cur_prompt = robot_prompt.replace("{robot}", cur_content)
        else:
            raise RuntimeError
        total_prompt += cur_prompt
    total_prompt = total_prompt + cur_query_prompt.replace("{user}", prompt)
    return total_prompt

def main():
    # torch.cuda.empty_cache()
    print("load model begin.")
    model, tokenizer = load_model()
    print("load model end.")

    user_avator = "images/user.png"
    robot_avator = "images/robot.png"

    st.title("食神——菜谱小助手 by 张小白")

    generation_config = prepare_generation_config()

    # Initialize chat history
    if "messages" not in st.session_state:
        st.session_state.messages = []

    # Display chat messages from history on app rerun
    for message in st.session_state.messages:
        with st.chat_message(message["role"], avatar=message.get("avatar")):
            st.markdown(message["content"])

    # Accept user input
    if prompt := st.chat_input("What is up?"):
        # Check if the user input contains certain keywords
        keywords = ["怎么做", "做法", "菜谱"]
        contains_keywords = any(keyword in prompt for keyword in keywords)

        # Display user message in chat message container
        with st.chat_message("user", avatar=user_avator):
            st.markdown(prompt)
        real_prompt = combine_history(prompt)

        # Add user message to chat history
        st.session_state.messages.append({"role": "user", "content": prompt, "avatar": user_avator})

        # If keywords are not present, display a prompt message immediately
        if not contains_keywords:
            with st.chat_message("robot", avatar=robot_avator):
                st.markdown("我是食神周星星的唯一传人张小白，我什么菜都会做，包括黑暗料理，您可以问我什么菜怎么做，我会告诉你具体的做法。")
            # Add robot response to chat history
            st.session_state.messages.append({"role": "robot", "content": "我是食神周星星的唯一传人张小白，我什么菜都会做，包括黑暗料理，您可以问我什么菜怎么做，我会告诉你具体的做法。", "avatar": robot_avator})
        else:
            # Generate robot response
            with st.chat_message("robot", avatar=robot_avator):
                message_placeholder = st.empty()
                for cur_response in generate_interactive(
                    model=model,
                    tokenizer=tokenizer,
                    prompt=real_prompt,
                    additional_eos_token_id=103028,
                    **asdict(generation_config),
                ):
                    # Display robot response in chat message container
                    message_placeholder.markdown(cur_response + "▌")
                message_placeholder.markdown(cur_response)
            # Add robot response to chat history
            st.session_state.messages.append({"role": "robot", "content": cur_response, "avatar": robot_avator})
            torch.cuda.empty_cache()

if __name__ == "__main__":
    main()

我想把参数加到
generation_config = GenerationConfig(max_length=max_length, top_p=top_p, temperature=temperature)
变成：
generation_config = GenerationConfig(max_length=max_length, top_p=top_p, temperature=temperature, repetition-penalty=1.002)
但实际上不行，运行时报错：
<img width="936" alt="111341f39d4a0f34de7680a369fc59b" src="https://github.com/InternLM/xtuner/assets/63148804/92f477b6-5fcf-4148-9629-a6f29d6258d5">

**Comment by LZHgrla** [comment]
https://github.com/InternLM/xtuner/blob/26d333f83bcd84122ffe68459dbbe292a80b5c03/xtuner/tools/chat.py#L333

下划线_，而非-

**Comment by zhanghui-china** [comment]
def load_model():
    model = (
        AutoModelForCausalLM.from_pretrained("/home/zhanghui/shishen2/merged", trust_remote_code=True)
        .to(torch.bfloat16)
        .cuda()
    )
    tokenizer = AutoTokenizer.from_pretrained("/home/zhanghui/shishen2/merged", trust_remote_code=True)
    return model, tokenizer


def prepare_generation_config():
    with st.sidebar:
        max_length = st.slider("Max Length", min_value=32, max_value=2048, value=2048)
        #top_p = st.slider("Top P", 0.0, 1.0, 0.8, step=0.01)
        #temperature = st.slider("Temperature", 0.0, 1.0, 0.7, step=0.01)
        st.button("Clear Chat History", on_click=on_btn_click)

    #generation_config = GenerationConfig(max_length=max_length, top_p=top_p, temperature=temperature )
    generation_config = GenerationConfig(max_length=max_length, top_p=0.8, temperature=0.8, repetition_penalty=1.002 )

    return generation_config


改成以上方式，启动后：
<img width="597" alt="8baa1552c3a456de5211ec47842a15b" src="https://github.com/InternLM/xtuner/assets/63148804/eca49f69-c387-4c50-88b9-cac05baa82ff">
<img width="608" alt="e921642337d5811871e50a533dfcddb" src="https://github.com/InternLM/xtuner/assets/63148804/cfa78a30-afe6-49f4-b8d7-22d1c5ed793a">


是这个没起作用吗？

**Comment by LZHgrla** [comment]
你这个脚本的对话模版是internlm_chat的 不是internlm2_chat

**Comment by zhanghui-china** [comment]
对话模板也可以加到参数里面去吗？

**Comment by LZHgrla** [comment]
这个是需要在这个代码里修改、实现的，看起来是`combine_history`这个函数

**Comment by zhanghui-china** [comment]
def combine_history(prompt):
    messages = st.session_state.messages
    total_prompt = ""
    for message in messages:
        cur_content = message["content"]
        if message["role"] == "user":
            cur_prompt = user_prompt.replace("{user}", cur_content)
        elif message["role"] == "robot":
            cur_prompt = robot_prompt.replace("{robot}", cur_content)
        else:
            raise RuntimeError
        total_prompt += cur_prompt
    total_prompt = total_prompt + cur_query_prompt.replace("{user}", prompt)
    return total_prompt

**Comment by zhanghui-china** [comment]
<img width="371" alt="b88ad65878be8e6e0125142cb6bbf79" src="https://github.com/InternLM/xtuner/assets/63148804/a0a6e7c5-10bc-4bc1-8dd7-99ecd67541a4">

**Comment by zhanghui-china** [comment]
[app.py.txt](https://github.com/InternLM/xtuner/files/14047506/app.py.txt)
代码如上。

**Comment by LZHgrla** [comment]
后续xtuner会有一自己的webui，现阶段建议先按照原函数，参照着新模板进行修改

**Comment by zhanghui-china** [comment]
终于找到解决方法了：
需要在代码中，
将 additional_eos_token_id=103028
改为 additional_eos_token_id=92542
