### ISSUE TITLE
是训练xtuner train的时候把prompt 工程的要求训练进模型，还是xtuner chat的时候使用提示实现prompt

### ISSUE THREAD

**Issue by zhanghui-china** [InternLM/xtuner#358]
def combine_history(prompt):
    messages = st.session_state.messages
    total_prompt = "您是一个厨师，熟悉很多菜的制作方法。用户会问你哪些菜怎么制作，您可以用自己的专业知识答复他。回答的内容一般包含两块：这道菜需要哪些食材，这道菜具体是怎么做出来的。如果用户没有问菜谱相关的问题，就提醒他对菜谱的相关问题进行提问。"
    for message in messages:
        cur_content = message["content"]
        if message["role"] == "user":
            cur_prompt = user_prompt.replace("{user}", cur_content)
        elif message["role"] == "robot":
            cur_prompt = robot_prompt.replace("{robot}", cur_content)
        else:
            raise RuntimeError
        total_prompt += cur_prompt
    total_prompt = total_prompt + cur_query_prompt.replace("{user}", prompt)
    return total_prompt

在应用中这样设置好像没有反应。

**Comment by LZHgrla** [comment]
如果场景单一，都使用是最合适的
