### ISSUE TITLE
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by datalee** [InternLM/xtuner#365]
`xtuner list-cfg`后出现这样的报错，xtuner-0.1.11
`import pandas._libs.window.aggregations as window_aggregations
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found`

**Comment by LZHgrla** [comment]
```python
import xtuner
print(xtuner.__version__)
```

尝试一下上述代码，看是否报错，如果报错可以仔细查看一下报错信息，确认是哪个包有问题。

**Comment by datalee** [comment]
> ```python
> import xtuner
> print(xtuner.__version__)
> ```
> 
> 尝试一下上述代码，看是否报错，如果报错可以仔细查看一下报错信息，确认是哪个包有问题。

已解决
