### ISSUE TITLE
multi-node training

### ISSUE THREAD

**Issue by rese1f** [InternLM/xtuner#366]
hi, can u provide a multi-node training examples?

**Comment by LZHgrla** [comment]
@rese1f  Hi!

Here is an example of training with  2 * 8 * GPUs.

1. slurm

`$PARTITION` means the virtual partition of slurm.

```bash
srun -p $PARTITION --job-name=name --nodes=2 --gres=gpu:8 --ntasks-per-node=8 xtuner train XXX --launcher slurm
```

### torchrun

`$NODE_0_ADDR` means the ip address of the node_0 machine.

```bash
# excuete on node 0
NPROC_PER_NODE=8 NNODES=2 PORT=29600 ADDR=$NODE_0_ADDR NODE_RANK=0 xtuner train XXX

# excuete on node 1
NPROC_PER_NODE=8 NNODES=2 PORT=29600 ADDR=$NODE_0_ADDR NODE_RANK=1 xtuner train XXX
```

**Comment by rese1f** [comment]
thank you! I'll have a try!

**Comment by ztfmars** [comment]
> @rese1f Hi!
> 
> Here is an example of training with 2 * 8 * GPUs.
> 
> 1. slurm
> 
> `$PARTITION` means the virtual partition of slurm.
> 
> ```shell
> srun -p $PARTITION --job-name=name --nodes=2 --gres=gpu:8 --ntasks-per-node=8 xtuner train XXX --launcher slurm
> ```
> 
> ### torchrun
> `$NODE_0_ADDR` means the ip address of the node_0 machine.
> 
> ```shell
> # excuete on node 0
> NPROC_PER_NODE=8 NNODES=2 PORT=29600 ADDR=$NODE_0_ADDR NODE_RANK=0 xtuner train XXX
> 
> # excuete on node 1
> NPROC_PER_NODE=8 NNODES=2 PORT=29600 ADDR=$NODE_0_ADDR NODE_RANK=1 xtuner train XXX
> ```

what's the meaning of this? use 8 process in 2 nodes, and each node runs a task? can this help to solve multi tasks training at the same time?
by the way , is there any detail instruction or tutorial on this?
thx in advance
