### ISSUE TITLE
微调InternLM2-7b-chat，max_length改小时报错epoch_length为0

### ISSUE THREAD

**Issue by luzhongyu** [InternLM/xtuner#370]
其他配置不变，max_length=2048时运行正常，当max_length=256时，报错epoch_length must be a positive integer, but got 0

**Comment by LZHgrla** [comment]
有可能是大多数数据的“输入部分”就已经超过了256的长度，此时截断到256后，并不会有labels进行监督训练，所以xtuner会将这部分数据剔除。进而导致数据量不够，产生该错误。

https://github.com/InternLM/xtuner/blob/4981bb9fda102ff9be650e78910cd9a008adf06f/xtuner/dataset/huggingface.py#L205-L209

**Comment by luzhongyu** [comment]
> 有可能是大多数数据的“输入部分”就已经超过了256的长度，此时截断到256后，并不会有labels进行监督训练，所以xtuner会将这部分数据剔除。进而导致数据量不够，产生该错误。
> 
> https://github.com/InternLM/xtuner/blob/4981bb9fda102ff9be650e78910cd9a008adf06f/xtuner/dataset/huggingface.py#L205-L209

是的，数据的input的部分普遍长度比较长超过了256，这种有什么办法吗？是否需要自己预处理提前截取数据？

**Comment by LZHgrla** [comment]
这个就看自己需求了
不过。为何不增大max_length呢？

**Comment by luzhongyu** [comment]
> 这个就看自己需求了 不过。为何不增大max_length呢？

由于显存只有16G，增大max_length后qlora训练速度很慢（每10条input约4分钟），所以想尝试下降低max_length看看能否加快训练

**Comment by LZHgrla** [comment]
但是，如果训练的数据长度就是很长，此时降低max_length就不能满足预期了。所以就是个trade-off，需要取舍

**Comment by luzhongyu** [comment]
> 但是，如果训练的数据长度就是很长，此时降低max_length就不能满足预期了。所以就是个trade-off，需要取舍

是的，我们评估下如何处理更适合我们的场景，谢谢 @LZHgrla 解答
