### ISSUE TITLE
llava-internlm2-7b 推理mmbench速度问题

### ISSUE THREAD

**Issue by davidluciolu** [InternLM/xtuner#376]
使用modelscope上下载的llava-internlm2-7b推理MMBench_DEV_EN
gpu：4*V100 32g
耗时约12小时，请问是否正常？
推理脚本：
```
export CUDA_VISIBLE_DEVICES=0,1,2,3
model_path=./xtuner/internlm/internlm2-chat-7b
ve_path=./xtuner/openai/clip-vit-large-patch14-336/
llava_path=./xtuner/llava-internlm2/llava-internlm2-7b/

xtuner mmbench ${model_path} \
  --visual-encoder ${ve_path} \
  --llava ${llava_path} \
  --prompt-template internlm_chat \
  --data-path ../data/mmbench/MMBench_DEV_EN.tsv \
  --work-dir ./work_dirs/offical_llava-internlm2-7b/MMBench_DEV_EN
```

运行截图
![image](https://github.com/InternLM/xtuner/assets/46648807/9e310653-7ada-47f8-bcc8-256eeb3d5fa6)

![image](https://github.com/InternLM/xtuner/assets/46648807/bf3e2584-e1f4-43e2-a495-2f8390604992)

**Comment by davidluciolu** [comment]
另外，使用单卡V100推理速度稍快一些，约10小时

**Comment by LZHgrla** [comment]
@davidluciolu  Hi
1. 我这边单卡A100预计20分钟左右可以评测完成
2. 目前main分支的代码支持DDP多卡评测（https://github.com/InternLM/xtuner/pull/300）。建议拉取main分支代码，并在 `xtuner mmbench` 前增加参数 `NPROC_PER_NODE=$GPU_NUM` 来启动多卡评测
3. `--prompt-template` 选项有点问题，应该使用`internlm2_chat`，而非`internlm_chat`。这一不匹配可能导致每一次生成无法正常结束，进而导致评测耗时增大

**Comment by StarCycle** [comment]
啊啊啊我就遇到了这个问题，恨不能早看到此issue！

**Comment by davidluciolu** [comment]
谢谢！更换模板后v100单卡约30分钟完成MMBench_DEV_EN推理
