### ISSUE TITLE
'end' value is not set correctly in lr schedulers

### ISSUE THREAD

**Issue by gzlong96** [InternLM/xtuner#386]
Hi. When I try to train more than 1 epoch, I found that the lr scheduler is not function as expected. For example, the max_epochs is 3 in this [config](https://github.com/InternLM/xtuner/blob/47c08d871652fe317b77fbd9948a4a170cb76f7f/xtuner/configs/internlm/internlm2_chat_7b/internlm2_chat_7b_qlora_alpaca_e3.py#L142). The cosine scheduler will stop working after the first epoch. The is caused by the default 'end' value in the scheduler was set to 1 by the TrainLoop runner, which is an iter-based runner and its max_epochs is always 1. But the true end value should be max_epochs * epoch_length. So, I have to set end=max_epochs manually in the config.
I not sure if it's a dependency issue. Could you please have a check on your side? My mmengine is 0.10.3.

Here is the log of my exp. The lr froze after the first epoch.
![image](https://github.com/InternLM/xtuner/assets/30570937/a6469c95-bcc5-4329-89f3-75cca55d317c)

**Comment by LZHgrla** [comment]
Hi! @gzlong96  Thanks for reporting this issue.
You are right, and it is a bug of parameter scheduler settings.

We should rename the argument `T_max` to `end` in all config files, to get the correct behavior!
```diff
param_scheduler = [
    dict(
        type=LinearLR,
        start_factor=1e-5,
        by_epoch=True,
        begin=0,
        end=warmup_ratio * max_epochs,
        convert_to_iter_based=True),
    dict(
        type=CosineAnnealingLR,
        eta_min=0.0,
        by_epoch=True,
        begin=warmup_ratio * max_epochs,
-       T_max=max_epochs,
+       end=max_epochs,
        convert_to_iter_based=True)
]
```

I will try to fix it, and if convenient, you are also welcome to submit a PR for this issue!

**Comment by gzlong96** [comment]
Sure. I'll submit a PR ASAP.

**Comment by gzlong96** [comment]
PR submitted.
