### ISSUE TITLE
多轮对话训练后测试不能多轮对话。

### ISSUE THREAD

**Issue by ZPfree** [InternLM/xtuner#391]
![4c8ef33d5e74602c2300c3eac600f4b](https://github.com/InternLM/xtuner/assets/16116418/f048afe4-24ce-4d03-bf79-3249d5828256)
 然后我的数据格式是这样
![image](https://github.com/InternLM/xtuner/assets/16116418/b6e64e2a-2a0c-4ff7-8fc3-09bf30b0ecb0)

没有按照
![937eb273ddc2ab8a2d8b5f9e45050d5](https://github.com/InternLM/xtuner/assets/16116418/54aed7f1-bcad-4209-85be-83f5c65a3500)
请问是我数据格式导致的不能多轮对话吗

**Comment by LZHgrla** [comment]
数据看起来没问题，请问测试时的效果是什么？

**Comment by ZPfree** [comment]
![3e2aa8fe722c8ca3a421ed54f02bd22](https://github.com/InternLM/xtuner/assets/16116418/73ec260b-aa7c-4d5b-9389-1020a6760155)
![c17e7b64af8a16792be7ef8d2034574](https://github.com/InternLM/xtuner/assets/16116418/6541db00-8ac9-4f26-8b7c-d2ab2cd5d385)

第一张图是测试的时候感觉稍微可以医生回话的截图，第二图是我训练的数据集这种医生会根据问题继续提问，测试过程中，发现医生只会解答现在的问题，不会像图2一样提出问题让病人回答

**Comment by ZPfree** [comment]
他的配置和单轮没有区别吧？我看文档没有提

**Comment by LZHgrla** [comment]
数据的system可以修正一下，现在可能还会有一些问题。system最好从user的角度去阐述，而非从assistant的角度。 类似：你是XXX，请XXXXX

其他地方，从配置上来看没有问题

**Comment by LZHgrla** [comment]
> 他的配置和单轮没有区别吧？我看文档没有提

训练的时候只要数据构造成这个样子就会在一起训练。
chat的时候都有历史会话管理，也没有问题

**Comment by ZPfree** [comment]
![296d34849b06c77f506fd191e5234c5](https://github.com/InternLM/xtuner/assets/16116418/fdfb6531-3070-46a6-948f-aac296ae8727)
我已经改成了这个格式，system 还是先前的值我是。。。要改成你是。。。训练快结束了，我到时再试试 多谢

**Comment by ZPfree** [comment]
![image](https://github.com/InternLM/xtuner/assets/16116418/8feeb859-2341-46f0-a2c9-92b568e76104)
![image](https://github.com/InternLM/xtuner/assets/16116418/36d94789-53e2-43eb-aa8f-80ea6c642a9a)
一图数据格式，二图还是不会问

**Comment by ZPfree** [comment]
![f9d87a62c46bcb3f7d049a701a1b717](https://github.com/InternLM/xtuner/assets/16116418/4f2cbb9a-9b72-4b77-a427-56188d2cb24e)
yl医疗助手为什么不会问我问题，测试多条数据 都是类似这种
![image](https://github.com/InternLM/xtuner/assets/16116418/177a1ed3-24bf-4b8e-9d2f-48fd6dfe5756)
![image](https://github.com/InternLM/xtuner/assets/16116418/9325cbd9-3090-410e-81ff-ad39a2fef01b)

数据集里医生是会提问的

**Comment by LZHgrla** [comment]
您好 @ZPfree 
这是炼丹及模型效果的问题了，不同场景、不同训练配置都有可能导致模型效果的差异，所以我们这边无法提供相关建议
