### ISSUE TITLE
怎么在IDE中debug xtuner？

### ISSUE THREAD

**Issue by shipengai** [InternLM/xtuner#397]
现在是命令行直接运行，想debug看下里面代码？应该如何在pytcharm或者vscode中debug

**Comment by LZHgrla** [comment]
```
import xtuner
print(xtuner)
```

获得输出：
```
<module 'xtuner' from '/xxx/xtuner/__init__.py'>
```

此处路径即 xtuner pypi 包的安装路径

**Comment by shipengai** [comment]
@LZHgrla 怎么样可以不用xtuner开头呢，例如直接 python xtuner/tools/train.py这样可以吗？我把xtuner下载到本地了，想debug到这个文件夹里面的代码

**Comment by LZHgrla** [comment]
> @LZHgrla 怎么样可以不用xtuner开头呢，例如直接 python xtuner/tools/train.py这样可以吗？我把xtuner下载到本地了，想debug到这个文件夹里面的代码

可以的！

**Comment by shipengai** [comment]
> > @LZHgrla 怎么样可以不用xtuner开头呢，例如直接 python xtuner/tools/train.py这样可以吗？我把xtuner下载到本地了，想debug到这个文件夹里面的代码
> 
> 可以的！

看了下xtuner/entry_point.py文件里的cli文件，单卡使用python，多卡使用torchrun

**Comment by LZHgrla** [comment]
> > > @LZHgrla 怎么样可以不用xtuner开头呢，例如直接 python xtuner/tools/train.py这样可以吗？我把xtuner下载到本地了，想debug到这个文件夹里面的代码
> 
> > 
> 
> > 可以的！
> 
> 
> 
> 看了下xtuner/entry_point.py文件里的cli文件，单卡使用python，多卡使用torchrun

是的，同时该文件也定义了对应命令与python脚本的映射关系～

**Comment by shipengai** [comment]
> > > > @LZHgrla 怎么样可以不用xtuner开头呢，例如直接 python xtuner/tools/train.py这样可以吗？我把xtuner下载到本地了，想debug到这个文件夹里面的代码
> > 
> > 
> > > 
> > 
> > 
> > > 可以的！
> > 
> > 
> > 看了下xtuner/entry_point.py文件里的cli文件，单卡使用python，多卡使用torchrun
> 
> 是的，同时该文件也定义了对应命令与python脚本的映射关系～

谢谢解答。在问题https://github.com/InternLM/xtuner/issues/352中提到We found that the official implementation of sampler did not synchronize seeds between multiple ranks.
可以说下是修改了哪块代码吗？

**Comment by LZHgrla** [comment]
> > > > > @LZHgrla 怎么样可以不用xtuner开头呢，例如直接 python xtuner/tools/train.py这样可以吗？我把xtuner下载到本地了，想debug到这个文件夹里面的代码
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 可以的！
> 
> > > 
> 
> > > 
> 
> > > 看了下xtuner/entry_point.py文件里的cli文件，单卡使用python，多卡使用torchrun
> 
> > 
> 
> > 是的，同时该文件也定义了对应命令与python脚本的映射关系～
> 
> 
> 
> 谢谢解答。在问题[https://github.com/InternLM/xtuner/issues/352](url) 中提到We found that the official implementation of sampler did not synchronize seeds between multiple ranks.
> 
> 可以说下是修改了哪块代码吗？

done！
