### ISSUE TITLE
about tokenizer

### ISSUE THREAD

**Issue by syf-fgnb** [InternLM/xtuner#398]
Hi, 

Thanks for your excellent work. I want to know how to modify the tokenizer (e.g. add a new token to the existing tokenizer).

**Comment by LZHgrla** [comment]
If you want to add a new token, you need to modify the tokenizer and LLM (if needed)

1. Modify your tokenizer, to add these new tokens. You can do this offline, that directly modify the tokenizer file, or do this online by modifying the tokenizer config in your training config file
https://github.com/InternLM/xtuner/blob/f63859b3d0cb39cbac709e3850f3fe01de1023aa/xtuner/configs/internlm/internlm2_chat_7b/internlm2_chat_7b_qlora_alpaca_e3.py#L61-L65

2. If these added tokens extend the vocab size, please remember to modify your LLM's embed layer and lm_head, to support these token embedding and prediction. You can do this after these lines,
https://github.com/InternLM/xtuner/blob/f63859b3d0cb39cbac709e3850f3fe01de1023aa/xtuner/model/sft.py#L26-L30

3. Ensure added embedding and lm_head weights are trainable. LoRA will freeze these parameters by default, and you should modify it by `modules_to_save` arguments of `LoraConfig`, or directly use full-parameter tuning.
4. Ensure that all tokenizers and LLMs throughout the entire process (including training, converting, chatting) have been modified.

**Comment by syf-fgnb** [comment]
Hi @ LZHgrla, thanks for your help! 
Currently, I have an error `02/05 04:08:40 - mmengine - WARNING - WARNING: command error: '[Errno 28] No space left on device: '/home/mywork/.triton/autotune''!` when I convert the checkpoint to hf according to 'Model Convert' in README. Can I assign a specified path which is of enough space to save the intermediate files?

**Comment by LZHgrla** [comment]
@syf-fgnb 
Maybe you can specify the cache dir of triton library by `export TRITON_CACHE_DIR='xxx'`

ref: https://github.com/openai/triton/blob/9ff4870b2f386046054c6fe79c548ecdf9f2382d/python/triton/runtime/cache.py#L63

**Comment by syf-fgnb** [comment]
Hi @LZHgrla, thanks. 

I have one last question. Suppose I want to evaluate my own model (which is not LLava), how can I evaluate my model on some popular benchmarks (e.g., MMMU) and set the hyperparameters?

**Comment by LZHgrla** [comment]
@syf-fgnb 
You can use OpenCompass and VLMEvalKit

https://github.com/open-compass/opencompass
https://github.com/open-compass/VLMEvalKit
