### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:6 and cuda:7! (when checking argumen t for argument mat2 in method wrapper_CUDA_mm)

### ISSUE THREAD

**Issue by xmy0916** [InternLM/xtuner#399]
![image](https://github.com/InternLM/xtuner/assets/43675899/ec7c4671-6603-4223-97fa-2d4c7cd33de6)
llava interlm2chat + qlora 推理mmb数据集报错tensor不在一个设备上，这个挺奇怪的我看代码没有to(device)的操作全是cuda()咋还会报错呢

**Comment by LZHgrla** [comment]
@xmy0916 
我在我的环境下执行以下命令以模拟您的情况，但是无法复现该报错。考虑可能是触发了 peft 某些奇怪的载入逻辑导致了这个报错。

```shell
CUDA_VISIBLE_DEVICES=0,1 xtuner mmbench internlm/internlm2-chat-7b --llava xtuner/llava-internlm2-7b  --visual-encoder openai/clip-vit-large-patch14-336  --prompt-template internlm2_chat --data-path ./MMBench_DEV_EN.tsv
```

目前可以尝试在单卡环境下评测，验证是否有问题。

比如使用2号卡单卡评测：
```
CUDA_VISIBLE_DEVICES=2 xtuner mmbench XXX
```

同时，也可以启用 DDP，以加速评测。以使用2号、3号卡为例：

```
NPROC_PER_NODE=2 CUDA_VISIBLE_DEVICES=2,3 xtuner mmbench XXX
```

**Comment by xmy0916** [comment]
@LZHgrla project layer我做了点改动，加了个卷积层，不确定是不是这个导致的

**Comment by LZHgrla** [comment]
@xmy0916 
如果改动不涉及 device，应该不会有问题

**Comment by xmy0916** [comment]
> @xmy0916 如果改动不涉及 device，应该不会有问题

好滴，我也感觉挺奇怪的，我加cuda device visalbe=0限制只用一张卡就行了
