### ISSUE TITLE
xtuner convert merge CUDA out of memory

### ISSUE THREAD

**Issue by zhudongwork** [InternLM/xtuner#401]
使用最新版的xtuner merge代码时出现CUDA out of memory错误，老版本没有出现过，看了一下新版的merge.py，--device默认设置为cuda，改回auto就能正常运行了，建议调整默认参数。

**Comment by LZHgrla** [comment]
您好 @zhudongwork 

感谢您的issue

修改的详细原因见 https://github.com/InternLM/xtuner/issues/273，所以暂时不会考虑做修改

如果需要使用 auto，请使用参数 --device auto
