### ISSUE TITLE
认知微调失败

### ISSUE THREAD

**Issue by xxg98** [InternLM/xtuner#402]
认知微调失败

报错如下：
1. type=<class 'xtuner.engine.hooks.dataset_info_hook.DatasetInfoHook'>),
         ^
SyntaxError: invalid syntax

2. yapf.yapflib.errors.YapfError: <unknown>:14:14: invalid syntax

3. SyntaxError: Failed to format the config file, please check the syntax of:

配置如下：
# Copyright (c) OpenMMLab. All rights reserved.
import torch
from datasets import load_dataset
from mmengine.dataset import DefaultSampler
from mmengine.hooks import (CheckpointHook, DistSamplerSeedHook, IterTimerHook,
                            LoggerHook, ParamSchedulerHook)
from mmengine.optim import AmpOptimWrapper, CosineAnnealingLR, LinearLR
from peft import LoraConfig
from torch.optim import AdamW
from transformers import (AutoModelForCausalLM, AutoTokenizer,
                          BitsAndBytesConfig)

from xtuner.dataset import process_hf_dataset
from xtuner.dataset.collate_fns import default_collate_fn
from xtuner.dataset.map_fns import oasst1_map_fn, template_map_fn_factory
from xtuner.engine.hooks import (DatasetInfoHook, EvaluateChatHook,
                                 VarlenAttnArgsToMessageHubHook)
from xtuner.engine.runner import TrainLoop
from xtuner.model import SupervisedFinetune
from xtuner.utils import PROMPT_TEMPLATE

#######################################################################
#                          PART 1  Settings                           #
#######################################################################
# Model
pretrained_model_name_or_path = '/home/yanyonghao/work/projects/internlm2-chat-7b'
use_varlen_attn = False

# Data
data_path = '/home/yanyonghao/work/projects/xtuner/data/personal_assistant.json'
prompt_template = PROMPT_TEMPLATE.internlm2_chat
max_length = 512
pack_to_max_length = True

# Scheduler & Optimizer
batch_size = 2  # per_device
accumulative_counts = 16
dataloader_num_workers = 0
max_epochs = 3
optim_type = AdamW
lr = 2e-4
betas = (0.9, 0.999)
weight_decay = 0
max_norm = 1  # grad clip
warmup_ratio = 0.03

# Save
save_steps = 500
save_total_limit = 2  # Maximum checkpoints to keep (-1 means unlimited)

# Evaluate the generation performance during the training
evaluation_freq = 90
SYSTEM = ''
evaluation_inputs = [
    '请介绍一下你自己', '你是谁？'
]

#######################################################################
#                      PART 2  Model & Tokenizer                      #
#######################################################################
tokenizer = dict(
    type=AutoTokenizer.from_pretrained,
    pretrained_model_name_or_path=pretrained_model_name_or_path,
    trust_remote_code=True,
    padding_side='right')

model = dict(
    type=SupervisedFinetune,
    use_varlen_attn=use_varlen_attn,
    llm=dict(
        type=AutoModelForCausalLM.from_pretrained,
        pretrained_model_name_or_path=pretrained_model_name_or_path,
        trust_remote_code=True,
        torch_dtype=torch.float16,
        quantization_config=dict(
            type=BitsAndBytesConfig,
            load_in_4bit=True,
            load_in_8bit=False,
            llm_int8_threshold=6.0,
            llm_int8_has_fp16_weight=False,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type='nf4')),
    lora=dict(
        type=LoraConfig,
        r=64,
        lora_alpha=16,
        lora_dropout=0.1,
        bias='none',
        task_type='CAUSAL_LM'))

#######################################################################
#                      PART 3  Dataset & Dataloader                   #
#######################################################################
train_dataset = dict(
    type=process_hf_dataset,
    # dataset=dict(type=load_dataset, path=data_path),
    dataset=dict(type=load_dataset, path='json', data_files=dict(train=data_path)),
    tokenizer=tokenizer,
    max_length=max_length,
    # dataset_map_fn=oasst1_map_fn,
    dataset_map_fn=None,
    template_map_fn=dict(
        type=template_map_fn_factory, template=prompt_template),
    remove_unused_columns=True,
    shuffle_before_pack=True,
    pack_to_max_length=pack_to_max_length,
    use_varlen_attn=use_varlen_attn)

train_dataloader = dict(
    batch_size=batch_size,
    num_workers=dataloader_num_workers,
    dataset=train_dataset,
    sampler=dict(type=DefaultSampler, shuffle=True),
    collate_fn=dict(type=default_collate_fn, use_varlen_attn=use_varlen_attn))

#######################################################################
#                    PART 4  Scheduler & Optimizer                    #
#######################################################################
# optimizer
optim_wrapper = dict(
    type=AmpOptimWrapper,
    optimizer=dict(
        type=optim_type, lr=lr, betas=betas, weight_decay=weight_decay),
    clip_grad=dict(max_norm=max_norm, error_if_nonfinite=False),
    accumulative_counts=accumulative_counts,
    loss_scale='dynamic',
    dtype='float16')

# learning policy
# More information: https://github.com/open-mmlab/mmengine/blob/main/docs/en/tutorials/param_scheduler.md  # noqa: E501
param_scheduler = [
    dict(
        type=LinearLR,
        start_factor=1e-5,
        by_epoch=True,
        begin=0,
        end=warmup_ratio * max_epochs,
        convert_to_iter_based=True),
    dict(
        type=CosineAnnealingLR,
        eta_min=0.0,
        by_epoch=True,
        begin=warmup_ratio * max_epochs,
        end=max_epochs,
        convert_to_iter_based=True)
]

# train, val, test setting
train_cfg = dict(type=TrainLoop, max_epochs=max_epochs)

#######################################################################
#                           PART 5  Runtime                           #
#######################################################################
# Log the dialogue periodically during the training process, optional
custom_hooks = [
    dict(type=DatasetInfoHook, tokenizer=tokenizer),
    dict(
        type=EvaluateChatHook,
        tokenizer=tokenizer,
        every_n_iters=evaluation_freq,
        evaluation_inputs=evaluation_inputs,
        system=SYSTEM,
        prompt_template=prompt_template)
]

if use_varlen_attn:
    custom_hooks += [dict(type=VarlenAttnArgsToMessageHubHook)]

# configure default hooks
default_hooks = dict(
    # record the time of every iteration.
    timer=dict(type=IterTimerHook),
    # print log every 10 iterations.
    logger=dict(type=LoggerHook, log_metric_by_epoch=False, interval=10),
    # enable the parameter scheduler.
    param_scheduler=dict(type=ParamSchedulerHook),
    # save checkpoint per `save_steps`.
    checkpoint=dict(
        type=CheckpointHook,
        by_epoch=False,
        interval=save_steps,
        max_keep_ckpts=save_total_limit),
    # set sampler seed in distributed evrionment.
    sampler_seed=dict(type=DistSamplerSeedHook),
)

# configure environment
env_cfg = dict(
    # whether to enable cudnn benchmark
    cudnn_benchmark=False,
    # set multi process parameters
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    # set distributed parameters
    dist_cfg=dict(backend='nccl'),
)

# set visualizer
visualizer = None

# set log level
log_level = 'INFO'

# load from which checkpoint
load_from = None

# whether to resume training from the loaded checkpoint
resume = False

# Defaults to use random seed and disable `deterministic`
randomness = dict(seed=None, deterministic=False)

# set log processor
log_processor = dict(by_epoch=False)

环境：
python：3.10
cuda：12.0
xtune：r最新拉取版本
数据集：无语法错误的json数组，参考教程：https://github.com/InternLM/tutorial/blob/main/xtuner/self.md

**Comment by LZHgrla** [comment]
@xxg98  
请张贴一下完整的报错信息

**Comment by xxg98** [comment]
> @xxg98 请张贴一下完整的报错信息


完整报错信息如下：
[2024-02-05 13:33:50,500] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-05 13:33:52,327] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
02/05 13:33:52 - mmengine - INFO - 
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
    CUDA available: True
    MUSA available: False
    numpy_random_seed: 39300127
    GPU 0: NVIDIA GeForce RTX 3090 Ti
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 12.0, V12.0.140
    GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
    PyTorch: 2.2.0+cu121
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

    OpenCV: 4.9.0
    MMEngine: 0.10.3

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 39300127
    deterministic: False
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

Traceback (most recent call last):
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/yapf/pytree/pytree_utils.py", line 113, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 188, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 157, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/yapf_third_party/_ylib2to3/pgen2/parse.py", line 230, in addtoken
    return self._addtoken(ilabel, type, value, context)
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/yapf_third_party/_ylib2to3/pgen2/parse.py", line 313, in _addtoken
    raise ParseError('bad input', type, value, context)
yapf_third_party._ylib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (14, 13))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 206, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/yapf/pytree/pytree_utils.py", line 116, in ParseCodeToTree
    ast.parse(code)
  File "/home/yanyonghao/anaconda3/envs/py3_10/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 14
    type=<class 'xtuner.engine.hooks.dataset_info_hook.DatasetInfoHook'>),
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/mmengine/config/config.py", line 1481, in pretty_text
    text, _ = FormatCode(
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 209, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
yapf.yapflib.errors.YapfError: <unknown>:14:14: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanyonghao/work/projects/xtuner/xtuner/tools/train.py", line 307, in <module>
    main()
  File "/home/yanyonghao/work/projects/xtuner/xtuner/tools/train.py", line 296, in main
    runner = Runner.from_cfg(cfg)
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 403, in __init__
    self._log_env(env_cfg)
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 2388, in _log_env
    self.logger.info(f'Config:\n{self.cfg.pretty_text}')
  File "/home/yanyonghao/work/projects/xtuner/xtuner/lib/python3.10/site-packages/mmengine/config/config.py", line 1484, in pretty_text
    raise SyntaxError('Failed to format the config file, please '
SyntaxError: Failed to format the config file, please check the syntax of: 
SYSTEM=''
accumulative_counts=16
batch_size=2
betas=(
    0.9,
    0.999,
    )
custom_hooks=[
    dict(tokenizer=dict(
            padding_side='right',
            pretrained_model_name_or_path='/home/yanyonghao/work/projects/internlm2-chat-7b',
            trust_remote_code=True,
            type='transformers.AutoTokenizer.from_pretrained'),
        type=<class 'xtuner.engine.hooks.dataset_info_hook.DatasetInfoHook'>),
    dict(evaluation_inputs=[
            '请介绍一下你自己',
            '你是谁？',
            ],
        every_n_iters=90,
        prompt_template=dict(
            INSTRUCTION='<|im_start|>user\n{input}<|im_end|>\n<|im_start|>assistant\n',
            SEP='\n',
            STOP_WORDS=[
                '<|im_end|>',
                ],
            SUFFIX='<|im_end|>',
            SUFFIX_AS_EOS=True,
            SYSTEM='<|im_start|>system\n{system}<|im_end|>\n'),
        system='',
        tokenizer=dict(
            padding_side='right',
            pretrained_model_name_or_path='/home/yanyonghao/work/projects/internlm2-chat-7b',
            trust_remote_code=True,
            type='transformers.AutoTokenizer.from_pretrained'),
        type=<class 'xtuner.engine.hooks.evaluate_chat_hook.EvaluateChatHook'>),
    ]
data_path='/home/yanyonghao/work/projects/xtuner/data/personal_assistant.json'
dataloader_num_workers=0
default_hooks=dict(
    checkpoint=dict(
        by_epoch=False,
        interval=500,
        max_keep_ckpts=2,
        type='mmengine.hooks.CheckpointHook'),
    logger=dict(
        interval=10,
        log_metric_by_epoch=False,
        type='mmengine.hooks.LoggerHook'),
    param_scheduler=dict(
        type='mmengine.hooks.ParamSchedulerHook'),
    sampler_seed=dict(
        type='mmengine.hooks.DistSamplerSeedHook'),
    timer=dict(
        type='mmengine.hooks.IterTimerHook'))
env_cfg=dict(
    cudnn_benchmark=False,
    dist_cfg=dict(
        backend='nccl'),
    mp_cfg=dict(
        mp_start_method='fork',
        opencv_num_threads=0))
evaluation_freq=90
evaluation_inputs=[
    '请介绍一下你自己',
    '你是谁？',
    ]
launcher='none'
load_from=None
log_level='INFO'
log_processor=dict(
    by_epoch=False)
lr=0.0002
max_epochs=3
max_length=512
max_norm=1
model=dict(
    llm=dict(
        pretrained_model_name_or_path='/home/yanyonghao/work/projects/internlm2-chat-7b',
        quantization_config=dict(
            bnb_4bit_compute_dtype='torch.float16',
            bnb_4bit_quant_type='nf4',
            bnb_4bit_use_double_quant=True,
            llm_int8_has_fp16_weight=False,
            llm_int8_threshold=6.0,
            load_in_4bit=True,
            load_in_8bit=False,
            type='transformers.BitsAndBytesConfig'),
        torch_dtype='torch.float16',
        trust_remote_code=True,
        type='transformers.AutoModelForCausalLM.from_pretrained'),
    lora=dict(
        bias='none',
        lora_alpha=16,
        lora_dropout=0.1,
        r=64,
        task_type='CAUSAL_LM',
        type='peft.LoraConfig'),
    type=<class 'xtuner.model.sft.SupervisedFinetune'>,
    use_varlen_attn=False)
optim_type='torch.optim.AdamW'
optim_wrapper=dict(
    accumulative_counts=16,
    clip_grad=dict(
        error_if_nonfinite=False,
        max_norm=1),
    dtype='float16',
    loss_scale='dynamic',
    optimizer=dict(
        betas=(
            0.9,
            0.999,
            ),
        lr=0.0002,
        type='torch.optim.AdamW',
        weight_decay=0),
    type='mmengine.optim.AmpOptimWrapper')
pack_to_max_length=True
param_scheduler=[
    dict(begin=0,
        by_epoch=True,
        convert_to_iter_based=True,
        end=0.09,
        start_factor=1e-05,
        type='mmengine.optim.LinearLR'),
    dict(begin=0.09,
        by_epoch=True,
        convert_to_iter_based=True,
        end=3,
        eta_min=0.0,
        type='mmengine.optim.CosineAnnealingLR'),
    ]
pretrained_model_name_or_path='/home/yanyonghao/work/projects/internlm2-chat-7b'
prompt_template=dict(
    INSTRUCTION='<|im_start|>user\n{input}<|im_end|>\n<|im_start|>assistant\n',
    SEP='\n',
    STOP_WORDS=[
        '<|im_end|>',
        ],
    SUFFIX='<|im_end|>',
    SUFFIX_AS_EOS=True,
    SYSTEM='<|im_start|>system\n{system}<|im_end|>\n')
randomness=dict(
    deterministic=False,
    seed=None)
resume=False
save_steps=500
save_total_limit=2
tokenizer=dict(
    padding_side='right',
    pretrained_model_name_or_path='/home/yanyonghao/work/projects/internlm2-chat-7b',
    trust_remote_code=True,
    type='transformers.AutoTokenizer.from_pretrained')
train_cfg=dict(
    max_epochs=3,
    type=<class 'xtuner.engine.runner.loops.TrainLoop'>)
train_dataloader=dict(
    batch_size=2,
    collate_fn=dict(
        type='<function default_collate_fn at 0x7f50950e08b0>',
        use_varlen_attn=False),
    dataset=dict(
        dataset=dict(
            data_files=dict(
                train='/home/yanyonghao/work/projects/xtuner/data/personal_assistant.json'),
            path='json',
            type='datasets.load_dataset'),
        dataset_map_fn=None,
        max_length=512,
        pack_to_max_length=True,
        remove_unused_columns=True,
        shuffle_before_pack=True,
        template_map_fn=dict(
            template=dict(
                INSTRUCTION='<|im_start|>user\n{input}<|im_end|>\n<|im_start|>assistant\n',
                SEP='\n',
                STOP_WORDS=[
                    '<|im_end|>',
                    ],
                SUFFIX='<|im_end|>',
                SUFFIX_AS_EOS=True,
                SYSTEM='<|im_start|>system\n{system}<|im_end|>\n'),
            type='<function template_map_fn_factory at 0x7f50950c1750>'),
        tokenizer=dict(
            padding_side='right',
            pretrained_model_name_or_path='/home/yanyonghao/work/projects/internlm2-chat-7b',
            trust_remote_code=True,
            type='transformers.AutoTokenizer.from_pretrained'),
        type='<function process_hf_dataset at 0x7f50950c1240>',
        use_varlen_attn=False),
    num_workers=0,
    sampler=dict(
        shuffle=True,
        type='mmengine.dataset.DefaultSampler'))
train_dataset=dict(
    dataset=dict(
        data_files=dict(
            train='/home/yanyonghao/work/projects/xtuner/data/personal_assistant.json'),
        path='json',
        type='datasets.load_dataset'),
    dataset_map_fn=None,
    max_length=512,
    pack_to_max_length=True,
    remove_unused_columns=True,
    shuffle_before_pack=True,
    template_map_fn=dict(
        template=dict(
            INSTRUCTION='<|im_start|>user\n{input}<|im_end|>\n<|im_start|>assistant\n',
            SEP='\n',
            STOP_WORDS=[
                '<|im_end|>',
                ],
            SUFFIX='<|im_end|>',
            SUFFIX_AS_EOS=True,
            SYSTEM='<|im_start|>system\n{system}<|im_end|>\n'),
        type='<function template_map_fn_factory at 0x7f50950c1750>'),
    tokenizer=dict(
        padding_side='right',
        pretrained_model_name_or_path='/home/yanyonghao/work/projects/internlm2-chat-7b',
        trust_remote_code=True,
        type='transformers.AutoTokenizer.from_pretrained'),
    type='<function process_hf_dataset at 0x7f50950c1240>',
    use_varlen_attn=False)
use_varlen_attn=False
visualizer=None
warmup_ratio=0.03
weight_decay=0
work_dir='./work_dirs/internlm2_chat_7b_qlora_oasst1_e3_copy'

**Comment by LZHgrla** [comment]
基于上述config，我这边是能够通过 mmengine/runner/runner.py", line 403 的执行的。

一个比较奇怪的点是，xtuner的函数都被解析成了类，而非LazyObject，如 `<class 'xtuner.engine.runner.loops.TrainLoop'>`

考虑是 xtuner 的安装问题。请列一下您的 xtuner 版本及所使用的训练命令。

```
python -c "import xtuner; print(xtuner.__version__)"
```

**Comment by xxg98** [comment]
> 基于上述config，我这边是能够通过 mmengine/runner/runner.py", line 403 的执行的，并不会报错。
> 
> 一个比较奇怪的点是，xtuner的函数都被解析成了动态的函数，而非LazyObject，如 `<class 'xtuner.engine.runner.loops.TrainLoop'>`
> 
> 考虑是 xtuner 的安装问题。请列一下您的 xtuner 版本及所使用的训练命令。
> 
> ```shell
> python -c "import xtuner; print(xtuner.__version__)"
> ```


在重新将整个流程走一遍后没有再出现这个问题，谢谢您的辛苦复现

**Comment by huer512** [comment]
我遇到了同样的问题，请问楼主是怎么解决的？

**Comment by ChencongZJU** [comment]
我也遇到了同样的问题，请问楼主怎么解决的
