### ISSUE TITLE
KeyError: 'Cache only has 0 layers, attempted to access layer with index 0'

### ISSUE THREAD

**Issue by xwwu2015** [InternLM/xtuner#405]
This is an old issue however the existing solution cannot work. The solution is to degrade the transformer version to 4.34.0, then the problem rises:

transformers-4.36.X will cause the issue, and 4.35.X, 4.34.1 are not accepted by the xtuner;
transformers-4.34.0 requires tokenizers < 2.15.0
tokenisers-2.14.X requires hugging face-hub < 1.94 
Xtuner requires datasets > 2.16.0
datasets-2.16.X requires hugging face-hub > 2.0.1

So which version can I use to run the llama model? any suggestion?

              i degrade transformers==4.34.0 and also re-install huggingface_hub==0.20.1 to solve this problem

_Originally posted by @rese1f in https://github.com/InternLM/xtuner/issues/290#issuecomment-1872659119_

**Comment by HIT-cwh** [comment]
We apologize for any inconvenience caused to your utilization. The issue has been resolved in [pr411](https://github.com/InternLM/xtuner/pull/411). To prevent further problems, we recommend installing the XTuner main branch in developer mode.
```
git clone https://github.com/InternLM/xtuner.git
cd xtuner
pip install -e '.[all]'
```
