### ISSUE TITLE
超大规模预训练

### ISSUE THREAD

**Issue by aries-young** [InternLM/xtuner#413]
请问 xtuner llava 是否支持超大规模的多模态预训练数据（1.5B），我这边发现 xtuner 训练时内存占用会持续增加，在训练几百 iter 后 oom（实验机子 2T cpu）

**Comment by LZHgrla** [comment]
Hi @aries-young 
我们在训练 llava-mix 数据时 （~600K），没有发现内存泄漏问题。

如果您在训练时内存不足（或泄漏），可以优先考虑检查数据读取的实现方式。
