### ISSUE TITLE
Support model sharding for training large models

### ISSUE THREAD

**Issue by phquang** [InternLM/xtuner#421]
How to perform model sharding to fully train the large language model?
I cannot run the llava with internlm2 chat 20B, finetuning all parameters configuration (https://github.com/InternLM/xtuner/blob/main/xtuner/configs/llava/internlm2_chat_20b_clip_vit_large_p14_336/finetune/llava_internlm2_chat_20b_clip_vit_large_p14_336_e1_gpu8_finetune.py) on a cluster of 8xA100, even with batch size 1 (without cpu offloading).

How can I do model sharding to scale to larger LLMs without CPU offloading?

**Comment by LZHgrla** [comment]
@phquang Hi!
Please use deepspeed zero, by `xtuner train XXX --deepspeed deepspeed_zero3`
