### ISSUE TITLE
如何指定卡来进行增量预训练？

### ISSUE THREAD

**Issue by 1518630367** [InternLM/xtuner#423]
例如想指定0-8卡中的4 5 6 三张卡进行训练

**Comment by HIT-cwh** [comment]
在训练的命令前加 CUDA_VISIBLE_DEVICES=4,5,6 这样呢

**Comment by 1518630367** [comment]
> 在训练的命令前加 CUDA_VISIBLE_DEVICES=4,5,6 这样呢

我尝试使用了 CUDA_VISIBLE_DEVICES=1,4,5,6 NPROC_PER_NODE=4 nohup  xtuner train config_huangtu_deepseek.py  --deepspeed  deepspeed_zero2 > output.log 2>&1 &，可是还是默认使用0，1，2，3这四张卡

**Comment by 1518630367** [comment]
> 在训练的命令前加 CUDA_VISIBLE_DEVICES=4,5,6 这样呢

好的 感谢
