### ISSUE TITLE
Add `Gemma` Model to xtuner.

### ISSUE THREAD

**Issue by PommesPeter** [InternLM/xtuner#427]
Google 刚公布了 Gemma 开源模型，请问有计划是否可以添加到 Xtuner，本人想为 xtuner 贡献 `Gemma` 相关配置和实现

huggingface: https://huggingface.co/google/gemma-7b
technical report: https://blog.google/technology/developers/gemma-open-models/

**Comment by pppppM** [comment]
十分欢迎！

XTuner 中添加 HF 格式的模型比较方便，可以参考这个 PR
https://github.com/InternLM/xtuner/pull/253

如果 Gemma 有特有的对话模板，需要根据这个文档，再添加一个 Gemma 的对话模板
https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/prompt_template.md

**Comment by PommesPeter** [comment]
> 十分欢迎！
> 
> XTuner 中添加 HF 格式的模型比较方便，可以参考这个 PR #253
> 
> 如果 Gemma 有特有的对话模板，需要根据这个文档，再添加一个 Gemma 的对话模板 https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/prompt_template.md

好的！

**Comment by LZHgrla** [comment]
@PommesPeter Hi

One more thing, 为减轻维护代价，计划新增的示例config可以参考这个：每个模型新增一个qlora config，一个全量微调 config即可。
https://github.com/InternLM/xtuner/tree/main/xtuner/configs/internlm/internlm2_1_8b

**Comment by PommesPeter** [comment]
> @PommesPeter Hi
> 
> One more thing, 为减轻维护代价，计划新增的示例config可以参考这个 https://github.com/InternLM/xtuner/tree/main/xtuner/configs/internlm/internlm2_1_8b
> 
> 即，每个模型新增一个qlora config，一个全量微调 config即可。

好的
