### ISSUE TITLE
LLaVA MME指标

### ISSUE THREAD

**Issue by KooSung** [InternLM/xtuner#428]
LLaVA的MME指标是不是不太对，我自己测出来的llava-internlm2-7b是1407
![image](https://github.com/InternLM/xtuner/assets/34935911/a23460d7-2732-4e5f-8bde-76175a153c68)
![image](https://github.com/InternLM/xtuner/assets/34935911/a8ff05b6-29e2-43ce-a6f6-43b06216da94)

**Comment by LZHgrla** [comment]
Hi @KooSung 
xtuner的README中张贴是 Perception + Reasoning 的总分。
1400+ 应该是 Perception 的分数
