### ISSUE TITLE
[Feature] 如果增量训练数据上亿条，如何加快处理速度，有没有离线处理的方式？

### ISSUE THREAD

**Issue by amulil** [InternLM/xtuner#443]
当前使用 `xtuner train` 处理上亿条数据，光第一个 map 可能需要十几个小时才能完成，每次训的时候会很慢，对于这种上亿级别的数据量，希望可以提供一个能离线处理的操作流程，这样每次训的时候直接读会快很多。

**Comment by HIT-cwh** [comment]
能否提供一条数据样例供我们调试下呢？

**Comment by pppppM** [comment]
@HIT-cwh 直接介绍一下如何离线处理数据应该就可以了吧，应该不需要样例数据吧

**Comment by amulil** [comment]
@HIT-cwh 

现在使用的数据是这样子的：
```python
# one sample data
{"text": "Two brothers from the Wingham area, diagnosed with a rare disease,..."}
```
然后 config 里面数据相关配置用的是：
```python
pretrain_data = dict(
    type=process_hf_dataset,
    dataset=dict(
        type=load_dataset, 
        path='json', 
        data_files=dict(train=pretrain_data)),
    tokenizer=tokenizer,
    max_length=max_length,
    dataset_map_fn=pretrain_map_fn,
    remove_unused_columns=True,
    shuffle_before_pack=True,
    pack_to_max_length=pack_to_max_length,
    use_varlen_attn=use_varlen_attn)

train_dataloader = dict(
    batch_size=batch_size,
    num_workers=dataloader_num_workers,
    dataset=pretrain_data,
    sampler=dict(type=DefaultSampler, shuffle=True),
    collate_fn=dict(type=default_collate_fn, use_varlen_attn=use_varlen_attn))
```

**Comment by HIT-cwh** [comment]
@amulil 刚刚完善了一下文档，您的这个情况可以参考下 [Offline.md](https://github.com/InternLM/xtuner/blob/a2b44fa507a351cf2954a9aa920f0328f9bdc221/docs/zh_cn/user_guides/custom_dataset/Offline.md) 这个文档。（目前文档还在不断完善，还没合入main分支）

文档中的前两步您这边已经做好了，直接执行 Step 3。命令为：
```
python xtuner/tools/process_untokenized_datasets.py  your_config_name.py \
    --save-folder /folder/to/save/processed/dataset
```
上述命令会在 `your_config_name.py` 同级目录下新建一个名为 `your_config_name_modified.py` 的配置文件，后续训练都要用这个新的 config。

因为数据预处理是一个 cpu 任务，所以用 slurm 调度系统的时候尽量申请尽可能多的 cpu。

另外，上述操作可能不会减少数据处理的耗时，但会得到一份离线处理好的数据，此后每次训练都可以直接读数据训练。

**Comment by amulil** [comment]
尝试了离线处理，没有发现问题，可以跑通整个流程。
