### ISSUE TITLE
关于gemma的template问题

### ISSUE THREAD

**Issue by pokerc** [InternLM/xtuner#453]
https://github.com/InternLM/xtuner/blob/770bac38bc905794eb38e53de4f54f98e30a77dc/xtuner/utils/templates.py#L128
你好，gemma chat的template是不是有些不对。system role对应的角色名为什么会是model呢？虽然官方的chat模型好像本身就没有使用system的角色来做指令微调。

**Comment by hhaAndroid** [comment]
非常感谢你的回复。通过 https://huggingface.co/google/gemma-7b-it 查看，确实是没有的，因为这个并不是 model 输出。我们会再次确认下
