### ISSUE TITLE
关于自定义图文数据微调

### ISSUE THREAD

**Issue by guikunchen** [InternLM/xtuner#455]
https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/custom_dataset/Online.md
这里面有些命令在版本0.1.14都报错了，【xtuner list-cfg -p custom_dataset】，【xtuner copy-cfg internlm2_7b_full_finetune_custom_dataset_e1 .】【xtuner list-dataset-format】

此外，custom_dataset/Online.md展示的对话格式里似乎不支持图像输入？
是否支持类似于这里的图文数据示例呢？https://github.com/InternLM/InternLM-XComposer/blob/main/finetune/README_zh-CN.md

**Comment by guikunchen** [comment]
> > https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/custom_dataset/Online.md 这里面有些命令在版本0.1.14都报错了，【xtuner list-cfg -p custom_dataset】，【xtuner copy-cfg internlm2_7b_full_finetune_custom_dataset_e1 .】【xtuner list-dataset-format】
> 
> @guikunchen 能提供下报错的日志么？

------
xtuner copy-cfg internlm2_7b_full_finetune_custom_dataset_e1 .
  File "lib/python3.9/site-packages/xtuner/tools/copy_cfg.py", line 21
    return f'{file_name}_copy{ext}'
                                  ^
SyntaxError: invalid syntax
------
xtuner list-cfg -p custom_dataset
  File "lib/python3.9/site-packages/xtuner/tools/list_cfg.py", line 20
    print(f'PATTERN: {args.pattern}')
                                   ^
SyntaxError: invalid syntax
------
xtuner list-dataset-format
03/08 13:47:41 - mmengine - WARNING - WARNING: command error!
03/08 13:47:41 - mmengine - WARNING - 
    Arguments received: ['xtuner', 'list-dataset-format']. xtuner commands use the following syntax:

        xtuner MODE MODE_ARGS ARGS

        Where   MODE (required) is one of ('list-cfg', 'copy-cfg', 'log-dataset', 'check-custom-dataset', 'train', 'test', 'chat', 'convert', 'preprocess', 'mmbench', 'eval_refcoco')

**Comment by pppppM** [comment]
> 此外，custom_dataset/Online.md展示的对话格式里似乎不支持图像输入？ 是否支持类似于这里的图文数据示例呢？https://github.com/InternLM/InternLM-XComposer/blob/main/finetune/README_zh-CN.md

custom_dataset/Online.md 主要针对的还是 sft 数据
多模态这部分我们目前是复用了 llava 的数据格式，可以参考
https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K

**Comment by guikunchen** [comment]
> > 此外，custom_dataset/Online.md展示的对话格式里似乎不支持图像输入？ 是否支持类似于这里的图文数据示例呢？https://github.com/InternLM/InternLM-XComposer/blob/main/finetune/README_zh-CN.md
> 
> custom_dataset/Online.md 主要针对的还是 sft 数据 多模态这部分我们目前是复用了 llava 的数据格式，可以参考 https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K

这个数据格式应该只支持一个序列包含一张图片:( 请问对于一个序列里包括多张图片的情况有支持吗？

**Comment by pppppM** [comment]
> > > 此外，custom_dataset/Online.md展示的对话格式里似乎不支持图像输入？ 是否支持类似于这里的图文数据示例呢？https://github.com/InternLM/InternLM-XComposer/blob/main/finetune/README_zh-CN.md
> > 
> > 
> > custom_dataset/Online.md 主要针对的还是 sft 数据 多模态这部分我们目前是复用了 llava 的数据格式，可以参考 https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K
> 
> 这个数据格式应该只支持一个序列包含一张图片:( 请问对于一个序列里包括多张图片的情况有支持吗？

@guikunchen 这个我们还在研发中，功能上和算法上都存在一些问题，现有的开源数据配合 llava 1.5这个版本，很难训练出有多图能力

**Comment by pppppM** [comment]
> > > https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/custom_dataset/Online.md 这里面有些命令在版本0.1.14都报错了，【xtuner list-cfg -p custom_dataset】，【xtuner copy-cfg internlm2_7b_full_finetune_custom_dataset_e1 .】【xtuner list-dataset-format】
> > 
> > 
> > @guikunchen 能提供下报错的日志么？
> 
> ## xtuner copy-cfg internlm2_7b_full_finetune_custom_dataset_e1 .
> File "lib/python3.9/site-packages/xtuner/tools/copy_cfg.py", line 21
> return f'{file_name}_copy{ext}'
> ^
> SyntaxError: invalid syntax
> ## xtuner list-cfg -p custom_dataset
> File "lib/python3.9/site-packages/xtuner/tools/list_cfg.py", line 20
> print(f'PATTERN: {args.pattern}')
> ^
> SyntaxError: invalid syntax
> xtuner list-dataset-format 03/08 13:47:41 - mmengine - WARNING - WARNING: command error! 03/08 13:47:41 - mmengine - WARNING - Arguments received: ['xtuner', 'list-dataset-format']. xtuner commands use the following syntax:
> 
> ```
>     xtuner MODE MODE_ARGS ARGS
> 
>     Where   MODE (required) is one of ('list-cfg', 'copy-cfg', 'log-dataset', 'check-custom-dataset', 'train', 'test', 'chat', 'convert', 'preprocess', 'mmbench', 'eval_refcoco')
> ```

@LZHgrla 有遇到过类似的情况么？

**Comment by LZHgrla** [comment]
> > > > https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/custom_dataset/Online.md 这里面有些命令在版本0.1.14都报错了，【xtuner list-cfg -p custom_dataset】，【xtuner copy-cfg internlm2_7b_full_finetune_custom_dataset_e1 .】【xtuner list-dataset-format】
> 
> > > 
> 
> > > 
> 
> > > @guikunchen 能提供下报错的日志么？
> 
> > 
> 
> > ## xtuner copy-cfg internlm2_7b_full_finetune_custom_dataset_e1 .
> 
> > File "lib/python3.9/site-packages/xtuner/tools/copy_cfg.py", line 21
> 
> > return f'{file_name}_copy{ext}'
> 
> > ^
> 
> > SyntaxError: invalid syntax
> 
> > ## xtuner list-cfg -p custom_dataset
> 
> > File "lib/python3.9/site-packages/xtuner/tools/list_cfg.py", line 20
> 
> > print(f'PATTERN: {args.pattern}')
> 
> > ^
> 
> > SyntaxError: invalid syntax
> 
> > xtuner list-dataset-format 03/08 13:47:41 - mmengine - WARNING - WARNING: command error! 03/08 13:47:41 - mmengine - WARNING - Arguments received: ['xtuner', 'list-dataset-format']. xtuner commands use the following syntax:
> 
> > 
> 
> > ```
> 
> >     xtuner MODE MODE_ARGS ARGS
> 
> > 
> 
> >     Where   MODE (required) is one of ('list-cfg', 'copy-cfg', 'log-dataset', 'check-custom-dataset', 'train', 'test', 'chat', 'convert', 'preprocess', 'mmbench', 'eval_refcoco')
> 
> > ```
> 
> 
> 
> @LZHgrla 有遇到过类似的情况么？

@guikunchen  报错有点奇怪，考虑重新安装一下xtuner？

**Comment by guikunchen** [comment]
好的，感谢～
