### ISSUE TITLE
KeyError: 'Column length not in the dataset. Current columns in the dataset: []'

### ISSUE THREAD

**Issue by Modas-Li** [InternLM/xtuner#465]
when using own dataset according to the instrution.
So where to write column length?

**Comment by LZHgrla** [comment]
@Modas-Li Hi
Could you please post your config and custom dataset format？

**Comment by LZHgrla** [comment]
Feel free to re-open this issue~

**Comment by Franklin-L** [comment]
> Feel free to re-open this issue~

我有类似的报错请问如何进行解决呀

![Image](https://github.com/user-attachments/assets/54cef4e8-73c2-4ede-8ec7-be3a4d779f55)我的自制数据集格式如下

![Image](https://github.com/user-attachments/assets/9b166c69-0683-4a4f-b560-98db30addac3)
