### ISSUE TITLE
数据template 的截断-- input和output想切分一下该去哪里改呢？

### ISSUE THREAD

**Issue by aiyinyuedejustin** [InternLM/xtuner#471]
大佬好！

我的自定义单轮对话 数据格式目前如下：

[{
    "conversation":[
        {
            "system": "请你xxxx",
            "input": "很长一段话",
            "output": "比input短的一段话"
        }
    ]
},
{
    "conversation":[
        {
            "system": "请你xxxx",
            "input": "很长一段话",
            "output": "比input短的一段话"
        }
    ]
}]

总的来说，我的"input" 会特别长，且每条input不等长。我想要微调mixtral 8x7b, 但如果按照模板拼接 sytemt+input+output 然后设置max_len,那这样很多数据的output部分可能就被截断了。如果把max_len设的特别大让他自己去padding，那计算量又太大。

所以我想采取一个**截断操作**，比如设置max_len = 13k, 每条conversation保留全部的output。 如果sytemt+input+output  总体比max_len大，那就截断input，使得总体不会超过max_len。

想请问我应该看哪个文件或者在哪里实现这个逻辑呢？

在使用xtuner之前，我是自己手撕的训练代码，然后再dataset.py中定义了一个class 去自定义截断的，使得output被全部保留，且不会超过max_len。

第一次用xtuner，功能都不错，也很集成，但不知道去哪里改了呜呜呜。

谢谢大佬！！！

**Comment by LZHgrla** [comment]
@aiyinyuedejustin Hi
数据的token化、截断是发生在

https://github.com/InternLM/xtuner/blob/a115e55e837b806708b1eb3ebb774fa5f943cc5d/xtuner/dataset/huggingface.py#L67-L85

具体实现在 `encode_fn` 中，可以在此自定义截断操作

https://github.com/InternLM/xtuner/blob/a115e55e837b806708b1eb3ebb774fa5f943cc5d/xtuner/dataset/utils.py#L36
