### ISSUE TITLE
在配置文件中尝试添加val_evaluator时，出现ModuleNotFoundError

### ISSUE THREAD

**Issue by GolfHotelSierra** [InternLM/xtuner#473]
### 问题描述
- 微调时使用的配置文件中，尝试添加 `val_evaluator` 时出现 `ModuleNotFoundError` 错误
> [mmengine文档中与 `val_evaluator` 相关的部分内容](https://mmengine.readthedocs.io/zh-cn/latest/tutorials/evaluation.html#id1)
- 配置文件 `internlm2_7b_qlora_CMDD_1_300_tmp.py`(来自于xtuner提供的`internlm2_7b_qlora_json_e3`，并进行了重命名和修改) 中相关的部分代码如下
```python
from util_tools.rouge4mmengine import Rouge4mmengine

val_evaluator = dict(
    type=Rouge4mmengine
)
```
- 文件结构如下，在 `internlm2_7b_qlora_CMDD_1_300_tmp.py` 中调用 `rouge4mmengine.py`
```text
|-- util_tools/
|   |-- __init__.py
|   |-- rouge4mmengine.py
|-- xtuner-cfg/
|   |-- internlm2_7b_qlora_CMDD_1_300_tmp/
|   |   |-- __init__.py
|   |   |-- internlm2_7b_qlora_CMDD_1_300_tmp.py
```

### 额外信息补充
- 完整的报错信息如下，
```
ModuleNotFoundError: Failed to import util_tools.rouge4mmengine in ./internlm2_7b_qlora_CMDD_1_300_tmp.py, line 30 for No module named 'util_tools'
```
- 完整的 `rouge4mmengine.py` 文件如下，
```python
from mmengine.evaluator import BaseMetric
from rouge_chinese import Rouge


class Rouge4mmengine(BaseMetric):
    def process(self, data_batch, data_samples):
        score, gt = data_samples
        print(f'score: {type(score)} = {score}')
        print(f'gt: {type(gt)} = {gt}')
        print("====================")


    def compute_metrics(self, results):
        return dict(rouge1=0.1, rouge2=0.3, rougel=0.5) # 仅用于流程测试，因此没有真正地计算验证集上的loss函数


if __name__ == '__main__':
    pass
```
以上代码参考 [mmengine官方文档中的Accuracy类](https://mmengine.readthedocs.io/zh-cn/latest/get_started/15_minutes.html#id3)
- 调整文件结构后进行了额外的测试，
调整后的文件结构如下，
```text
|-- xtuner-cfg/
|   |-- internlm2_7b_qlora_CMDD_1_300_tmp/
|   |   |-- __init__.py
|   |   |-- internlm2_7b_qlora_CMDD_1_300_tmp.py
|   |   |-- rouge4mmengine.py
```
配置文件中的 `import` 语句也进行了相应的调整，但是仍然出现了 `ModuleNotFoundError` 错误

### 预期的结果
- 请问错误是否是我对于 `xtuner` 框架提供的配置文件的修改产生的？或是 `mmengine` 中对 `val_evaluator` 有一些其它的要求？

**Comment by LZHgrla** [comment]
目前 mmengine 的 config 对 相对路径 python 库 的引用存在或多或少的限制，因此建议从源码安装 xtuner，再在 xtuner 库下进行自己的开发。

即，可以在 https://github.com/InternLM/xtuner/tree/main/xtuner/evaluation 中进行相关实现；同时，在实现自定义评测时，也可以参考 https://github.com/InternLM/xtuner/blob/main/xtuner/configs/internlm/internlm_7b/internlm_7b_qlora_oasst1_mmlu_e3.py 中对 MMLU 评测的实现

**Comment by GolfHotelSierra** [comment]
> 目前 mmengine 的 config 对 相对路径 python 库 的引用存在或多或少的限制，因此建议从源码安装 xtuner，再在 xtuner 库下进行自己的开发。
> 
> 即，可以在 https://github.com/InternLM/xtuner/tree/main/xtuner/evaluation 中进行相关实现；同时，在实现自定义评测时，也可以参考 https://github.com/InternLM/xtuner/blob/main/xtuner/configs/internlm/internlm_7b/internlm_7b_qlora_oasst1_mmlu_e3.py 中对 MMLU 评测的实现

@LZHgrla 好的，十分感谢您的回复
另外我也想询问一下，是否有mmengine对“python 库 的引用存在限制”相关的博客或文档等资源，我希望可以进一步了解一下这个问题，谢谢

**Comment by LZHgrla** [comment]
@GolfHotelSierra 
这里～
https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#a-pure-python-style-configuration-file-beta

**Comment by GolfHotelSierra** [comment]
> @GolfHotelSierra 这里～ https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#a-pure-python-style-configuration-file-beta

@LZHgrla 好的，感谢
