### ISSUE TITLE
LLava的文本处理，好像没有对齐

### ISSUE THREAD

**Issue by FDInSky** [InternLM/xtuner#478]
https://github.com/haotian-liu/LLaVA/blob/main/llava/train/train.py#L472
llava在这里减了2，没看到xtuner有这个操作，请问是哪里不一样吗？

**Comment by LZHgrla** [comment]
xtuner 有自己独立的数据处理逻辑，可以确保对数据的正确处理。

https://github.com/InternLM/xtuner/blob/3558f847cf8a647385086d1f5c5619e4d16fdef4/xtuner/dataset/utils.py#L36
