### ISSUE TITLE
咨询关于 FLOPs 的计算

### ISSUE THREAD

**Issue by wiryls** [InternLM/xtuner#479]
你好，感谢维护这样一个方便又强大的项目。

有个问题想要咨询一下。最近正在翻阅学习配置文件，我注意到有些配置启用了 [`ThroughputHook`](https://github.com/InternLM/xtuner/blob/164d383437930a13ad7184a9734d46a8082fed4b/xtuner/engine/hooks/throughput_hook.py#L59) 用于计算 tflops、tokens_per_sec：

https://github.com/InternLM/xtuner/blob/164d383437930a13ad7184a9734d46a8082fed4b/xtuner/configs/internlm/internlm2_chat_20b/internlm2_chat_20b_full_finetune_custom_dataset_e1.py#L154-L167

有的（llava）配置似乎特意没有加：

https://github.com/InternLM/xtuner/blob/164d383437930a13ad7184a9734d46a8082fed4b/xtuner/configs/llava/internlm2_chat_20b_clip_vit_large_p14_336/pretrain/llava_internlm2_chat_20b_clip_vit_large_p14_336_e1_gpu8_pretrain.py#L153-L164

因此想请教一下 ThroughputHook 的适用范围，后者的预训练能否用 `ThroughputHook` 统计 tflops、tokens_per_sec 数据呢？该如何判断呢？

> 我阅读了注释引用的论文的 APPENDIX: FLOATING-POINT OPERATIONS，但背景知识有限未能看懂是否适用

**Comment by HIT-cwh** [comment]
Hi! @wiryls 
ThroughputHook 统计得到的 TFlops 是一个理论估计值，详细的计算公式可以参考[这篇paper](https://deepakn94.github.io/assets/papers/megatron-sc21.pdf)附录中的解释。

理论上讲，llava和普通的语言模型一样，都是可以用 ThroughputHook 来统计 tflops、tokens_per_sec 的。
