### ISSUE TITLE
Support CohereForAI/c4ai-command-r-v01

### ISSUE THREAD

**Issue by choyakawa** [InternLM/xtuner#480]
It is almost llama, except: logits_scale and different DecoderLayer

see https://github.com/Lightning-AI/litgpt/issues/1089 https://github.com/ggerganov/llama.cpp/pull/6033

**Comment by LZHgrla** [comment]
@choyakawa  Hi

In my opinion, you can directly use `CohereForAI/c4ai-command-r-v01` in xtuner.

Just like the modification on https://github.com/InternLM/xtuner/pull/429

1. Apply `CohereForAI/c4ai-command-r-v01` in your config, that is `pretrained_model_name_or_path = 'CohereForAI/c4ai-command-r-v01'`

2. Expand the `PROMPT_TEMPLATE` according to the model and use it in your config, that is `prompt_template = PROMPT_TEMPLATE.xxx`

You can try it and if you encounter any problems, feel free to post them on this issue.
