### ISSUE TITLE
xtuner convert merge出现OOM！ 单卡a100

### ISSUE THREAD

**Issue by aiyinyuedejustin** [InternLM/xtuner#482]
<img width="2129" alt="image" src="https://github.com/InternLM/xtuner/assets/114650502/170f1344-08be-4db4-8f59-bbcd3a8c5450">

SFT的mixtral 8x7b

`
 xtuner convert merge /root/New/Mixtral-8x7B-Instruct-v0.1 /root/New/work_dirs/mixtral_8x7b_instruct_qlora_oasst1_e3_2/iter_4000_hf root/New/Mixtral-8x7B-Instruct-v0.1-tuned --max-shard-size 2GB
`
我从别的教程里找到了：

先运行

export MKL_SERVICE_FORCE_INTEL=1
export MKL_THREADING_LAYER='GNU'

然后我也用了--max-shard-size 2GB

在训练的时候都没有OOM想请问这个怎么解决呢

**Comment by pppppM** [comment]
@aiyinyuedejustin 命令中添加 --device cpu

训练时是用的 qlora ，所以显存够用
但 merge 时默认是在 gpu 上进行，此时加载的是模型全量参数，所以导致显存 OOM

**Comment by zxy1728** [comment]
请问解决了吗
