### ISSUE TITLE
[Bug] dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by rourouZ** [InternLM/xtuner#489]
命令：xtuner train internlm2_chat_7b_qlora_alpaca_e3
报错： mmengine - WARNING - WARNING: command error: 'dlopen: cannot load any more object with static TLS'!

xtuner version
- mmengine - INFO - 0.1.14

**Comment by LZHgrla** [comment]
@rourouZ 

系统环境应该有一些问题，可以尝试一下以下命令，看是否会报 `dlopen: cannot load any more object with static TLS` 错误

```
import torch
import cv2
```

如果会报错，应该需要重新搞一个新环境，并首先 **利用 conda（而非 pypi）** 安装好 pytorch，之后再安装 xtuner。 

1. 新建一个虚拟环境。
2. 使用 conda 安装 pytorch，可参考 [这里](https://pytorch.org/get-started/previous-versions/#v212)。注意版本需要 <=2.1.2。
3. 安装 xtuner。

**Comment by rourouZ** [comment]
> @rourouZ
> 
> 系统环境应该有一些问题，可以尝试一下以下命令，看是否会报 `dlopen: cannot load any more object with static TLS` 错误
> 
> ```
> import torch
> import cv2
> ```
> 
> 如果会报错，应该需要重新搞一个新环境，并首先 **利用 conda（而非 pypi）** 安装好 pytorch，之后再安装 xtuner。
> 
> 1. 新建一个虚拟环境。
> 2. 使用 conda 安装 pytorch，可参考 [这里](https://pytorch.org/get-started/previous-versions/#v212)。注意版本需要 <=2.1.2。
> 3. 安装 xtuner。

感谢，找到问题，import cv会报错，改变cv或xtuner版本均无法修复这个问题。目前的做法是在源码中注掉了cv库的导入，微调可以正常运行，但不知道会不会造成其他影响？

**Comment by LZHgrla** [comment]
@rourouZ 
xtuner 所使用的代码没有依赖opencv，所以只要不要涉及到其他库中opencv的代码就不会报错

**Comment by rourouZ** [comment]
> @rourouZ
> 
> 系统环境应该有一些问题，可以尝试一下以下命令，看是否会报 `dlopen: cannot load any more object with static TLS` 错误
> 
> ```
> import torch
> import cv2
> ```
> 
> 如果会报错，应该需要重新搞一个新环境，并首先 **利用 conda（而非 pypi）** 安装好 pytorch，之后再安装 xtuner。
> 
> 1. 新建一个虚拟环境。
> 2. 使用 conda 安装 pytorch，可参考 [这里](https://pytorch.org/get-started/previous-versions/#v212)。注意版本需要 <=2.1.2。
> 3. 安装 xtuner。

感谢，找到问题，import cv会报错，改变cv或xtuner版本均无法修复这个问题。目前的做法是在源码中注掉了cv库的导入，微调可以正常运行，但不知道会不会造成其他影响？
