### ISSUE TITLE
Can i finetune Qwen1.5-72B-Chat-GPTQ-Int4 model, and also convert&merge as a GPTQ-Int4 model directly?

### ISSUE THREAD

**Issue by iFe1er** [InternLM/xtuner#497]
Since I don't have enough resources to lora finetune a 72B model, I wonder if I can i finetune Qwen1.5-72B-Chat-GPTQ-Int4 model, and also convert&merge as a GPTQ-Int4 model directly?

**Comment by LZHgrla** [comment]
@iFe1er 
No, we cannot fine-tune the GPTQ models. 

If you don't have enough memory resources, you should consider using QLoRA, which also applies 4-bit quantization for LLM.

**Comment by iFe1er** [comment]
> @iFe1er No, we cannot fine-tune the GPTQ models.
> 
> If you don't have enough memory resources, you should consider using QLoRA, which also applies 4-bit quantization for LLM.

Thank you for the reply!  I already know that multiple GPUs is supported in xtuner, I have tried to QLoRA finetune a Qwen1.5-14B-Chat model on two 4090 (each 24GB).

my training command like:
NPROC_PER_NODE=2 xtuner train qwen1_5_14b_chat_qlora_myscript.py --deepspeed deepspeed_zero2_offload

However,  I notice that the GPU usages **is not halfed**  even i am using two gpus. 

So If i am going to QLoRA finetune a 72B model, i MUST use a single GPU with larger memory?   Can i stack more GPUs (for example 8 gpus) together to train a large model, but each gpu have only 24G memory? 
@LZHgrla

**Comment by LZHgrla** [comment]
@iFe1er  Hi!

Sorry for the delayed response.

> that the GPU usages is not halfed even i am using two gpus.

Yes, because the training is data parallel and each GPU has its own model.

> So If i am going to QLoRA finetune a 72B model, i MUST have at lease one single GPU with LARGE memory?

Yes, because QLoRA can only be compatible with zero2 and cannot use zero3.

> Can i stack more GPUs (for example 8 gpus) together to train a large model, but each gpu have small memory?

There's one solution: you can use LoRA instead of QLoRA, and then configure ZeRO3.
