### ISSUE TITLE
How to obtain the pretrained pth of llava_v15_7b?

### ISSUE THREAD

**Issue by zytx121** [InternLM/xtuner#500]
Due to the limitation of my GPUs, I want to fine-tune the pre-training weights. So, how to obtain the  './work_dirs/llava_v15_7b_pretrain/iter_2181.pth'? or can you provide an hf_to_pth script?

**Comment by zytx121** [comment]
Same problem with './work_dirs/llava_vicuna_7b_v15_clip_vit_large_p14_336_e1_gpu8_pretrain/iter_2181.pth'， './work_dirs/llava_internlm_chat_7b_clip_vit_large_p14_336_e1_gpu8_pretrain/iter_2181.pth'， './work_dirs/llava_internlm2_chat_7b_clip_vit_large_p14_336_e1_gpu8_pretrain/iter_2181.pth'

**Comment by zytx121** [comment]
Ok,  epoch_1 == iter_2181 here.

**Comment by dvishal485** [comment]
> Ok, epoch_1 == iter_2181 here.

Can you explain what you did to obtain the pretrain file? I also have limited GPU and wanted to fine-tune the pretrained weights.

I tried doing

```bash
xtuner train llava_v15_7b_pretrain --cfg-options train_cfg.max_epochs=1
```

but I keep getting out of GPU memory message `torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 93.06 MiB is free. Process 24707 has 14.65 GiB memory in use. Of the allocated memory 14.55 GiB is allocated by PyTorch, and 5.43 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`.

**Comment by yinglang** [comment]
try https://huggingface.co/xtuner/llava-internlm2-7b-pretrain/tree/main

**Comment by dvishal485** [comment]
> try https://huggingface.co/xtuner/llava-internlm2-7b-pretrain/tree/main

Thanks! Well, follow up is that I switched to a completely different model (PaliGemma 3b) and it worked perfectly for my use case. Smaller multi-modal models were not readily available just a few months back.
