### ISSUE TITLE
微调计算精度bf16 bfloat16

### ISSUE THREAD

**Issue by aiyinyuedejustin** [InternLM/xtuner#509]
<img width="762" alt="image" src="https://github.com/InternLM/xtuner/assets/114650502/fb886627-2f52-4e74-b79d-4014d2197a39">

您好，想请问一下，在使用qlora微调模型时，上图中默认的精度是fp16， 

如果用deepspeed zero2, 貌似会自动选择bf16或者fp16, 是根据我的显卡自动判断对吗？

但是deepspeed的bf16/fp16 跟这个qlora参数的fp16有关系吗？ 这两个是独立的吗？我需要把qlora这里改成bf16以获得更好的效果吗？

谢谢

**Comment by aiyinyuedejustin** [comment]
<img width="1178" alt="image" src="https://github.com/InternLM/xtuner/assets/114650502/c30b6c0f-9918-4ad8-9586-33cbe01aec8f">
另外optimizer这里貌似默认的也是float16? 这个位置可以改吗？还是也会自动选择bf16/fp16呢？ 我记得optimizer貌似fp32效果会好一些？

**Comment by LZHgrla** [comment]
@aiyinyuedejustin 
“如果用deepspeed zero2, 貌似会自动选择bf16或者fp16, 是根据我的显卡自动判断对吗？”
是的

“但是deepspeed的bf16/fp16 跟这个qlora参数的fp16有关系吗？ 这两个是独立的吗？我需要把qlora这里改成bf16以获得更好的效果吗？”
没有关系，该参数决定 `AutoModelForCausalLM.from_pretrained` 得到的 LLM，在之后 DeepSpeed 会对这个 LLM 的数据类型再次进行转换。因此，也不需要修改这个地方。

“optimizer这里貌似默认的也是float16? 这个位置可以改吗？”
使用 DeepSpeed 后，这个参数不会起作用，实际使用的 optimizer 为：
https://github.com/InternLM/xtuner/blob/59834032c82d39994c13252aea9b00011d1b2457/xtuner/tools/train.py#L312-L315
