### ISSUE TITLE
为什么回答的前半部分正确，后半段错误？

### ISSUE THREAD

**Issue by FDInSky** [InternLM/xtuner#523]
你好，
我做了llava-internlm2-7b的pretrain训练，但回答看起来有问题，请问什么原因？
这是完整的回答：
Two young people are walking on the beach and looking at a rock that has been found for them in which they can write their names with “I love you” written inside it\n&mdash; by iStock &tm;&copy;\n# ` # \' " "" ? ( ) , ! : ; * @ - _ + = && | [ ] \\^ $ % / . ** > <:?@=(-)$\n\n```\nimage is available via download.\n\nfile name:\n\n## description:\nThere\'s no better place than to get engagement photos taken near your favorite places or where he proposed! This couple wanted something unique so we set out onto an amazing coastal trail of San Diego.\nThis was done just before sunset during high tide along this hidden path towards Coronado Island’s North Beach known as The Spine...\n\nFor more information check my website below!\n- https://www.pictureswithlove.com/engagement/photoshoot/san-diego-sunset-beach-couple-shooting.html \n\nTo book please message me here from social media!\n\nThank You!! xo`"\n---\n\n### I\'m sorry
正确部分：
Two young people are walking on the beach and looking at a rock that has been found for them in which they can write their names with “I love you” written inside it\n
错误部分：
&mdash; by iStock &tm;&copy;\n# ` # \' " "" ? ( ) , ! : ; * @ - _ + = && | [ ] \\^ $ % / . ** > <:?@=(-)$\n\n```\nimage is available via download.\n\nfile name:\n\n## description:\nThere\'s no better place than to get engagement photos taken near your favorite places or where he proposed! This couple wanted something unique so we set out onto an amazing coastal trail of San Diego.\nThis was done just before sunset during high tide along this hidden path towards Coronado Island’s North Beach known as The Spine...\n\nFor more information check my website below!\n-

**Comment by LZHgrla** [comment]
@FDInSky 
张贴一下所使用的config？ 看起来是模型输出没有按照正常停止

**Comment by FDInSky** [comment]
推理时stop words没有设置好，改好了，多谢
