### ISSUE TITLE
Minimum GPU memory needed for fine-tuning LLaVA-v1.5?

### ISSUE THREAD

**Issue by dongyang2011** [InternLM/xtuner#526]
Hi there, I encountered a lack of GPU memory when attempting to fine-tune using the configuration of `llava_vicuna_13b_v15_qlora_clip_vit_large_p14_336_lora_e1_gpu8_finetune` on my 24GB RTX3090. What is the minimum memory requirement for this configuration?

I set `pretrained_pth` to `None` since I don't have the pretrained weights. I hope that is irrelevant to the error mentioned above.

**Comment by LZHgrla** [comment]
@dongyang2011 
HI! 24GB is not enough for llava fine-tuning. The minimum GPU memory requirement for 7B is 48GB, 13B is 80GB.

As the `pretrained_pth`, you can use the pretrained one from [here](https://huggingface.co/xtuner/llava-v1.5-13b-xtuner-pretrain/blob/main/epoch_1.pth).

**Comment by dongyang2011** [comment]
Thanks! However, the original [Llava](https://github.com/haotian-liu/LLaVA) can be finetuned using lora with relatively low mem requirement. 

> Use LoRA: [finetune_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_lora.sh). We are able to fit 13B training in 8-A100-40G/8-A6000, and 7B training in 8-RTX3090.

Will XTuner support configurations with such low memory soon?

**Comment by LZHgrla** [comment]
@dongyang2011 

XTuner already supports these features, but we need to modify some configs. I have added the LoRA fine-tuning configs on https://github.com/InternLM/xtuner/pull/536, and you can have a try.

Here are some tips.

1. Please use deepseed zero3 offload
    ```
    NPROC_PER_NODE=8 xtuner train $CONFIG --deepspeed deepspeed_zero3_offload
    ```
2. If the above command runs OOM, reduce the `batch_size` appropriately and scale up `accumulative_counts` proportionally. For example, `batch_size = 16; accumulative_counts = 1` or `batch_size =8; accumulative_counts = 2`

**Comment by dongyang2011** [comment]
Thanks, I will try it.
