### ISSUE TITLE
近期是否考虑支持llava 1.6 34B 的模型微调呢？

### ISSUE THREAD

**Issue by awzhgw** [InternLM/xtuner#549]
llava 1.6现在很火啊
近期是否考虑支持llava 1.6 34B 的模型微调呢？

**Comment by hhaAndroid** [comment]
这个 34b 模型微调是指的从头复现？还是指的加载他们的权重继续微调？

**Comment by awzhgw** [comment]
@hhaAndroid  加载他们的模型权重，继续微调哈。。

**Comment by awzhgw** [comment]
@hhaAndroid  什么时候支持： 加载https://huggingface.co/liuhaotian/llava-v1.6-34b 这个权重，进行微调呢？  @hhaAndroid

**Comment by hhaAndroid** [comment]
@awzhgw 感谢你的关注，这个我们接下来会支持，应该就这两个礼拜

**Comment by awzhgw** [comment]
@hhaAndroid  近期应该首先支持：llava 1.6 + llama3 8B 或者llava 1.6 +llama3 70B ..
