### ISSUE TITLE
如何正确的在py配置文件中引入自定义代码？

### ISSUE THREAD

**Issue by zodiacg** [InternLM/xtuner#550]
尝试在.py形式的配置文件中引入自定义的模型结构。但反复报错，不知正确的语法格式是什么？

目录结构：
```
project
├── custom_module
│      ├──__init__.py
│      └──vision.py # 一号位置
└──config
       ├──vision.py # 二号位置
       └──xtuner_config.py
```
在project目录下执行xtuner train config/xtuner_config.py。我尝试过：
1. 一号位置，用`from custom_module.vision import VisionModel`
2. 二号位置，用`from vision import VisionModel`
3. 二号位置，用`from .vision import VisionModel`
均不能正确引入。

请问正确的引入模块的方式是什么？

我理解应该是第三种，因为使用`with read_base():`尝试引入时至少正确找到了文件（当然read_base只能引入配置项不能引入定义……）

lazy import导致每次修改都需要预处理数据集，调试起来还挺麻烦的……

**Comment by hhaAndroid** [comment]
from project.custom_module.vision import VisionModel 才是对的
