### ISSUE TITLE
something wrong with mmengine

### ISSUE THREAD

**Issue by 52THANOS** [InternLM/xtuner#551]
![image](https://github.com/InternLM/xtuner/assets/117810189/b354f553-c0d4-4c95-9cf4-84f142cb6046)
![image](https://github.com/InternLM/xtuner/assets/117810189/02349c61-4520-467f-96f2-b062e154165f)

**Comment by LZHgrla** [comment]
Duplicated with https://github.com/InternLM/xtuner/issues/546
