### ISSUE TITLE
请问为什么执行微调chatglm3的时候报错AttributeError

### ISSUE THREAD

**Issue by Franklinlifangcheng** [InternLM/xtuner#561]
请问为什么执行微调的时候报错，我的数据集格式按照官方的修改了
![image](https://github.com/InternLM/xtuner/assets/146100070/49edde36-d9f5-415e-a610-93d62365edb9)

**Comment by LZHgrla** [comment]
@Franklinlifangcheng 
transformers 版本是多少？

**Comment by Franklinlifangcheng** [comment]
> transformers

是4.34.0

**Comment by LZHgrla** [comment]
4.34.0的transformers对于gradient checkpointing有一些 BC breaking。所以更新一下 transformers版本吧。

xtuner 推荐的版本是 
https://github.com/InternLM/xtuner/blob/bd6fe4c1dea7158dae333e39436b3cf1d7798646/requirements/runtime.txt#L25

**Comment by Franklinlifangcheng** [comment]
> 4.34.0的transformers对于gradient checkpointing有一些 BC breaking。所以更新一下 transformers版本吧。
> 
> xtuner 推荐的版本是
> 
> https://github.com/InternLM/xtuner/blob/bd6fe4c1dea7158dae333e39436b3cf1d7798646/requirements/runtime.txt#L25
老哥我更新完版本就报错了
![image](https://github.com/InternLM/xtuner/assets/146100070/7ee138bc-c56f-4a8a-8542-7b9ccc68150d)

**Comment by Franklinlifangcheng** [comment]
> 4.34.0的transformers对于gradient checkpointing有一些 BC breaking。所以更新一下 transformers版本吧。
> 
> xtuner 推荐的版本是
> 
> https://github.com/InternLM/xtuner/blob/bd6fe4c1dea7158dae333e39436b3cf1d7798646/requirements/runtime.txt#L25

我看工程里面的requirement要求的好像是这样
![image](https://github.com/InternLM/xtuner/assets/146100070/b9c33453-cc06-49e3-8b08-1ccb57d02dc7)

**Comment by LZHgrla** [comment]
xtuner用的是老版本吗？考虑用最新版的xtuner？

**Comment by Franklinlifangcheng** [comment]
> xtuner用的是老版本吗？考虑用最新版的xtuner？

可以的我换成新的就没有这个报错了但是我却显示GPU不足，24G的显存跑不了微调吗
![image](https://github.com/InternLM/xtuner/assets/146100070/a64de282-15a2-4ca7-aaa0-69a47dd4be4e)

**Comment by Franklinlifangcheng** [comment]
> xtuner用的是老版本吗？考虑用最新版的xtuner？
是不是选择的脚本不太对呀，下面的这些选择是有什么讲究吗
![image](https://github.com/InternLM/xtuner/assets/146100070/54312716-470b-4bc3-833c-1f2dee65146b)

**Comment by LZHgrla** [comment]
@Franklinlifangcheng 哪一个配置文件？ 以及启动命令是什么？

**Comment by Franklinlifangcheng** [comment]
> @Franklinlifangcheng 哪一个配置文件？ 以及启动命令是什么？

用这个复制的文件xtuner copy-cfg chatglm3_6b_base_qlora_alpaca_zh_e3  .
然后启动命令是xtuner train chatglm3_6b_base_qlora_alpaca_zh_e3_copy.py

**Comment by LZHgrla** [comment]
这张卡没有其他进程占用吗？

**Comment by Franklinlifangcheng** [comment]
> 这张卡没有其他进程占用吗？

没有哎我查看了一下占用情况
![image](https://github.com/InternLM/xtuner/assets/146100070/6b021b16-acdf-401a-9db2-755de8e9ba00)

**Comment by LZHgrla** [comment]
bitsandbytes版本是多少？

**Comment by Franklinlifangcheng** [comment]
> bitsandbytes版本是多少？

喔喔老哥我把那个maxlength缩小了就可以了
