### ISSUE TITLE
Xtuner 不启动训练，

### ISSUE THREAD

**Issue by hello-gary-2022** [InternLM/xtuner#566]
安装正常，没任何问题
硬件环境： 3050TI ， 基于docker image：nvcr.io/nvidia/pytorch:23.10-py ， torch version: 2.1.0a0+32f93b1
- opencv-python 版本：
pip show opencv-python
Name: opencv-python
Version: 4.9.0.80
Location: /usr/local/lib/python3.10/dist-packages
Required-by: mmengine

- 通过下面命令， xtuner 不启动训练  ， 只有warining，没有报错，但是也无法启动微调！
- /home/ws/finetune/llm/PsyAssistant/xtuner/qwen1_5_0_5b_chat_qlora.py 文件路径正确，可以正常打开

-----

运行如下命令：
root@9fc00d230ea3#xtuner train /home/ws/finetune/llm/PsyAssistant/xtuner/qwen1_5_0_5b_chat_qlora.py

04/14 13:05:29 - mmengine - WARNING - Use random port: 22344
[2024-04-14 13:05:36,744] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
04/14 13:05:37 - mmengine - WARNING - WARNING: command error: 'module 'cv2.dnn' has no attribute 'DictValue''!
04/14 13:05:37 - mmengine - WARNING -
    Arguments received: ['xtuner', 'train', '/home/ws/finetune/llm/PsyAssistant/xtuner/qwen1_5_0_5b_chat_qlora.py']. xtuner commands use the following syntax:

        xtuner MODE MODE_ARGS ARGS

        Where   MODE (required) is one of ('list-cfg', 'copy-cfg', 'log-dataset', 'check-custom-dataset', 'train', 'test', 'chat', 'convert', 'preprocess', 'mmbench', 'eval_refcoco')
                MODE_ARG (optional) is the argument for specific mode
                ARGS (optional) are the arguments for specific command

    Some usages for xtuner commands: (See more by using -h for specific command!)

        1. List all predefined configs:

**Comment by LZHgrla** [comment]
保存信息在log里：`04/14 13:05:37 - mmengine - WARNING - WARNING: command error: 'module 'cv2.dnn' has no attribute 'DictValue''!`

使用下列脚本应该能复现，然后解决一下环境的问题：

```python
import logging
import os
import random
import subprocess
import sys

from mmengine.logging import print_log

import xtuner
```

**Comment by hello-gary-2022** [comment]
确实是OpenCV版本的问题，但是并不是可以通过install很简单的升级就能解决，有计划提供一个DockerFile吗？ 或者一个docker镜像就像LMDelopy一样，这样就不会出现环境问题，方便xtuner的使用。

**Comment by FlyCarrot** [comment]
> 确实是OpenCV版本的问题，但是并不是可以通过install很简单的升级就能解决，有计划提供一个DockerFile吗？ 或者一个docker镜像就像LMDelopy一样，这样就不会出现环境问题，方便xtuner的使用。

请问这个问题是怎么解决的呢？同样出现了这个问题，尝试了opencv autofix，变成了新的报错
The 'opencv-python>=3' distribution was not found and is required by mmengine

**Comment by AlienceGG** [comment]
试下 pip install opencv-python-headless


> > 保存信息在log里：`04/14 13:05:37 - mmengine - WARNING - WARNING: command error: 'module 'cv2.dnn' has no attribute 'DictValue''!`
> > 使用下列脚本应该能复现，然后解决一下环境的问题：
> > ```python
> > import logging
> > import os
> > import random
> > import subprocess
> > import sys
> > 
> > from mmengine.logging import print_log
> > 
> > import xtuner
> > ```
> 
> 我按照这个方法没有复现，而且依然报错
