### ISSUE TITLE
请问各位大佬如何设置超参数来微调呢

### ISSUE THREAD

**Issue by Franklin-L** [InternLM/xtuner#570]
新人小白第一次接触大模型，请问各位前辈是怎么设置超参数来微调的呀，或者是如何进行调整的，有什么具体步骤吗，或者有什么评估手段可以实现不断调优呢

**Comment by LZHgrla** [comment]
@Franklinlifangcheng 

可以参考这个文档，在config对一些配置进行修改

https://xtuner.readthedocs.io/zh-cn/latest/training/modify_settings.html#id2
