### ISSUE TITLE
RuntimeError: probability tensor contains either inf, nan or element < 0

### ISSUE THREAD

**Issue by xmy0916** [InternLM/xtuner#573]
训练一百多个iters，loss nan了...有什么建议吗，模型用的internlm2，看了下loss是正常下降突然就nan的，数据集是自己的，感觉是数据问题或者float16的问题。

**Comment by LZHgrla** [comment]
降低学习率试一试。数据正常的话，即使是 fp16 训练应该也不会出现 NaN 的情况。如果想启动 bf16 训练，需确保机器支持 bf16（`torch.cuda.is_bf16_supported()`），并使用 `--deepspeed deepspeed_zero2` 来启动 deepspeed 训练。

**Comment by xmy0916** [comment]
> 降低学习率试一试。数据正常的话，即使是 fp16 训练应该也不会出现 NaN 的情况。如果想启动 bf16 训练，需确保机器支持 bf16（`torch.cuda.is_bf16_supported()`），并使用 `--deepspeed deepspeed_zero2` 来启动 deepspeed 训练。

感谢回复，今天重新训又正常了...感觉上就是float16的问题了，再出现我降低学习率试试
