### ISSUE TITLE
我该如何通过py文件调用模型问答?

### ISSUE THREAD

**Issue by tian969** [InternLM/xtuner#605]
如题, 看demo都是脚本样例, 直接xtuner chat就能回答, 现在本地已经部署好了, 请问我该如何在py文件中去调用模型进行回答? 比较疑惑这个xtuner的入口在哪里?

**Comment by LZHgrla** [comment]
@tian969 
入口的参考在这里 
https://github.com/InternLM/xtuner/blob/0e6241fa3c64df1928af33f7facf0bc22066c639/xtuner/entry_point.py#L210-L234

xtuner chat 对应 `https://github.com/InternLM/xtuner/blob/main/xtuner/tools/chat.py`

**Comment by tian969** [comment]
明白, 感谢您的解答!
