### ISSUE TITLE
requests版本冲突

### ISSUE THREAD

**Issue by JiBingdong** [InternLM/xtuner#606]
当我执行：
git clone -b v0.1.18 https://github.com/InternLM/XTuner
cd XTuner
pip install -e .
遇到requests的版本冲突：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchattacks 3.5.1 requires requests~=2.25.1, but you have requests 2.31.0 which is incompatible.
当我尝试直接安装requests=2.25.1时又遇到了其他包的版本冲突：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflic
ts.                                       
arxiv 2.1.0 requires requests==2.31.0, but you have requests 2.25.1 which is incompatible.                                                                                 
jupyterlab-server 2.27.1 requires requests>=2.31, but you have requests 2.25.1 which is incompatible.                                                                      
streamlit 1.33.0 requires requests<3,>=2.27, but you have requests 2.25.1 which is incompatible.                                                                           
tiktoken 0.6.0 requires requests>=2.26.0, but you have requests 2.25.1 which is incompatible.

**Comment by LZHgrla** [comment]
@JiBingdong 
torchattacks 库并非 xtuner 所依赖的，可以考虑卸载，或者新建一个 xtuner 专用的虚拟环境

**Comment by JiBingdong** [comment]
谢谢回复。我就是在conda内新建了一个专用的虚拟环境llama3，但是依然出现了版本冲突，似乎是现在的虚拟环境中的包与其他虚拟环境中的包产生了冲突，因为我发现包的安装路径都是在/home/ubuntu/.local/lib/python3.8/site-packages。我其实不太能理解这是为什么我是在虚拟环境中执行的命令，但是包的安装似乎是都在一个路径
