### ISSUE TITLE
请问作者使用LLAVA1.5-LLAMA3版本是否会存在问题是其他语言, 回答是中文的情况?

### ISSUE THREAD

**Issue by tian969** [InternLM/xtuner#612]
如题,我下载了权重, 自己构造数据集进行VQA, 发现它在进行部分回答时, 会回答中文. 问英文, 问日文, 都会有一定概率输出中文.请问这种现象正常嘛? 作者在测试时是否有发现? 下面这张是用in-the-wild评测时的结果. 左边我打印出来了具体的prompt_text, 右边是回答.
![image](https://github.com/InternLM/xtuner/assets/102512042/4aa37e2e-2798-4d45-be47-7682652453cb)

**Comment by LZHgrla** [comment]
我们没有进行具体的示例分析。但值得注意的是，llava-llama-3-8b 的训练数据为纯英文，而 llava-llama-3-8b-v1.1的指令微调数据中有大约12.5%的中文数据，有可能对此有影响。

您可以尝试评测一下 llava-llama-3-8b，看是否也会有类似的情况

**Comment by tian969** [comment]
是的 我用的是v1.1版本的, 那这样能说得通, 也可能是我自己改chat没改对, 毕竟我试demo中文对话蛮正常的. 感谢您的回答
