### ISSUE TITLE
请教一下训练时长如何做到这么短的?

### ISSUE THREAD

**Issue by tian969** [InternLM/xtuner#624]
我自己复现LLAVA v1.5-llama3, 在A800上, 用的原版训练超参数和脚本, 大概一阶段5h, 二阶段20h, 想请教您是如何缩短到两阶段11h的?

**Comment by tian969** [comment]
我看您的介绍, 参数基本上和原版保持一致, 除了VIT lora化了?

**Comment by hhaAndroid** [comment]
我们用的是 a100，应该是更快的吧
