### ISSUE TITLE
How to obtain the pretrained pth of llava-llama3-8b？

### ISSUE THREAD

**Issue by ciroimmobile** [InternLM/xtuner#639]
Could you please offer the finetuned pth link? I find that the pth have already converted to hf format? Could you please offer the hf_to_pth? Thanks

**Comment by LZHgrla** [comment]
Hi @ciroimmobile 
The .pth weight of llava-llama-3-8b-v1.1 is here

https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-pth
