### ISSUE TITLE
批量测试

### ISSUE THREAD

**Issue by zwhus** [InternLM/xtuner#645]
教程里提供了chat的方法，我现在想测试我自己的数据集的结果，请问有对应的多卡测试脚本吗

**Comment by LZHgrla** [comment]
目前没有，可以参考xtuner chat的实现，基于xtuner mmbench进行修改，其支持多卡评测

https://github.com/InternLM/xtuner/blob/main/xtuner/tools/mmbench.py

命令为 `torchrun --nnodes=1 --node_rank=0 --nproc_per_node=8 --master_addr=127.0.0.1 --master_port=29555 ./script.py xxxx --launcher pytorch`

**Comment by zwhus** [comment]
好的，已经解决

**Comment by syf-fgnb** [comment]
Hi @LZHgrla 
请问我根据自己的数据修改了mmbench之后，是使用chat的命令进行测试吗，比如
`xtuner chat internlm/internlm2-chat-7b --adapter xtuner/internlm2-chat-7b-qlora-oasst1 --prompt-template internlm2_chat`
还是说是用上述的命令
`torchrun --nnodes=1 --node_rank=0 --nproc_per_node=8 --master_addr=127.0.0.1 --master_port=29555 ./script.py xxxx --launcher pytorch`
如果是第二个，这里的./script.py xxxx 指的是什么呢
