### ISSUE TITLE
请问如何选择脚本呀

### ISSUE THREAD

**Issue by Franklin-L** [InternLM/xtuner#646]
这个脚本是指的用qlora的方式微调ChatGLM3吗
![image](https://github.com/InternLM/xtuner/assets/146100070/4841cc3d-d70b-4157-ac79-7b741527f2c8)

**Comment by LZHgrla** [comment]
@Franklin-L 

这个脚本对应到 https://github.com/InternLM/xtuner/blob/main/xtuner/configs/chatglm/chatglm3_6b_base/chatglm3_6b_base_qlora_alpaca_zh_e3.py

是利用qlora在alpaca_zh数据上微调chatglm3-6b-base。

脚本选择的话，一般看自己需求（数据需求、模型需求、微调配置需求等等），基于所提供的config进行自定义修改。

**Comment by Franklin-L** [comment]
> @Franklin-L
> 
> 这个脚本对应到 https://github.com/InternLM/xtuner/blob/main/xtuner/configs/chatglm/chatglm3_6b_base/chatglm3_6b_base_qlora_alpaca_zh_e3.py
> 
> 是利用qlora在alpaca_zh数据上微调chatglm3-6b-base。
> 
> 脚本选择的话，一般看自己需求（数据需求、模型需求、微调配置需求等等），基于所提供的config进行自定义修改。

嗷嗷前辈我刚刚把脚本丢给gpt问了一下为什么它说是lora而非qlora呢
![image](https://github.com/InternLM/xtuner/assets/146100070/2f6c19c7-3b33-4636-8f0d-e8723e6ec293)
下面这地方是不是做了量化处理所以应该是qlora呀
![image](https://github.com/InternLM/xtuner/assets/146100070/f13969e8-6f45-4585-a708-ee0400dee0bd)

**Comment by LZHgrla** [comment]
@Franklin-L 是的，是QLoRA

**Comment by Franklin-L** [comment]
> @Franklin-L 是的，是QLoRA

前辈请问是不是可以修改成qlora啊，这个量化之后会减少内存占用，但是会不会造成效果没有lora好哇，这个你们有没有测试过呀

**Comment by Franklin-L** [comment]
> @Franklin-L 是的，是QLoRA

嗷嗷好的，qlora量化之后会不会造成效果没有不量化的lora效果好啊，这个你们有没有测试过呀

**Comment by LZHgrla** [comment]
@Franklin-L 
最好还是lora，qlora的量化还是有一定的误差的。具体的没有定量的差距比较。

**Comment by Franklin-L** [comment]
> @Franklin-L 最好还是lora，qlora的量化还是有一定的误差的。具体的没有定量的差距比较。

我看关于chatglm3的脚本好像都是qlora的，是不是直接改那个对量化的配置就可以变成lora了啊

**Comment by LZHgrla** [comment]
> > @Franklin-L 最好还是lora，qlora的量化还是有一定的误差的。具体的没有定量的差距比较。
> 
> 我看关于chatglm3的脚本好像都是qlora的，是不是直接改那个对量化的配置就可以变成lora了啊

是的，量化的配置删掉或者设为None就可以

**Comment by Franklin-L** [comment]
> > > @Franklin-L 最好还是lora，qlora的量化还是有一定的误差的。具体的没有定量的差距比较。
> > 
> > 
> > 我看关于chatglm3的脚本好像都是qlora的，是不是直接改那个对量化的配置就可以变成lora了啊
> 
> 是的，量化的配置删掉或者设为None就可以
请问我把quantitity_config直接删掉了，执行微调会报错是为什么呀，不能直接删掉吗

**Comment by LZHgrla** [comment]
@Franklin-L 什么错误？

**Comment by Franklin-L** [comment]
> @Franklin-L 什么错误？

**Comment by LZHgrla** [comment]
@Franklin-L 
没加逗号？ 你的config有语法错误

**Comment by Franklin-L** [comment]
> @Franklin-L 没加逗号？ 你的config有语法错误

好奇怪我只是把那个quantitity_config给注释了呀

**Comment by Franklin-L** [comment]
> @Franklin-L 没加逗号？ 你的config有语法错误
前辈我把量化的内容去除了，要求的显存会很大吗，我是24G的显存量化的时候可以跑不量化会报错显存不够，我开了俩张卡48G
用多卡微调也会爆粗不够这是为什么啊，需要多大呀
