### ISSUE TITLE
请问如何将微调后的模型合并输出.safetensors格式的文件呀

### ISSUE THREAD

**Issue by Franklin-L** [InternLM/xtuner#647]
我在导出ChatGLM3的合并模型时候发现导出是7个bin文件请问如何导出为safetensors文件呢

**Comment by LZHgrla** [comment]
@Franklin-L 
配合这个PR的修改 https://github.com/InternLM/xtuner/pull/648 ，使用 `--safe-serialization` 可以允许 safetensors 的导出

**Comment by Franklin-L** [comment]
> @Franklin-L 配合这个PR的修改 #648 ，使用 `--safe-serialization` 可以允许 safetensors 的导出

请问我更改了这俩个脚本为什么输出的还是bin文件格式啊，是需要重新训练模型吗
![image](https://github.com/InternLM/xtuner/assets/146100070/3829936b-2429-4a75-b821-1fe5068d02b3)
我执行的是这俩个指令
![image](https://github.com/InternLM/xtuner/assets/146100070/b5d1467b-27b2-4a33-a2c2-47f7e8d6cbe8)

**Comment by LZHgrla** [comment]
@Franklin-L 

命令增加参数 --safe-serialization

**Comment by Franklin-L** [comment]
> --safe-serialization

嗷嗷加上指令确实可以了谢谢，那我把脚本修改了应该没事吧

**Comment by LZHgrla** [comment]
> > --safe-serialization
> 
> 
> 
> 嗷嗷加上指令确实可以了谢谢，那我把脚本修改了应该没事吧

可以的～没问题！
