### ISSUE TITLE
LoRA for llava llama-3

### ISSUE THREAD

**Issue by nicolas-dufour** [InternLM/xtuner#649]
Hi,
I see that the Llava model is trained with full finetuning of the LLM.
Did you do the ablation using LoRAs?
If so do you have a version with LoRA instead of full finetuning?

Thanks!

**Comment by hhaAndroid** [comment]
@nicolas-dufour Thank you for your clarification. We didn't use LORA to train the LLM because the model size was small. Instead, we directly fine-tuned the model on the full dataset.

**Comment by nicolas-dufour** [comment]
@hhaAndroid thanks for the clarification!

I think using a Lora can still improve performance even if it fits in memory!

The recent Idefics2 paper show they achieve better perf with a LoRA than with full fine-tuning!

https://arxiv.org/abs/2405.02246

**Comment by hhaAndroid** [comment]
@nicolas-dufour I'm curious, would LoRa really perform better if we have more training data? Maybe we can try it later.

**Comment by nicolas-dufour** [comment]
> @nicolas-dufour I'm curious, would LoRa really perform better if we have more training data? Maybe we can try it later.

According to this paper they argue that Lora stabilize training facilitating optimization. They do use quite a lot of data on their side as well
