### ISSUE TITLE
请问为什么用 xtuner工具微调后输出的模型文件无法转换成onnx模型

### ISSUE THREAD

**Issue by Franklin-L** [InternLM/xtuner#650]
我之前用官方的微调方式然后将微调后的参数合并到原来的模型后输出safetensors格式文件，然后最近我开始尝试xtuner框架进行微调，输出bin文件后我尝试转换成onnx格式发现报错aten::scaled_dot_product_attention，我以为是因为bin文件格式问题，所以我就输出safetensors格式文件发现依然是这个报错，求助各位大佬这是因为什么呀，是因为xtuner微调框架有什么不能兼容的地方吗

**Comment by LZHgrla** [comment]
@Franklin-L 
xtuner微调后得到的模型就是一个正常的transformers的LLM，与初始的LLM一致。
导出onnx的话，与是否微调应该无关，可以检查一下导出工具是否支持LLM的导出。

**Comment by Franklin-L** [comment]
> @Franklin-L xtuner微调后得到的模型就是一个正常的transformers的LLM，与初始的LLM一致。 导出onnx的话，与是否微调应该无关，可以检查一下导出工具是否支持LLM的导出。

我们尝试过导出初始未微调的ChatGLM3和用官方的微调方法后的模型，这俩种情况都可以导出onnx，导出的工具应该是可以支持的，就是编写了一个导出onnx的脚本

**Comment by LZHgrla** [comment]
@Franklin-L 
未微调的chatglm3和xtuner微调后的chatglm3在文件上有何异同嘛？

**Comment by Franklin-L** [comment]
> @Franklin-L 未微调的chatglm3和xtuner微调后的chatglm3在文件上有何异同嘛？

![image](https://github.com/InternLM/xtuner/assets/146100070/654b894d-b04d-4592-b4fe-63783a0c3a04)
这是用xtuner微调后的下面是没有微调的
![image](https://github.com/InternLM/xtuner/assets/146100070/799b8436-64ae-4795-a7ed-5c4c0cf441d1)
对照了一下有一点区别，但是我们在转换onnx的时候只需要那七个大的safetensors文件

**Comment by LZHgrla** [comment]
可以尝试将 modeling_chatglm.py, configuration_chatglm.py 替换为未微调的版本再尝试一下。

**Comment by Franklin-L** [comment]
> @Franklin-L 未微调的chatglm3和xtuner微调后的chatglm3在文件上有何异同嘛？

然后我们用的是下面的脚本将官方微调后输出的lora参数和原始模型进行合并输出的新的safetensors文件，只不过用这个脚本只会输出三个而不是七个，但是这种办法输出的竟然是可以转换onnx不会报错的
![image](https://github.com/InternLM/xtuner/assets/146100070/745c2073-cfc8-4abe-a303-3b417ff2b8c3)

**Comment by LZHgrla** [comment]
@Franklin-L 
那可以尝试用这个脚本来merge xtuner微调出的adapter？保存个数不会有影响，不会影响实际参数和模型架构。

**Comment by Franklin-L** [comment]
> @Franklin-L 那可以尝试用这个脚本来merge xtuner微调出的adapter？保存个数不会有影响，不会影响实际参数和模型架构。

这个脚本是直接将官方微调输出的checkpoint一步直接输出成新的模型文件了，xtuner是先把pth变成adapter然后再merge adapter，我如果想用这个脚本来导出xtuner微调后的模型是应该加在哪个步骤啊，merge xtuner微调出的adapter吗？

**Comment by LZHgrla** [comment]
@Franklin-L  
是的

**Comment by Franklin-L** [comment]
> @Franklin-L 是的

之前是用的这个指令，要找到对应的checkpoint，那我如果是操作adapter的话就是把checkpoints换成adapter的safetensors吗
![image](https://github.com/InternLM/xtuner/assets/146100070/84798896-17dd-464a-8cf1-b4c784bdbd82)

**Comment by Franklin-L** [comment]
> 可以参考xtuner的merge，对两个脚本进行对齐、合并
> 
> https://github.com/InternLM/xtuner/blob/main/xtuner/tools/model_converters/merge.py

我修改了好像有很多问题，我在想xtuner框架微调可以输出checkpoints格式的文件来保存模型状态吗，这样就可以直接应用之前的脚本合并了

**Comment by Franklin-L** [comment]
> 可以参考xtuner的merge，对两个脚本进行对齐、合并
> 
> https://github.com/InternLM/xtuner/blob/main/xtuner/tools/model_converters/merge.py

好的终于解决了谢谢前辈
