### ISSUE TITLE
如何查看支持什么模型呢？

### ISSUE THREAD

**Issue by fxb392** [InternLM/xtuner#653]

**Comment by HIT-cwh** [comment]
可以通过 ``xtuner list-cfg`` 命令来查看我们支持的所有 config name，其中 config name 的前缀就是模型名称。
例如 ``internlm2_7b_qlora_alpaca_e3`` 表示使用qlora算法在alpaca数据集上微调 Internlm2 模型 3 个 epoch 的配置文件。

**Comment by fxb392** [comment]
好的，感谢您！
