### ISSUE TITLE
运行llava-llama-3-8b-v1_1报错：FileNotFoundError: can't find *_optim_states.pt files in directory

### ISSUE THREAD

**Issue by Egber1t** [InternLM/xtuner#674]
微调时，已经生成work dirs。但是最后报错：
    raise FileNotFoundError(f"can't find {glob_pattern} files in directory '{checkpoint_dir}'")
FileNotFoundError: can't find *_optim_states.pt files in directory '/root/autodl-tmp/llava-llama-3-8b-v1_1'

config设置为
llm_name_or_path = '/root/autodl-tmp/Meta-Llama-3-8B-Instruct'
visual_encoder_name_or_path = '/root/autodl-tmp/clip-vit-large-patch14-336'
# Specify the pretrained pth
pretrained_pth = '/root/autodl-tmp/llava-llama-3-8b-v1_1'  # noqa: E501

求解答谢谢

**Comment by hhaAndroid** [comment]
@Egber1t https://github.com/InternLM/xtuner/issues/671

**Comment by Egber1t** [comment]
为啥这里指向phi呢（好奇）

**Comment by Egber1t** [comment]
已解决需要更换成：
https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-pth

**Comment by Liu98C** [comment]
> 已解决需要更换成： https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-pth
你好，为什么我更换后还是报错。
    raise FileNotFoundError(f"can't find {glob_pattern} files in directory '{checkpoint_dir}'")
FileNotFoundError: can't find *_optim_states.pt files in directory '/home/bit118/Liucheng/model/llava-llama-3-8b-v1_1-pth'
