### ISSUE TITLE
warning on CUTLASS&sparse_attn&triton

### ISSUE THREAD

**Issue by shockjiang** [InternLM/xtuner#676]
hi, after I created the conda env, I run the experiments, I met the follwoing warning. I wonder does this affect my training and final result.

thx.

<img width="751" alt="image" src="https://github.com/InternLM/xtuner/assets/1284499/16f77a79-08ad-4fb6-be1b-775f40a7b8d1">

**Comment by pppppM** [comment]
It won't affect anything, this is a warning from the new version of PyTorch and Triton
