### ISSUE TITLE
求助max_epochs 的问题

### ISSUE THREAD

**Issue by Franklin-L** [InternLM/xtuner#677]
请问我在训练模型的时候，我想分别测试epoch为5和10的效果，可以只训练为10的时候吗，就是epoch为10是不是能包含5的情况呀，输出的权重文件是不是有对应5的时候

**Comment by LZHgrla** [comment]
不可以的，因为max epochs会影响默认的cosine lr scheduler，导致不同max epochs设定下同一epoch的训练不是等价的。

**Comment by Franklin-L** [comment]
> 不可以的，因为max epochs会影响默认的cosine lr scheduler，导致不同max epochs设定下同一epoch的训练不是等价的。

前辈请问不量化单纯lora需要多大的显存呀，微调chatglm3
