### ISSUE TITLE
log输出中的time的意思

### ISSUE THREAD

**Issue by shockjiang** [InternLM/xtuner#687]
log输出：
```
eta: 0:00:03  time: 0.0768  data_time: 0.0137  memory: 9806
```
其中time & data_time 分别是什么意思？是否包含梯度回传的时间？
memory的单位是什么？

谢谢

**Comment by HIT-cwh** [comment]
time表示前传 + 反传 + 参数更新（如果当前iter需要）的总时间
data_time表示读取训练数据所需时间
memory的单位是MB

**Comment by shockjiang** [comment]
谢谢。
是指rank=0的GPU设备上，整个batch的时间，对吗？

**Comment by hhaAndroid** [comment]
> 谢谢。 是指rank=0的GPU设备上，整个batch的时间，对吗？

对
