### ISSUE TITLE
长序列训练的疑惑？

### ISSUE THREAD

**Issue by RyanOvO** [InternLM/xtuner#703]
internlm2的上下文也可以达到200k，长序列训练基准的模型怎么不放一下internlm2的数据，全是Yi、Llama2？

**Comment by HIT-cwh** [comment]
XTuner 实现的序列并行方法同样适用于 InternLM2 等其他模型。支持序列并行训练的模型如下所示。如果您有兴趣，欢迎对 InternLM2 的长上下文训练效率进行测速。
![image](https://github.com/InternLM/xtuner/assets/41630003/9f38f372-1a16-44e4-a314-7bf7cbe7b357)
