### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement mpi4py-mpich (from xtuner[all]) (from versions: none)

### ISSUE THREAD

**Issue by eugine5** [InternLM/xtuner#704]
Hi All, 

I am trying to follow the quick start installation and once I follow the steps, I see the error as below. 

This is the full error : 
(xtuner-env) yoojinchoi@Yoos-MacBook-Pro xtuner % pip install -e '.[all]'            
Obtaining file:///Users/yoojinchoi/Desktop/Yoo%20Jin%20Choi/python/xtuner
  Preparing metadata (setup.py) ... done
Requirement already satisfied: bitsandbytes>=0.40.0.post4 in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (0.42.0)
Requirement already satisfied: datasets>=2.16.0 in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (2.19.1)
Requirement already satisfied: einops in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (0.8.0)
Requirement already satisfied: lagent>=0.1.2 in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (0.2.2)
Requirement already satisfied: mmengine>=0.10.3 in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (0.10.4)
Requirement already satisfied: openpyxl in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (3.1.2)
Requirement already satisfied: peft>=0.4.0 in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (0.11.1)
Requirement already satisfied: scikit-image in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (0.23.2)
Requirement already satisfied: scipy in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (1.13.0)
Requirement already satisfied: SentencePiece in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (0.2.0)
Requirement already satisfied: tiktoken in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (0.7.0)
Requirement already satisfied: torch in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (2.3.0)
Requirement already satisfied: torchvision in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (0.18.0)
Requirement already satisfied: transformers!=4.38.0,!=4.38.1,!=4.38.2,>=4.36.0 in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (4.41.0)
Requirement already satisfied: transformers_stream_generator in /Users/yoojinchoi/miniforge3/envs/xtuner-env/lib/python3.10/site-packages (from xtuner==0.1.19) (0.0.5)
Collecting deepspeed>=0.12.3 (from xtuner==0.1.19)
  Using cached deepspeed-0.14.2.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of xtuner[all] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement mpi4py-mpich (from xtuner[all]) (from versions: none)
ERROR: No matching distribution found for mpi4py-mpich

this is the command that I ran: 

conda create --name xtuner-env mpi4py python=3.10 -y
  529  conda activate xtuner-env
  530  pip install -U xtuner
  531  git clone https://github.com/InternLM/xtuner.git
  532  cd xtuner
  533  pip install -e '.[all]'
  534  conda install conda-forge::py-cpuinfo
  535  pip install -e '.[all]'
  536  conda install conda-forge::pydantic
  537  pip install -e '.[all]'

I also ran 'brew install mpi4py'
but none of these are working. Can someone please help me on this? 
Please let  me know any further details needed.

**Comment by pppppM** [comment]
Currently, XTuner only supports NVIDIA devices and does not support the Mac system. @eugine5

**Comment by eugine5** [comment]
gotcha, I will test it out with the NVIDIA devices. Thank you @pppppM !!
