### ISSUE TITLE
OSError: We couldn't connect to 'https://huggingface.co' to load this file

### ISSUE THREAD

**Issue by Artist2001** [InternLM/xtuner#710]
Traceback (most recent call last):
  File "/root/autodl-tmp/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 168, in <module>
    main()
  File "/root/autodl-tmp/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 81, in main
    model = BUILDER.build(cfg.model)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/autodl-tmp/xtuner/xtuner/model/sft.py", line 84, in __init__
    llm = self._dispatch_lm_model_cfg(llm, max_position_embeddings)
  File "/root/autodl-tmp/xtuner/xtuner/model/sft.py", line 224, in _dispatch_lm_model_cfg
    llm_cfg = AutoConfig.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 934, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/hub.py", line 442, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like ZhipuAI/chatglm3-6b is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
在将pth文件转换成hf形式时出现此报错，请问可能是什么原因

**Comment by LZHgrla** [comment]
@Artist2001 
ZhipuAI/chatglm3-6b 不是有效的huggingface model id，正确的应该是 THUDM/chatglm3-6b（https://huggingface.co/THUDM/chatglm3-6b）

同时，如果已经下载到本地，也可以直接将该参数设置为本地的模型路径

**Comment by Artist2001** [comment]
你好，我的模型是下载到本地服务器的路径，THUDM/chatglm3-6b是这个路径






道阻且长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "InternLM/xtuner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月21日(星期二) 下午2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [InternLM/xtuner] OSError: We couldn't connect to 'https://huggingface.co' to load this file (Issue #710)





 
@Artist2001
 ZhipuAI/chatglm3-6b 不是有效的huggingface model id，正确的应该是 THUDM/chatglm3-6b（https://huggingface.co/THUDM/chatglm3-6b）
 
同时，如果已经下载到本地，也可以直接将该参数设置为本地的模型路径

**Comment by LZHgrla** [comment]
你所使用的命令是什么？

**Comment by Artist2001** [comment]
xtuner convert pth_to_hf chatglm3_0520/chatglm3_6b_base_qlora_alpaca_zh_e3_copy.py chatglm3_0520/iter_39885.pth chatglm_hf1/是这一个




道阻且长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "InternLM/xtuner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月21日(星期二) 下午2:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [InternLM/xtuner] OSError: We couldn't connect to 'https://huggingface.co' to load this file (Issue #710)





 
你所使用的命令是什么？

**Comment by LZHgrla** [comment]
config中使用了ZhipuAI/chatglm3-6b吗？

**Comment by Artist2001** [comment]
是有使用的







道阻且长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "InternLM/xtuner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月21日(星期二) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [InternLM/xtuner] OSError: We couldn't connect to 'https://huggingface.co' to load this file (Issue #710)





 
config中使用了ZhipuAI/chatglm3-6b吗？

**Comment by LZHgrla** [comment]
这就是问题所在，你用的ZhipuAI/chatglm3-6b不是一个huggingface model id

**Comment by Artist2001** [comment]
请问应该如何解决呢，我训练能生成pth文件但是，转换不了hf文件

道阻且长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "InternLM/xtuner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月21日(星期二) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [InternLM/xtuner] OSError: We couldn't connect to 'https://huggingface.co' to load this file (Issue #710)





 
这就是问题所在，你用的ZhipuAI/chatglm3-6b不是一个huggingface model id

**Comment by LZHgrla** [comment]
现在这个config应该也无法训练？pth_to_hf和train初始化模型的逻辑是一样的

**Comment by LZHgrla** [comment]
你需要在config的 pretrained_model_name_or_path 指定一个huggingface 的model id（如THUDM/chatglm3-6b），或者一个本地的模型存储路径

**Comment by Artist2001** [comment]
拿一个刚刚训练保存的小的pth文件进行转换时仍然报错
Traceback (most recent call last):
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1722, in _get_metadata_or_catch_error
&nbsp; &nbsp; metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
&nbsp; &nbsp; return fn(*args, **kwargs)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1645, in get_hf_file_metadata
&nbsp; &nbsp; r = _request_wrapper(
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 372, in _request_wrapper
&nbsp; &nbsp; response = _request_wrapper(
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 395, in _request_wrapper
&nbsp; &nbsp; response = get_session().request(method=method, url=url, **params)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
&nbsp; &nbsp; resp = self.send(prep, **send_kwargs)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
&nbsp; &nbsp; r = adapter.send(request, **kwargs)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 66, in send
&nbsp; &nbsp; return super().send(request, *args, **kwargs)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
&nbsp; &nbsp; raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /ZhipuAI/chatglm3-6b/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efb435f7460&gt;, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 2821fe50-b3bb-436a-9828-d18c7b1dde01)')


The above exception was the direct cause of the following exception:


Traceback (most recent call last):
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/hub.py", line 399, in cached_file
&nbsp; &nbsp; resolved_file = hf_hub_download(
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
&nbsp; &nbsp; return fn(*args, **kwargs)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
&nbsp; &nbsp; return _hf_hub_download_to_cache_dir(
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1325, in _hf_hub_download_to_cache_dir
&nbsp; &nbsp; _raise_on_head_call_error(head_call_error, force_download, local_files_only)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1826, in _raise_on_head_call_error
&nbsp; &nbsp; raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.


The above exception was the direct cause of the following exception:


Traceback (most recent call last):
&nbsp; File "/root/autodl-tmp/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 168, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "/root/autodl-tmp/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 81, in main
&nbsp; &nbsp; model = BUILDER.build(cfg.model)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
&nbsp; &nbsp; return self.build_func(cfg, *args, **kwargs, registry=self)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
&nbsp; &nbsp; obj = obj_cls(**args)&nbsp; # type: ignore
&nbsp; File "/root/autodl-tmp/xtuner/xtuner/model/sft.py", line 84, in __init__
&nbsp; &nbsp; llm = self._dispatch_lm_model_cfg(llm, max_position_embeddings)
&nbsp; File "/root/autodl-tmp/xtuner/xtuner/model/sft.py", line 224, in _dispatch_lm_model_cfg
&nbsp; &nbsp; llm_cfg = AutoConfig.from_pretrained(
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 934, in from_pretrained
&nbsp; &nbsp; config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/transformers/configuration_utils.py", line 632, in get_config_dict
&nbsp; &nbsp; config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
&nbsp; &nbsp; resolved_config_file = cached_file(
&nbsp; File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/hub.py", line 442, in cached_file
&nbsp; &nbsp; raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like ZhipuAI/chatglm3-6b is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.






道阻且长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "InternLM/xtuner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月21日(星期二) 下午3:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [InternLM/xtuner] OSError: We couldn't connect to 'https://huggingface.co' to load this file (Issue #710)





 
你需要在config的 pretrained_model_name_or_path 指定一个huggingface 的model id（如THUDM/chatglm3-6b），或者一个本地的模型存储路径

**Comment by LZHgrla** [comment]
@Artist2001 
config怎么写的？贴一下？

**Comment by Artist2001** [comment]
好的，如下
# Copyright (c) OpenMMLab. All rights reserved.
import torch
from datasets import load_dataset
from mmengine.dataset import DefaultSampler
from mmengine.hooks import (CheckpointHook, DistSamplerSeedHook, IterTimerHook,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; LoggerHook, ParamSchedulerHook)
from mmengine.optim import AmpOptimWrapper, CosineAnnealingLR, LinearLR
from peft import LoraConfig
from torch.optim import AdamW
from transformers import (AutoModelForCausalLM, AutoTokenizer,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; BitsAndBytesConfig)


from xtuner.dataset import process_hf_dataset
from xtuner.dataset.collate_fns import default_collate_fn
from xtuner.dataset.map_fns import alpaca_zh_map_fn, template_map_fn_factory
from xtuner.engine.hooks import (DatasetInfoHook, EvaluateChatHook,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;VarlenAttnArgsToMessageHubHook)
from xtuner.engine.runner import TrainLoop
from xtuner.model import SupervisedFinetune
from xtuner.utils import PROMPT_TEMPLATE, SYSTEM_TEMPLATE


#######################################################################
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; PART 1&nbsp; Settings&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;#
#######################################################################
# Model
pretrained_model_name_or_path = 'ZhipuAI/chatglm3-6b'
use_varlen_attn = False


# Data
data_files = ['Data/output.json']
# alpaca_zh_path = 'autodl-tmp/Data/output.json'
prompt_template = PROMPT_TEMPLATE.chatglm3
max_length = 1024
pack_to_max_length = True


# Scheduler &amp; Optimizer
batch_size = 1&nbsp; # per_device
accumulative_counts = 16
dataloader_num_workers = 0
max_epochs = 3
optim_type = AdamW
lr = 2e-4
betas = (0.9, 0.999)
weight_decay = 0
max_norm = 1&nbsp; # grad clip
warmup_ratio = 0.03


# Save
save_steps = 500
save_total_limit = 2&nbsp; # Maximum checkpoints to keep (-1 means unlimited)


# Evaluate the generation performance during the training
evaluation_freq = 500
SYSTEM = SYSTEM_TEMPLATE.alpaca
evaluation_inputs = [
&nbsp; &nbsp; '请给我介绍五个上海的景点', 'Please tell me five scenic spots in Shanghai'
]


#######################################################################
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; PART 2&nbsp; Model &amp; Tokenizer&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; #
#######################################################################
tokenizer = dict(
&nbsp; &nbsp; type=AutoTokenizer.from_pretrained,
&nbsp; &nbsp; pretrained_model_name_or_path=pretrained_model_name_or_path,
&nbsp; &nbsp; trust_remote_code=True,
&nbsp; &nbsp; encode_special_tokens=True,
&nbsp; &nbsp; padding_side='left')


model = dict(
&nbsp; &nbsp; type=SupervisedFinetune,
&nbsp; &nbsp; use_varlen_attn=use_varlen_attn,
&nbsp; &nbsp; llm=dict(
&nbsp; &nbsp; &nbsp; &nbsp; type=AutoModelForCausalLM.from_pretrained,
&nbsp; &nbsp; &nbsp; &nbsp; pretrained_model_name_or_path=pretrained_model_name_or_path,
&nbsp; &nbsp; &nbsp; &nbsp; trust_remote_code=True,
&nbsp; &nbsp; &nbsp; &nbsp; torch_dtype=torch.float16,
&nbsp; &nbsp; &nbsp; &nbsp; quantization_config=dict(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; type=BitsAndBytesConfig,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; load_in_4bit=True,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; load_in_8bit=False,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; llm_int8_threshold=6.0,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; llm_int8_has_fp16_weight=False,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bnb_4bit_compute_dtype=torch.float16,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bnb_4bit_use_double_quant=True,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bnb_4bit_quant_type='nf4')),
&nbsp; &nbsp; lora=dict(
&nbsp; &nbsp; &nbsp; &nbsp; type=LoraConfig,
&nbsp; &nbsp; &nbsp; &nbsp; r=64,
&nbsp; &nbsp; &nbsp; &nbsp; lora_alpha=16,
&nbsp; &nbsp; &nbsp; &nbsp; lora_dropout=0.1,
&nbsp; &nbsp; &nbsp; &nbsp; bias='none',
&nbsp; &nbsp; &nbsp; &nbsp; task_type='CAUSAL_LM'))


#######################################################################
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; PART 3&nbsp; Dataset &amp; Dataloader&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;#
#######################################################################
alpaca_zh = dict(
&nbsp; &nbsp; type=process_hf_dataset,
&nbsp; &nbsp; dataset=dict(type=load_dataset, path='json',data_files=data_files),
&nbsp; &nbsp; tokenizer=tokenizer,
&nbsp; &nbsp; max_length=max_length,
&nbsp; &nbsp; dataset_map_fn=None,
&nbsp; &nbsp; template_map_fn=dict(
&nbsp; &nbsp; &nbsp; &nbsp; type=template_map_fn_factory, template=prompt_template),
&nbsp; &nbsp; remove_unused_columns=True,
&nbsp; &nbsp; shuffle_before_pack=True,
&nbsp; &nbsp; pack_to_max_length=pack_to_max_length,
&nbsp; &nbsp; use_varlen_attn=use_varlen_attn)


train_dataloader = dict(
&nbsp; &nbsp; batch_size=batch_size,
&nbsp; &nbsp; num_workers=dataloader_num_workers,
&nbsp; &nbsp; dataset=alpaca_zh,
&nbsp; &nbsp; sampler=dict(type=DefaultSampler, shuffle=True),
&nbsp; &nbsp; collate_fn=dict(type=default_collate_fn, use_varlen_attn=use_varlen_attn))


#######################################################################
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; PART 4&nbsp; Scheduler &amp; Optimizer&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; #
#######################################################################
# optimizer
optim_wrapper = dict(
&nbsp; &nbsp; type=AmpOptimWrapper,
&nbsp; &nbsp; optimizer=dict(
&nbsp; &nbsp; &nbsp; &nbsp; type=optim_type, lr=lr, betas=betas, weight_decay=weight_decay),
&nbsp; &nbsp; clip_grad=dict(max_norm=max_norm, error_if_nonfinite=False),
&nbsp; &nbsp; accumulative_counts=accumulative_counts,
&nbsp; &nbsp; loss_scale='dynamic',
&nbsp; &nbsp; dtype='float16')


# learning policy
# More information: https://github.com/open-mmlab/mmengine/blob/main/docs/en/tutorials/param_scheduler.md&nbsp; # noqa: E501
param_scheduler = [
&nbsp; &nbsp; dict(
&nbsp; &nbsp; &nbsp; &nbsp; type=LinearLR,
&nbsp; &nbsp; &nbsp; &nbsp; start_factor=1e-5,
&nbsp; &nbsp; &nbsp; &nbsp; by_epoch=True,
&nbsp; &nbsp; &nbsp; &nbsp; begin=0,
&nbsp; &nbsp; &nbsp; &nbsp; end=warmup_ratio * max_epochs,
&nbsp; &nbsp; &nbsp; &nbsp; convert_to_iter_based=True),
&nbsp; &nbsp; dict(
&nbsp; &nbsp; &nbsp; &nbsp; type=CosineAnnealingLR,
&nbsp; &nbsp; &nbsp; &nbsp; eta_min=0.0,
&nbsp; &nbsp; &nbsp; &nbsp; by_epoch=True,
&nbsp; &nbsp; &nbsp; &nbsp; begin=warmup_ratio * max_epochs,
&nbsp; &nbsp; &nbsp; &nbsp; end=max_epochs,
&nbsp; &nbsp; &nbsp; &nbsp; convert_to_iter_based=True)
]


# train, val, test setting
train_cfg = dict(type=TrainLoop, max_epochs=max_epochs)


#######################################################################
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;PART 5&nbsp; Runtime&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;#
#######################################################################
# Log the dialogue periodically during the training process, optional
custom_hooks = [
&nbsp; &nbsp; dict(type=DatasetInfoHook, tokenizer=tokenizer),
&nbsp; &nbsp; dict(
&nbsp; &nbsp; &nbsp; &nbsp; type=EvaluateChatHook,
&nbsp; &nbsp; &nbsp; &nbsp; tokenizer=tokenizer,
&nbsp; &nbsp; &nbsp; &nbsp; every_n_iters=evaluation_freq,
&nbsp; &nbsp; &nbsp; &nbsp; evaluation_inputs=evaluation_inputs,
&nbsp; &nbsp; &nbsp; &nbsp; system=SYSTEM,
&nbsp; &nbsp; &nbsp; &nbsp; prompt_template=prompt_template)
]


if use_varlen_attn:
&nbsp; &nbsp; custom_hooks += [dict(type=VarlenAttnArgsToMessageHubHook)]


# configure default hooks
default_hooks = dict(
&nbsp; &nbsp; # record the time of every iteration.
&nbsp; &nbsp; timer=dict(type=IterTimerHook),
&nbsp; &nbsp; # print log every 10 iterations.
&nbsp; &nbsp; logger=dict(type=LoggerHook, log_metric_by_epoch=False, interval=10),
&nbsp; &nbsp; # enable the parameter scheduler.
&nbsp; &nbsp; param_scheduler=dict(type=ParamSchedulerHook),
&nbsp; &nbsp; # save checkpoint per `save_steps`.
&nbsp; &nbsp; checkpoint=dict(
&nbsp; &nbsp; &nbsp; &nbsp; type=CheckpointHook,
&nbsp; &nbsp; &nbsp; &nbsp; by_epoch=False,
&nbsp; &nbsp; &nbsp; &nbsp; interval=save_steps,
&nbsp; &nbsp; &nbsp; &nbsp; max_keep_ckpts=save_total_limit),
&nbsp; &nbsp; # set sampler seed in distributed evrionment.
&nbsp; &nbsp; sampler_seed=dict(type=DistSamplerSeedHook),
)


# configure environment
env_cfg = dict(
&nbsp; &nbsp; # whether to enable cudnn benchmark
&nbsp; &nbsp; cudnn_benchmark=False,
&nbsp; &nbsp; # set multi process parameters
&nbsp; &nbsp; mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
&nbsp; &nbsp; # set distributed parameters
&nbsp; &nbsp; dist_cfg=dict(backend='nccl'),
)


# set visualizer
visualizer = None


# set log level
log_level = 'INFO'


# load from which checkpoint
load_from = None


# whether to resume training from the loaded checkpoint
resume = False


# Defaults to use random seed and disable `deterministic`
randomness = dict(seed=None, deterministic=False)


# set log processor
log_processor = dict(by_epoch=False)







道阻且长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "InternLM/xtuner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月21日(星期二) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [InternLM/xtuner] OSError: We couldn't connect to 'https://huggingface.co' to load this file (Issue #710)





 
@Artist2001
 config怎么写的？贴一下？

**Comment by LZHgrla** [comment]
pretrained_model_name_or_path = 'ZhipuAI/chatglm3-6b'

这个地方ZhipuAI/chatglm3-6b这么写不合适，很容易搞混，写成绝对路径再试一下吧

**Comment by Artist2001** [comment]
好的，我现在试一下




道阻且长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "InternLM/xtuner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月21日(星期二) 下午3:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [InternLM/xtuner] OSError: We couldn't connect to 'https://huggingface.co' to load this file (Issue #710)





 
pretrained_model_name_or_path = 'ZhipuAI/chatglm3-6b'
 
这个地方ZhipuAI/chatglm3-6b这么写不合适，很容易搞混，写成绝对路径再试一下吧

**Comment by Artist2001** [comment]
改成绝对路径运行已成功转换为hf形式，感谢不尽！！！






道阻且长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "InternLM/xtuner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月21日(星期二) 下午3:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [InternLM/xtuner] OSError: We couldn't connect to 'https://huggingface.co' to load this file (Issue #710)





 
pretrained_model_name_or_path = 'ZhipuAI/chatglm3-6b'
 
这个地方ZhipuAI/chatglm3-6b这么写不合适，很容易搞混，写成绝对路径再试一下吧
