### ISSUE TITLE
could you provide a internlm2 1.8B llava model

### ISSUE THREAD

**Issue by shockjiang** [InternLM/xtuner#712]
hi, I'm working on a tiny LM given limited GPU resources. If you could provide a llava internlm2 1.8B pretrained model, it would greately speedup my research.

regards,

**Comment by LZHgrla** [comment]
@shockjiang 
StarCycle(https://huggingface.co/StarCycle) has provided some llava models with internlm2-1.8b, and you might want to check it out.
