### ISSUE TITLE
xtuner转化模型权重文件是否支持多卡

### ISSUE THREAD

**Issue by AlittlePIE** [InternLM/xtuner#715]
4张3090
微调qwen32b之后进行权重转换，是否有选择多卡的选项呢，默认是单卡，会出现oom，以及之后merge的操作，是否有多卡的选项，14b进行merge单卡也会oom（这一步可以使用原生transformers库搞定）

**Comment by LZHgrla** [comment]
@AlittlePIE 
pth_to_hf是在CPU上完成的，应该不涉及GPU的OOM，可以再检查一下是什么问题导致的OOM。
merge的话，有一个参数可以控制，以打开transformers的device_map='auto'，`--device auto`
https://github.com/InternLM/xtuner/blob/0d148dcbd1256a98f73f51edf3c9ef4e051010aa/xtuner/tools/model_converters/merge.py#L33-L37

**Comment by AlittlePIE** [comment]
![微信图片_20240524190555](https://github.com/InternLM/xtuner/assets/38075846/38e6fe73-c7be-4955-b89e-e1b6b3aa56d1)
这个看上去还是会加载权重的，然后就oom了

**Comment by LZHgrla** [comment]
@AlittlePIE 
试一下main分支的pth_to_hf？

https://github.com/InternLM/xtuner/blob/main/xtuner/tools/model_converters/pth_to_hf.py

**Comment by AlittlePIE** [comment]
![微信图片_20240524192157](https://github.com/InternLM/xtuner/assets/38075846/c409c649-1bf2-4a51-a64d-5f1c97bef8f4)
还是会这样

**Comment by AlittlePIE** [comment]
cfg = Config.fromfile(args.config)

**Comment by AlittlePIE** [comment]
cfg = Config.fromfile(args.config)
请问在这一句代码中，args.config是个代码路径，这一句代码是否会执行该代码文件呢，我在该代码文件里写了个print(1111)，在运行pth_to_hf的时候也输出了1111

**Comment by LZHgrla** [comment]
> cfg = Config.fromfile(args.config)
> 
> 请问在这一句代码中，args.config是个代码路径，这一句代码是否会执行该代码文件呢，我在该代码文件里写了个print(1111)，在运行pth_to_hf的时候也输出了1111

会执行

**Comment by LZHgrla** [comment]
> ![微信图片_20240524192157](https://github.com/InternLM/xtuner/assets/38075846/c409c649-1bf2-4a51-a64d-5f1c97bef8f4)
> 
> 还是会这样

试试在config的model中的llm中增加一个device_map='auto'参数，看会不会起效。

**Comment by AlittlePIE** [comment]
可以了，感谢
