### ISSUE TITLE
what's purpose of dispatch

### ISSUE THREAD

**Issue by shockjiang** [InternLM/xtuner#716]
there are some files under: https://github.com/InternLM/xtuner/tree/main/xtuner/model/modules/dispatch, which seems that it is required for each LLM.  I introduce a new LLM, openELM, for llava, but do nothing for its dispatch. I wonder it is ok or not?

thx!

**Comment by HIT-cwh** [comment]
We dispatch the forward method of Attention Block for the following two reasons:
1. Support sequence parallel training. Please refer to [sequence parallel docs](https://github.com/InternLM/xtuner/blob/docs/docs/zh_cn/acceleration/train_extreme_long_sequence.rst) for more details.
2. Support `Variable Length Flash Attention`. Please refer to [varlen flash attn docs](https://github.com/InternLM/xtuner/blob/docs/docs/zh_cn/acceleration/varlen_flash_attn.rst) for more details.

`Variable Length Flash Attention` is not used in llava currently, and `sequence parallel training` is not supported in llava now. So you can do nothing for its dispatch. 

BTW. Maybe you can set the `attn_implementation = 'flash_attention_2'` for faster training if you have install `flash_attn`:
```diff
model = dict(
    type=LLaVAModel,
    ...,
    llm=dict(
        type=AutoModelForCausalLM.from_pretrained,
        pretrained_model_name_or_path=llm_name_or_path,
        trust_remote_code=True,
+      attn_implementation='flash_attention_2',
        torch_dtype=torch.float16),
    visual_encoder=dict(
        type=CLIPVisionModel.from_pretrained,
        pretrained_model_name_or_path=visual_encoder_name_or_path))
```
