### ISSUE TITLE
error occur when run xtuner chat for single image inference

### ISSUE THREAD

**Issue by J0eky** [InternLM/xtuner#727]
when I input "hi", then tape double enter, the following error occurs: 
![image](https://github.com/InternLM/xtuner/assets/105731709/0a946659-ad6c-471d-815d-bd70b50b3f3f)

**Comment by xsx1001** [comment]
change transformers==4.39 works for me

**Comment by chalesguo** [comment]
change transformers==4.39 works，for follow train error.


You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtunerenv/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1271, in call_hook
[rank0]:     getattr(hook, fn_name)(self, **kwargs)
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtuner-main/xtuner-main/xtuner/engine/hooks/evaluate_chat_hook.py", line 230, in before_train
[rank0]:     self._generate_samples(runner, max_new_tokens=50)
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtuner-main/xtuner-main/xtuner/engine/hooks/evaluate_chat_hook.py", line 216, in _generate_samples
[rank0]:     self._eval_images(runner, model, device, max_new_tokens,
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtuner-main/xtuner-main/xtuner/engine/hooks/evaluate_chat_hook.py", line 148, in _eval_images
[rank0]:     generation_output = model.generate(
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtunerenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtunerenv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1758, in generate
[rank0]:     result = self._sample(
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtunerenv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2390, in _sample
[rank0]:     model_kwargs = self._get_initial_cache_position(input_ids, model_kwargs)
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtunerenv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1321, in _get_initial_cache_position
[rank0]:     past_length = model_kwargs["past_key_values"][0][0].shape[2]
[rank0]: TypeError: 'NoneType' object is not subscriptable

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtuner-main/xtuner-main/xtuner/tools/train.py", line 360, in <module>
[rank0]:     main()
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtuner-main/xtuner-main/xtuner/tools/train.py", line 356, in main
[rank0]:     runner.train()
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtunerenv/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1200, in train
[rank0]:     model = self.train_loop.run()  # type: ignore
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtunerenv/lib/python3.10/site-packages/mmengine/runner/loops.py", line 271, in run
[rank0]:     self.runner.call_hook('before_train')
[rank0]:   File "/home/ubuntu/program/xtuner_llava/xtunerenv/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1273, in call_hook
[rank0]:     raise TypeError(f'{e} in {hook}') from e
[rank0]: TypeError: 'NoneType' object is not subscriptable in <xtuner.engine.hooks.evaluate_chat_hook.EvaluateChatHook object at 0x7950fa3cd1b0>

**Comment by rivhea** [comment]
xtuner 0.1.18 + transformers==4.40.1 works for me

**Comment by J0eky** [comment]
@xsx1001 @chalesguo @rivhea Thank you for your responses. Following your suggestions, I downgraded the transformers library to version 4.39.1, and now I am able to successfully run the xtuner chat.
