### ISSUE TITLE
序列并行需要flash-attn支持，可否告知对于flash-attn版本的要求？

### ISSUE THREAD

**Issue by SrWYG** [InternLM/xtuner#744]
本人的DockerFile 如下：
##参考 https://github.com/InternLM/xtuner/pull/234

FROM nvcr.io/nvidia/pytorch:24.01-py3

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip config set global.extra-index-url "https://pypi.doubanio.com/simple"
RUN pip install opencv-python=='4.7.0.72'

WORKDIR /xtuner
COPY . /xtuner/

RUN pip install --no-cache-dir -e .['deepspeed']
RUN pip install packaging

##这里我之前运行过程中 xtuner要求2.1.0以上的flash-attn，但是nvidia-pytorch镜像的transformer-engine不支持 2.1.0 以及 2.5.6以上的版本，
RUN MAX_JOBS=4 pip install flash-attn==2.1.1 --no-build-isolation

如上的镜像build成功
但是执行过程中，已经通过了import的版本检查，load完模型后，出现以下报错：
```
flash_attn_func() got an unexpected keyword argument 'window_size'
```

应该还是版本错误导致的， 所以想问下能否提供一个标准的flash-attn版本，感谢🙏

**Comment by HIT-cwh** [comment]
flash_attn 库在 这个[pr](https://github.com/Dao-AILab/flash-attention/commit/083e8f525f1f8e1dde5044afdac79f9588302207) 支持了 local attn (支持传入window_size）。

目前我们频繁测试的版本是 flash_attn 2.3.6 和 2.5.8，理论上 2.3.6 之后的版本应该都不会报 `flash_attn_func() got an unexpected keyword argument 'window_size'` 这个错，推荐用2.5以上的flash attn
