### ISSUE TITLE
ValueError: The checkpoint you are trying to load has model type `llava_llama` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

### ISSUE THREAD

**Issue by ztfmars** [InternLM/xtuner#748]
i want to try the new your new pretrained llava-llama-3-8b-v1_1

the pretrain link: [xtuner/llava-llama-3-8b-v1_1-hf](https://modelscope.cn/models/xtuner/llava-llama-3-8b-v1_1-hf/summary)

i can run the official llama3 pretrain, but can't run the new pretrained weight.
my pip list:
"""
Package                       Version        Editable project location
----------------------------- -------------- ---------------------------------------
accelerate                    0.21.0
addict                        2.4.0
aiofiles                      23.2.1
aiohttp                       3.9.5
aiosignal                     1.3.1
aliyun-python-sdk-core        2.15.1
aliyun-python-sdk-kms         2.16.2
altair                        5.3.0
annotated-types               0.6.0
anyio                         4.3.0
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
arxiv                         2.1.0
asttokens                     2.4.1
async-lru                     2.0.4
async-timeout                 4.0.3
attrs                         23.2.0
Babel                         2.15.0
beautifulsoup4                4.12.3
bitsandbytes                  0.43.1
bleach                        6.1.0
blinker                       1.8.1
cachetools                    5.3.3
certifi                       2022.12.7
cffi                          1.16.0
charset-normalizer            2.1.1
click                         8.1.7
colorama                      0.4.6
comm                          0.2.2
contourpy                     1.2.1
crcmod                        1.7
cryptography                  42.0.6
cycler                        0.12.1
datasets                      2.18.0
debugpy                       1.8.1
decorator                     5.1.1
deepspeed                     0.14.2
defusedxml                    0.7.1
dill                          0.3.8
distro                        1.9.0
dnspython                     2.6.1
einops                        0.6.1
einops-exts                   0.0.4
email_validator               2.1.1
et-xmlfile                    1.1.0
exceptiongroup                1.2.1
executing                     2.0.1
fastapi                       0.111.0
fastapi-cli                   0.0.2
fastjsonschema                2.19.1
feedparser                    6.0.10
ffmpy                         0.3.2
filelock                      3.13.1
fire                          0.6.0
fonttools                     4.51.0
fqdn                          1.5.1
frozenlist                    1.4.1
fsspec                        2024.2.0
func_timeout                  4.3.5
gast                          0.5.4
gitdb                         4.0.11
GitPython                     3.1.43
gradio                        4.16.0
gradio_client                 0.8.1
griffe                        0.44.0
grpcio                        1.63.0
h11                           0.14.0
hjson                         3.1.0
httpcore                      1.0.5
httptools                     0.6.1
httpx                         0.27.0
huggingface-hub               0.23.0
idna                          3.4
imageio                       2.34.1
importlib_metadata            7.1.0
importlib_resources           6.4.0
ipykernel                     6.29.4
ipython                       8.24.0
ipywidgets                    8.1.2
isoduration                   20.11.0
jedi                          0.19.1
Jinja2                        3.1.3
jmespath                      0.10.0
joblib                        1.4.2
json5                         0.9.25
jsonpointer                   2.4
jsonschema                    4.22.0
jsonschema-specifications     2023.12.1
jupyter                       1.0.0
jupyter_client                8.6.1
jupyter-console               6.6.3
jupyter_core                  5.7.2
jupyter-events                0.10.0
jupyter-lsp                   2.2.5
jupyter_server                2.14.0
jupyter_server_terminals      0.5.3
jupyterlab                    4.1.8
jupyterlab_pygments           0.3.0
jupyterlab_server             2.27.1
jupyterlab_widgets            3.0.10
kiwisolver                    1.4.5
lagent                        0.2.2
lazy_loader                   0.4
llava                         1.2.2.post1
lmdeploy                      0.4.0
markdown-it-py                3.0.0
markdown2                     2.4.13
MarkupSafe                    2.1.5
matplotlib                    3.8.4
matplotlib-inline             0.1.7
mdurl                         0.1.2
mistune                       3.0.2
mmengine                      0.10.4
mmengine-lite                 0.10.4
modelscope                    1.14.0
mpi4py_mpich                  3.1.5
mpmath                        1.3.0
multidict                     6.0.5
multiprocess                  0.70.16
nbclient                      0.10.0
nbconvert                     7.16.4
nbformat                      5.10.4
nest-asyncio                  1.6.0
networkx                      3.2.1
ninja                         1.11.1.1
notebook                      7.1.3
notebook_shim                 0.2.4
numpy                         1.26.3
nvidia-cublas-cu12            12.4.5.8
nvidia-cuda-runtime-cu12      12.4.127
nvidia-curand-cu12            10.3.5.147
nvidia-nccl-cu12              2.21.5
opencv-python                 4.9.0.80
openpyxl                      3.1.2
orjson                        3.10.3
oss2                          2.18.5
overrides                     7.7.0
packaging                     24.0
pandas                        2.2.2
pandocfilters                 1.5.1
parso                         0.8.4
peft                          0.10.0
pexpect                       4.9.0
phx-class-registry            4.1.0
pillow                        10.2.0
pip                           24.0
platformdirs                  4.2.1
prometheus_client             0.20.0
prompt-toolkit                3.0.43
protobuf                      4.25.3
psutil                        5.9.8
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       16.0.0
pyarrow-hotfix                0.6
pybind11                      2.12.0
pycparser                     2.22
pycryptodome                  3.20.0
pydantic                      2.7.1
pydantic_core                 2.18.2
pydeck                        0.9.0
pydub                         0.25.1
Pygments                      2.18.0
pynvml                        11.5.0
pyparsing                     3.1.2
python-dateutil               2.9.0.post0
python-dotenv                 1.0.1
python-json-logger            2.0.7
python-multipart              0.0.9
python-rapidjson              1.16
pytorch-cuda                  12.1
pytz                          2024.1
PyYAML                        6.0.1
pyzmq                         26.0.3
qtconsole                     5.5.2
QtPy                          2.4.1
referencing                   0.35.1
regex                         2024.4.28
requests                      2.31.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.7.1
rpds-py                       0.18.0
ruff                          0.4.3
safetensors                   0.4.3
scikit-image                  0.23.2
scikit-learn                  1.2.2
scipy                         1.13.0
semantic-version              2.10.0
Send2Trash                    1.8.3
sentencepiece                 0.1.99
setuptools                    69.5.1
sgmllib3k                     1.0.0
shellingham                   1.5.4
shortuuid                     1.0.13
simplejson                    3.19.2
six                           1.16.0
smmap                         5.0.1
sniffio                       1.3.1
sortedcontainers              2.4.0
soupsieve                     2.5
stack-data                    0.6.3
starlette                     0.37.2
streamlit                     1.34.0
svgwrite                      1.4.3
sympy                         1.12
tenacity                      8.2.3
termcolor                     2.4.0
terminado                     0.18.1
threadpoolctl                 3.5.0
tifffile                      2024.5.3
tiktoken                      0.6.0
timm                          0.6.13
tinycss2                      1.3.0
tokenizers                    0.15.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.12.0
toolz                         0.12.1
torch                         2.1.2+cu121
torchaudio                    2.1.2+cu121
torchvision                   0.16.2+cu121
tornado                       6.4
tqdm                          4.66.4
traitlets                     5.14.3
transformers                  4.37.2
transformers-stream-generator 0.0.5
triton                        2.1.0
tritonclient                  2.45.0
typer                         0.12.3
types-python-dateutil         2.9.0.20240316
typing_extensions             4.9.0
tzdata                        2024.1
ujson                         5.9.0
uri-template                  1.3.0
urllib3                       2.2.1
uvicorn                       0.29.0
uvloop                        0.19.0
watchdog                      4.0.0
watchfiles                    0.21.0
wavedrom                      2.0.3.post3
wcwidth                       0.2.13
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.8.0
websockets                    11.0.3
wheel                         0.43.0
widgetsnbextension            4.0.10
xtuner                        0.1.18         /home/fusionai/project/internllm/xtuner
xxhash                        3.4.1
yapf                          0.40.2
yarl                          1.9.4
zipp                          3.18.1
"""

The error is :
"""
Traceback (most recent call last):
  File "/home/fusionai/anaconda3/envs/llama3/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1117, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/fusionai/anaconda3/envs/llama3/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 813, in __getitem__
    raise KeyError(key)
KeyError: 'llava_llama'

During handling of the above exception, another exception occurred:
....
ValueError: The checkpoint you are trying to load has model type `llava_llama` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
"""
![image](https://github.com/InternLM/xtuner/assets/35566228/2ad429ef-b1a9-4b41-8955-f40ee9f68158)

**Comment by hhaAndroid** [comment]
@ztfmars Apologies, this set of weights does not support fine-tuning. This model was trained on a limited dataset, so I think you would get better results if you first do pre-training and then fine-tune the model. That approach might work better.
