### ISSUE TITLE
xtuner 是否支持自动的loss function

### ISSUE THREAD

**Issue by Jason8Kang** [InternLM/xtuner#753]
现在用xtuner微调llama3,如果想改写loss function,不知道xtuner是否支持,感谢您的解答.

**Comment by HIT-cwh** [comment]
目前改写 loss function 只能通过 hardcode 的方式进行。
1. 对于 sft ，需要修改这一部分代码 https://github.com/InternLM/xtuner/blob/main/xtuner/model/sft.py#L286-L292
2. 对于 llava，需要修改这一部分代码 https://github.com/InternLM/xtuner/blob/main/xtuner/model/llava.py#L302-L305

**Comment by Jason8Kang** [comment]
@HIT-cwh 感谢你的解答, 在sft.py中loss 计算最终是在 self.llm函数里,如果我是用llama3_8b, llm函数是在哪定义的?  
`    def compute_loss(self, data, data_samples=None):
        if get_sequence_parallel_world_size() > 1:
            return self._compute_sequence_parallel_loss(data)
        else:
            outputs = self.llm(**data)
            loss_dict = {'loss': outputs.loss}
            return loss_dict`

**Comment by HIT-cwh** [comment]
> @HIT-cwh 感谢你的解答, 在sft.py中loss 计算最终是在 self.llm函数里,如果我是用llama3_8b, llm函数是在哪定义的?
> 
> ```
> 
> def compute_loss(self, data, data_samples=None):
>         if get_sequence_parallel_world_size() > 1:
>             return self._compute_sequence_parallel_loss(data)
>         else:
>             outputs = self.llm(**data)
>             loss_dict = {'loss': outputs.loss}
>             return loss_dict
> ```

这里的llm就是llama3_8b，如果data里有labels这个key，那就会在llm(**data)中就把loss计算了，如果你想自定义loss，可以把data里的labels的key pop出来，进行自定义计算。
loss 计算方式可以参考 https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L1185-L1195

**Comment by Jason8Kang** [comment]
理解了,非常感谢
