### ISSUE TITLE
请问是否计划支持Qwen2-128K的训练？

### ISSUE THREAD

**Issue by scewiner** [InternLM/xtuner#755]
请问是否计划支持Qwen2-128K的训练？ 
我尝试用xtuner 进行qwen2 7B模型的训练， 但是7B模型的attn_heads是28，导致sequence_parallel_size 只能设置4或者7；
sequence_parallel_size=4， OOM
sequence_parallel_size=7， 8GPU跑不了，7GPU也是OOM

另外多机多卡的时候，sequence_parallel_size 现在是只能设置成单节点的GPU数量？

**Comment by HIT-cwh** [comment]
我们正在优化序列并行的策略，让序列并行度的设置更加灵活。想麻烦您提供一下您具体的训练配置，以方便我们进一步测试：
1. 序列长度 (max_length)
2. 是全量微调 、lora 还是 qlora
3. 使用的显存优化策略是 deepspeed zero1 、zero2 还是 zero3
4. 您的 GPU 显存大小

> 另外多机多卡的时候，sequence_parallel_size 现在是只能设置成单节点的GPU数量？

目前，sequence_parallel_size 需要被 **gpu 总数** 和 **attn head** 整除，与单节点的GPU数量无关。

**Comment by scewiner** [comment]
这是参数：
1. max_length：131072
2. 全量和lora都试了，都是OOM
3. 优化策略： zero2、zero3都是OOM
4. GPU是8张H800
这个配置 zero2，llama3 8B的是可以训练的，数据也没变；感觉长序列zero2，还是zero3这个不是很关键，还是sequence_parallel_size比较关键。 Qwen2 7B主要是attn_head是莫名奇妙的28

**Comment by HIT-cwh** [comment]
可以试用下这个 pr ：https://github.com/InternLM/xtuner/pull/769

序列并行的用法跟之前一样，只不过像qwen2 这种 28 个 head的情况，支持开sp8了，我测了下128k sp8 在 8*A100 80G上是没有问题的。

**Comment by scewiner** [comment]
感谢！
用这个pr训了一版, 简单看了下生成的效果，目前来看一切正常~
