### ISSUE TITLE
Missing unit tests / 缺少测试文件

### ISSUE THREAD

**Issue by linzeyang** [InternLM/xtuner#77]
There is mentioning of `pytest tests` in `CONTRIBUTING.md` but there was no test files in the repo at the time I am filing this issue. Can I ask if there is any plan to provide test files?

------------------------------------------

在`CONTRIBUTING.md` 中有提到`pytest tests`，但在我提此issue时此repo中并无测试文件。请问今后是否有计划提供测试文件？

**Comment by pppppM** [comment]
目前还不是很完善，后续会持续添加单元测试

**Comment by linzeyang** [comment]
> 目前还不是很完善，后续会持续添加单元测试

了解，谢谢回复哈
