### ISSUE TITLE
请问如何启动gradient checkpointing呢？

### ISSUE THREAD

**Issue by Zheng-Jay** [InternLM/xtuner#823]
请问如何启动gradient checkpointing呢？

**Comment by hhaAndroid** [comment]
默认就应该是开启的

**Comment by Zheng-Jay** [comment]
> 默认就应该是开启的

咦，我在官方的ds-config里没看到有相关配置？

**Comment by hhaAndroid** [comment]
xtuner 用的是 mmengine，所以做法有点不一样，不是在 ds-config 里面配置，是代码配置的，实际上在 xtuner/model/ 里面，例如 sft.py 里面有这个参数可配置，默认就是 true

**Comment by Zheng-Jay** [comment]
好的，感谢！
