### ISSUE TITLE
Cannot produce .safetensor format

### ISSUE THREAD

**Issue by Mikael17125** [InternLM/xtuner#825]
Hi,

I tried to finetune the LLaVA-Llama3 using this configuration file: `llava_llama3_8b_instruct_qlora_clip_vit_large_p14_336_e1_gpu1_finetune.py`. 
The fine-tuning process completed successfully. 

However, when I attempted to convert the model to the HuggingFace format using the command `xtuner convert pth_to_hf llava_llama3_8b_instruct_qlora_clip_vit_large_p14_336_e1_gpu1_finetune.py iter_768.pth/ iter_768_xtuner/`, I could not generate a .safetensor file. Instead, the process produced the following directory structure:

```bash
├── iter_768_xtuner
│   ├── llm_adapter
│   │   ├── adapter_config.json
│   │   ├── adapter_model.bin
│   │   └── README.md
│   ├── projector
│   │   ├── config.json
│   │   ├── configuration_projector.py
│   │   ├── modeling_projector.py
│   │   └── pytorch_model.bin
│   └── xtuner_config.py
```

Can anyone help me?

**Comment by hhaAndroid** [comment]
add `--safe-serialization`

**Comment by Mikael17125** [comment]
I need to merge the llm adapter first to get the results as in tutorial:
`xtuner convert merge meta-llama/Meta-Llama-3-8B-Instruct iter_400_llava/llm_adapter/ merge --safe-serialization`

then just copy the remain directory

```bash
├── merge
│   ├── config.json
│   ├── generation_config.json
│   ├── model-00001-of-00009.safetensors
│   ├── model-00002-of-00009.safetensors
│   ├── model-00003-of-00009.safetensors
│   ├── model-00004-of-00009.safetensors
│   ├── model-00005-of-00009.safetensors
│   ├── model-00006-of-00009.safetensors
│   ├── model-00007-of-00009.safetensors
│   ├── model-00008-of-00009.safetensors
│   ├── model-00009-of-00009.safetensors
│   ├── model.safetensors.index.json
```

Thanks
