### ISSUE TITLE
Custom Optimizer

### ISSUE THREAD

**Issue by Echo0125** [InternLM/xtuner#828]
请问如何自定义optimizer呢，我看mmengine是支持自定义OptimWrapperConstructor来对不同的参数设置不同的lr和weight_decay的，我仿照mmengine的写法在xtuner中实现发现不会调用，实现如下：
```python
optim_wrapper = dict(
    type=AmpOptimWrapper,
    optimizer=dict(
        type=optim_type, lr=lr, betas=betas, weight_decay=weight_decay),
    clip_grad=dict(max_norm=max_norm, error_if_nonfinite=False),
    accumulative_counts=accumulative_counts,
    loss_scale='dynamic',
    dtype='float16',
    paramwise_cfg=dict(
            vit_mm_lr=lr * 10
        ),
    constructor='LLaVAOptimWrapperConstructor')
```
请问如何将vit和llm的lr设置为不同的值呢？

**Comment by Echo0125** [comment]
Done. 使用deepspeed后需要修改train的代码~

**Comment by Echo0125** [comment]
还有一个问题，就是我设置accumulation之后，迭代的iter数并没有变，这是mmengine内置的原因吗，iter不变，只有在iter % accumulation == 0时才会optimizer.step()，但是不显式更改每一轮的iter总数？

**Comment by hhaAndroid** [comment]
1. 如果你只是想实现 vit 和 llm 的 lr 不同的话，不需要重写LLaVAOptimWrapperConstructor，注入 paramwise_cfg 就可以了
2. 迭代的iter数并没有变是正常的，因为 mmengine 的逻辑就是如此，和 huggingface trainer 里面不一样

**Comment by hhaAndroid** [comment]
是的，没有修复这个 train.py bug。 paramwise_cfg=dict(custom_keys={'visual_encoder.': dict(lr_mult=0.1)})

**Comment by Echo0125** [comment]
好的，感谢解答~
