### ISSUE TITLE
全参量微调Deepseek-v2-lite时候出现“NotImplementedError”

### ISSUE THREAD

**Issue by BambiSheng** [InternLM/xtuner#851]
您好，我在全参量微调Deepseek-v2-lite时候发现如果在custom_hooks中加入了EvaluateChatHook之后（如下）
```
  dict(
    type=EvaluateChatHook,
    tokenizer=tokenizer,
    every_n_iters=evaluation_freq,
    evaluation_inputs=evaluation_inputs,
    system=SYSTEM,
    prompt_template=prompt_template)
```
代码就会出现“NotImplementedError”，指向https://github.com/InternLM/xtuner/blob/main/xtuner/model/transformers_models/deepseek_v2/modeling_deepseek.py 的第599行，而删掉后就能正常训练。这是bug还是目前xtuner不支持微调Deepseek-v2-lite的过程中进行evaluate？ @HIT-cwh

**Comment by BinJlu** [comment]
请问您是删掉了什么使他能够正常训练的，我微调llama3也遇到了这个问题
