### ISSUE TITLE
xtuner train 报错

### ISSUE THREAD

**Issue by rourouZ** [InternLM/xtuner#858]
07/22 03:04:52 - mmengine - WARNING - WARNING: command error: '[Errno 2] No such file or directory: 'python''!
![image](https://github.com/user-attachments/assets/87340c90-6ee9-42c0-bc61-20a7096b71bb)

**Comment by rourouZ** [comment]
已解决

**Comment by qiulongquan** [comment]
我也有同样的问题，xtuner train XXX.py 后出现语法格式的提示，无法进行训练，请问你是如何解决的 @rourouZ
