### ISSUE TITLE
About Training need

### ISSUE THREAD

**Issue by xiaohangguo** [InternLM/xtuner#86]
1.数据集格式
目前我用的两种数据集格式`"text_only"`和`"text2text"`
```
{
    "type": "text_only",
    "instances": [
        {
            "text":"……",
},
{
……
},
]
}
```
```
{
    "type": "text2text",
    "instances": [
        {
            "input":"……",
             "output":"",
},
{
……
},
]
}
```
prompt 的话有两种
```
1. ###instruction: {} ###input:{} ###output:{}
2. ###Human: instruction:{} input:{} ###Assistant:{}
```
多轮对话的语料部分是直接在textonly 里面多次的这种 `###instruction: {} ###input:{} ###output:{}`情况
2.基准模型
（1）codellama系列
`https://huggingface.co/codellama/CodeLlama-7b-Python-hf` 
`https://huggingface.co/Phind/Phind-CodeLlama-34B-v1`
……
codellama微调过后的phind :`https://huggingface.co/Phind/Phind-CodeLlama-34B-v1`
（2）starcoder系列
`https://huggingface.co/bigcode/starcoder`
（3）wizard系列
`https://huggingface.co/WizardLM/WizardCoder-Python-34B-V1.0`
3.zero3、zero2应该都可以试试，lora也可以试试，不过目前打算租赁A100，所以应该打算跑全量

**Comment by xiaohangguo** [comment]
![image](https://github.com/InternLM/xtuner/assets/72799392/aee72110-64bc-474a-a73d-0a614e8256f5)
这种配置可以跑34B的吗，目前的数据量在2W条左右。像如果跑全量的zero3，感觉220G内存不够吧

**Comment by pppppM** [comment]
@xiaohangguo 数据集格式需要你这边适配一下 xtuner，模型部分需要我进一步测试一下最小的 cpu 是多少

## 数据集
数据格式和我们目前支持的不太一致，需要根据我们的数据部分文档进行一下转换
https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/dataset_format.md

Text Only 的数据集对应的是 xtuner 的增量预训练 Pipeline
https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/incremental_pretraining.md

text2text 对应的是多轮对话数据集
https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/multi_turn_conversation.md

## Prompt
这里有一个增加 StarCoder 官方使用的微调数据集的 PR，可以下里面新增 Prompt 的方式
https://github.com/InternLM/xtuner/pull/83/files


## 模型部分

34B 模型需要的最小内存我需要测试一下，不过单卡 A100 应该是没有办法全量微调 34B 的，QLoRA 可以单卡微调 34B

**Comment by HIT-cwh** [comment]
想要新增您这两种数据集，只需要写两个map function 放到xtuner/dataset/map_fns/dataset_map_fns目录下，再把对应的两种prompt放到xtuner/utils/templates.py里就好。

### Step 1把数据集处理为标准格式

**对于text2text类型的数据**，因为xtuner提供的数据格式是
```json
[{
    "conversation":[
        {
            "input": "xxx",
            "output": "xxx"
        },
        {
            "input": "xxx",
            "output": "xxx"
        }
    ]
}]
```
跟你的数据只差个json的key不同，你的数据key是`instances`，我们的是`conversation`，所以可以写一个map function把key换一下：
```
def map_fn(example):
    return {'conversation': example['instances']}
```

**对于text_only类型的数据**，我看一个"instances"里有多条“text”数据，不知道是不是每条“text”数据都是一个`###instruction: {} ###input:{} ###output:{}`这样的组合？如果是这样的话，一般在训练过程中，instruction和input部分以及对话模板是不加loss的，只有output部分会算loss。所以我的想法是先写一个map function把对话模板（###instruction: ###input: ###output:）洗掉，大概长这样：
```
def map_fn(example):

    instances = example['instances']
    conversation = []

    for item in instances:
        text = item['text']  # ###instruction: {} ###input:{} ###output:{}
        instruction, input, output = None, None, None
        for sentence in text.strip().split('###'):
            sentence = sentence.strip()
            if sentence[:12] == 'instruction:':
                instruction = sentence[12:]
            elif sentence[:6] == 'input':
                input = sentence[6:]
            elif sentence[:7] == 'output:':
                output = sentence[7:]
            else:
                raise RuntimeError
        conversation.append({
            'input': f'{instruction}\n{input}',
            'output': output
        })

    return conversation
```

### Step 2 添加对话模板

在`xtuner/utils/templates.py`里加入两种对话模板：
```
from mmengine.config import ConfigDict
PROMPT_TEMPLATE = ConfigDict(
    xxxx,
    t1=dict(
        INSTRUCTION_START='### Instruction:\n{input}\n\n### Output: ',
        INSTRUCTION='### Instruction:\n{input}\n\n### Output: '),
    t2=dict(
        INSTRUCTION_START='### Human: {input}\n### Assistant: ',
        INSTRUCTION='### Human: {input}\n### Assistant: '))
```
这里对对话模板做了一些改动，你的对话模板是
```
###instruction: {} ###input:{} ###output:{}
```
但在chat的时候，大家应该不会先输入instruction再输入input？大概会直接输入一个instruction等待gpt的回答，所以上面这种写法会把对话模板改为
```
###instruction: {f'{instruction}\n{input}'} ###output:{f'{output}'}
```
这样能缩小训练和chat时候的gap

### Step 3 写config
可以基于`xtuner/configs/llama/llama2_7b/llama2_7b_qlora_oasst1_e3.py`这个config修改：
```diff
from xtuner.dataset.map_fns import map_fn, template_map_fn_factory  # 我们刚写的map function
...
#######################################################################
#                          PART 1  Settings                           #
#######################################################################
- pretrained_model_name_or_path = 'meta-llama/Llama-2-7b-hf'
+ pretrained_model_name_or_path =xxx

- prompt_template = PROMPT_TEMPLATE.openassistant
+ prompt_template = PROMPT_TEMPLATE.t1  # step 2里加的对话模板
...
# 其他参数稍微调整下
#######################################################################
#                      PART 3  Dataset & Dataloader                   #
#######################################################################
train_dataset = dict(
    type=process_hf_dataset,
-       dataset=dict(type=load_dataset, path=data_path),
+      dataset=dict(type=load_dataset, path=‘json’,data_files=xxx ),
    tokenizer=tokenizer,
    max_length=max_length,
    dataset_map_fn=map_fn,
    template_map_fn=dict(
        type=template_map_fn_factory, template=prompt_template),
    remove_unused_columns=True,
    shuffle_before_pack=True,
    pack_to_max_length=pack_to_max_length)
```
这样大概就能跑起来实验了

**Comment by pppppM** [comment]
> @xiaohangguo 数据集格式需要你这边适配一下 xtuner，模型部分需要我进一步测试一下最小的 cpu 是多少
> 
> ## 数据集
> 数据格式和我们目前支持的不太一致，需要根据我们的数据部分文档进行一下转换 https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/dataset_format.md
> 
> Text Only 的数据集对应的是 xtuner 的增量预训练 Pipeline https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/incremental_pretraining.md
> 
> text2text 对应的是多轮对话数据集 https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/multi_turn_conversation.md
> 
> ## Prompt
> 这里有一个增加 StarCoder 官方使用的微调数据集的 PR，可以下里面新增 Prompt 的方式 https://github.com/InternLM/xtuner/pull/83/files
> 
> ## 模型部分
> 34B 模型需要的最小内存我需要测试一下

不过根据你的截图来看，应该是 8*80GB 显存，8*228GB 内存？这样 34B 模型肯定是可以跑起来的

**Comment by xiaohangguo** [comment]
1卡

> > @xiaohangguo 数据集格式需要你这边适配一下 xtuner，模型部分需要我进一步测试一下最小的 cpu 是多少
> > ## 数据集
> > 数据格式和我们目前支持的不太一致，需要根据我们的数据部分文档进行一下转换 https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/dataset_format.md
> > Text Only 的数据集对应的是 xtuner 的增量预训练 Pipeline https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/incremental_pretraining.md
> > text2text 对应的是多轮对话数据集 https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/multi_turn_conversation.md
> > ## Prompt
> > 这里有一个增加 StarCoder 官方使用的微调数据集的 PR，可以下里面新增 Prompt 的方式 https://github.com/InternLM/xtuner/pull/83/files
> > ## 模型部分
> > 34B 模型需要的最小内存我需要测试一下
> 
> 不过根据你的截图来看，应该是 8x80GB 显存，8x228GB 内存？这样 34B 模型肯定是可以跑起来的
单卡能跑吗

**Comment by xiaohangguo** [comment]
> 想要新增您这两种数据集，只需要写两个map function 放到xtuner/dataset/map_fns/dataset_map_fns目录下，再把对应的两种prompt放到xtuner/utils/templates.py里就好。
> 
> ### Step 1把数据集处理为标准格式
> **对于text2text类型的数据**，因为xtuner提供的数据格式是
> 
> ```json
> [{
>     "conversation":[
>         {
>             "input": "xxx",
>             "output": "xxx"
>         },
>         {
>             "input": "xxx",
>             "output": "xxx"
>         }
>     ]
> }]
> ```
> 
> 跟你的数据只差个json的key不同，你的数据key是`instances`，我们的是`conversation`，所以可以写一个map function把key换一下：
> 
> ```
> def map_fn(example):
>     return {'conversation': example['instances']}
> ```
> 
> **对于text_only类型的数据**，我看一个"instances"里有多条“text”数据，不知道是不是每条“text”数据都是一个`###instruction: {} ###input:{} ###output:{}`这样的组合？如果是这样的话，一般在训练过程中，instruction和input部分以及对话模板是不加loss的，只有output部分会算loss。所以我的想法是先写一个map function把对话模板（###instruction: ###input: ###output:）洗掉，大概长这样：
> 
> ```
> def map_fn(example):
> 
>     instances = example['instances']
>     conversation = []
> 
>     for item in instances:
>         text = item['text']  # ###instruction: {} ###input:{} ###output:{}
>         instruction, input, output = None, None, None
>         for sentence in text.strip().split('###'):
>             sentence = sentence.strip()
>             if sentence[:12] == 'instruction:':
>                 instruction = sentence[12:]
>             elif sentence[:6] == 'input':
>                 input = sentence[6:]
>             elif sentence[:7] == 'output:':
>                 output = sentence[7:]
>             else:
>                 raise RuntimeError
>         conversation.append({
>             'input': f'{instruction}\n{input}',
>             'output': output
>         })
> 
>     return conversation
> ```
> 
> ### Step 2 添加对话模板
> 在`xtuner/utils/templates.py`里加入两种对话模板：
> 
> ```
> from mmengine.config import ConfigDict
> PROMPT_TEMPLATE = ConfigDict(
>     xxxx,
>     t1=dict(
>         INSTRUCTION_START='### Instruction:\n{input}\n\n### Output: ',
>         INSTRUCTION='### Instruction:\n{input}\n\n### Output: '),
>     t2=dict(
>         INSTRUCTION_START='### Human: {input}\n### Assistant: ',
>         INSTRUCTION='### Human: {input}\n### Assistant: '))
> ```
> 
> 这里对对话模板做了一些改动，你的对话模板是
> 
> ```
> ###instruction: {} ###input:{} ###output:{}
> ```
> 
> 但在chat的时候，大家应该不会先输入instruction再输入input？大概会直接输入一个instruction等待gpt的回答，所以上面这种写法会把对话模板改为
> 
> ```
> ###instruction: {f'{instruction}\n{input}'} ###output:{f'{output}'}
> ```
> 
> 这样能缩小训练和chat时候的gap
> 
> ### Step 3 写config
> 可以基于`xtuner/configs/llama/llama2_7b/llama2_7b_qlora_oasst1_e3.py`这个config修改：
> 
> ```diff
> from xtuner.dataset.map_fns import map_fn, template_map_fn_factory  # 我们刚写的map function
> ...
> #######################################################################
> #                          PART 1  Settings                           #
> #######################################################################
> - pretrained_model_name_or_path = 'meta-llama/Llama-2-7b-hf'
> + pretrained_model_name_or_path =xxx
> 
> - prompt_template = PROMPT_TEMPLATE.openassistant
> + prompt_template = PROMPT_TEMPLATE.t1  # step 2里加的对话模板
> ...
> # 其他参数稍微调整下
> #######################################################################
> #                      PART 3  Dataset & Dataloader                   #
> #######################################################################
> train_dataset = dict(
>     type=process_hf_dataset,
> -       dataset=dict(type=load_dataset, path=data_path),
> +      dataset=dict(type=load_dataset, path=‘json’,data_files=xxx ),
>     tokenizer=tokenizer,
>     max_length=max_length,
>     dataset_map_fn=map_fn,
>     template_map_fn=dict(
>         type=template_map_fn_factory, template=prompt_template),
>     remove_unused_columns=True,
>     shuffle_before_pack=True,
>     pack_to_max_length=pack_to_max_length)
> ```
> 
> 这样大概就能跑起来实验了
`我看一个"instances"里有多条“text”数据，不知道是不是每条“text”数据都是一个###instruction: {} ###input:{} ###output:{}这样的组合？`
我制作数据集的时候，是每一个都是这样的组合，但是，会有多轮对话的情况，最长的大概是三次

另外`一般在训练过程中，instruction和input部分以及对话模板是不加loss的，只有output部分会算loss。` 对于这个问题的话，我之前用的那个框架，他在text2text的这种格式下是你说的这种loss计算方式，text_only，应该不是，应该是整体来计算loss的，收敛会慢一点

**Comment by HIT-cwh** [comment]
如果text_only数据集对对话模板也计算loss，那实现方法可能就更简单些。像你说的那样，把input设为空，output是多轮对话的text，之后在config中把train_dataset 的template_map_fn置为None就可以了，因为不需要另外加对话模板了嘛。

但可能需要额外考虑一个问题，在tokenize的时候对于多轮对话，要不要每轮对话的开始和结束都加入bos token和eos token。如果按照上述方法（把input设为空，output是多轮对话的text），可能只会在多轮对话整体的开头结尾增加bos token和eos token。这样模型在对话过程中会不会不知道在什么时候应该生成eos token？（无法正常停下来）

**Comment by xiaohangguo** [comment]
是的，您说的很对，所以我的想法是，我自己来写正则之类的操作，把我现在用的text_only，一次性转换成这种形式吧
数据集里面只用内容对吧，不需要prompt，prompt在`xtuner/utils/templates.py`里面加？
https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/multi_turn_conversation.md

**Comment by HIT-cwh** [comment]
> 是的，您说的很对，所以我的想法是，我自己来写正则之类的操作，把我现在用的text_only，一次性转换成这种形式吧 数据集里面只用内容对吧，不需要prompt，prompt在`xtuner/utils/templates.py`里面加？ https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/multi_turn_conversation.md

是的，在xtuner/utils/templates.py里面加好之后config里也需要对应修改

**Comment by LZHgrla** [comment]
@xiaohangguo  

使用QLoRA得话，单卡是没有问题的
如果需要全量微调，这边实测了一下 `codellama/CodeLlama-34b-hf`，数据长度2048，使用4卡A100 + deepspeed_zero3_offload 能够训起来，内存占用800GB，看起来是能满足需求的

**Comment by xiaohangguo** [comment]
> 



> @xiaohangguo
> 
> 使用QLoRA得话，单卡训练是没有问题的
> 
> 如果需要全参数微调，我们实测了一下 `codellama/CodeLlama-34b-hf`，数据长度2048，使用4卡A100-80GB + deepspeed_zero3_offload 能够训起来，内存占用800GB，看起来是能满足需求的

好的，谢谢，单卡的话zero3 200G内存跑不动吧？得800G吧？ zero2的情况呢？如果可以的话请帮忙测测吧，感谢

**Comment by LZHgrla** [comment]
> > @xiaohangguo
> > 使用QLoRA得话，单卡训练是没有问题的
> > 如果需要全参数微调，我们实测了一下 `codellama/CodeLlama-34b-hf`，数据长度2048，使用4卡A100-80GB + deepspeed_zero3_offload 能够训起来，内存占用800GB，看起来是能满足需求的
> 
> 好的，谢谢，单卡的话zero3 200G内存跑不动吧？得800G吧？ zero2的情况呢？如果可以的话请帮忙测测吧，感谢

如果是单卡的话，不用QLoRA是跑不起来的，因为全量参数放不下。

多卡的话，ZeRO2并不会对模型做切分，所以全量参数也放不下，因此还是得使用ZeRO3。

综合来看，如果QLoRA得话，就是单卡或多卡，可用ZeRO2，也可不用；如果全参数微调，目前只能多卡ZeRO3。

**Comment by xiaohangguo** [comment]
```
nloading and preparing dataset json/xtuner to /home/lvshuhang/.cache/huggingface/datasets/json/xtuner-ee2fffce10ab4da6/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51...
Downloading data files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 5801.25it/s]
Extracting data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1201.12it/s]
Dataset json downloaded and prepared to /home/lvshuhang/.cache/huggingface/datasets/json/xtuner-ee2fffce10ab4da6/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51. Subsequent calls will reuse this data.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 601.51it/s]
Traceback (most recent call last):                                                                                                                                          
  File "/home/lvshuhang/gpt/xtuner/xtuner/tools/train.py", line 225, in <module>
    main()
  File "/home/lvshuhang/gpt/xtuner/xtuner/tools/train.py", line 221, in main
    runner.train()
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1703, in train
    self._train_loop = self.build_train_loop(
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1502, in build_train_loop
    loop = EpochBasedTrainLoop(
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1353, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/lvshuhang/gpt/xtuner/xtuner/dataset/huggingface.py", line 74, in process_hf_dataset
    dataset = dataset.map(dataset_map_fn)
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 563, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 528, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2953, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3307, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3210, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/home/lvshuhang/gpt/xtuner/xtuner/dataset/map_fns/dataset_map_fns/oasst1_map_fn.py", line 22, in oasst1_map_fn
    for sentence in example['text'].strip().split('###'):
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 280, in __getitem__
    value = self.data[key]
KeyError: 'text'
```
应该是不需要按照###这种形式切割了，我把数据集转了一下，不知道哪个
![image](https://github.com/InternLM/xtuner/assets/72799392/6c1778de-036c-4dfe-99d7-34e730aa8d11)

**Comment by xiaohangguo** [comment]
我直接转的，wizard的那种map其实好弄一点，因为里面有多轮对话，直接通过from gpt from human，来区别。我是直接转的，因为这种是alpaca的写法吧，还不知道这种怎么做多轮对话，只知道在做RLHF对齐的时候时候基本上就是要多轮对话

**Comment by pppppM** [comment]
可以参考数据集格式的文档，里面有详细的修改配置方法
https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/multi_turn_conversation.md
