### ISSUE TITLE
deepseek v2 使用shard模式做训练，在load权重的部分 报missing w1w3这类key的情况

### ISSUE THREAD

**Issue by FlyCarrot** [InternLM/xtuner#879]
报错如下
模型是deepseek v2-lite ，shard 是8，
```
model.layers.7.mlp.experts.3.w1w3 not in state_dict, loading deepseek-ai/DeepSeek-V2-Lite/model-00002-of-000004.safetensors
```

**Comment by Opdoop** [comment]
@FlyCarrot 我遇到了类似的情况，请问解决了吗？ w1w3 为什么会报这个 warning 呀？

**Comment by FlyCarrot** [comment]
> [@FlyCarrot](https://github.com/FlyCarrot) 我遇到了类似的情况，请问解决了吗？ w1w3 为什么会报这个 warning 呀？

_merge_experts_weight
搜索一下这个函数看下源码就知道了，这个是正常的，因为shard模式本身就是合并了一些experts做的，所以和原始的官方权重比，名称上会有少。这只是warning，不影响。
