### ISSUE TITLE
怎么自己指定fp16 fp32 bp16？

### ISSUE THREAD

**Issue by bjzhb666** [InternLM/xtuner#893]
使用deepspeed时候出现
![image](https://github.com/user-attachments/assets/104536ed-3ad5-46b7-8b7f-dab9dc4f5eb0)
参考https://github.com/microsoft/DeepSpeed/issues/1599
https://github.com/PKU-Alignment/safe-rlhf/issues/21
https://github.com/microsoft/DeepSpeed/issues/1773#issuecomment-1040655702
发现是所用V100在使用fp16的时候精度不够，因此需要替换。

查阅文档
![image](https://github.com/user-attachments/assets/514191bc-2843-4ab9-b922-fb2fa5ca61fb)
但是文档残缺，话没写全。

运行的命令是
```
NPROC_PER_NODE=8 xtuner train xtuner/configs/llava/official/llava_v15_7b/llava_v15_7b_pretrain.py \
    --deepspeed deepspeed_zero2 --seed 1024
```

cuda12.1，torch2.1.2

**Comment by tcxia** [comment]
使用fp32训练还会报错？ RuntimeError: "_amp_foreach_non_finite_check_and_unscale_cuda" not implemented for 'BFloat16'
