### ISSUE TITLE
codellama wizardcoder求支持

### ISSUE THREAD

**Issue by Xu-Wave** [InternLM/xtuner#90]
codellama wizardcoder 求支持 万分感谢！

**Comment by pppppM** [comment]
@Xu-Wave CodeLlama 和 Wizardcoder 应该都没有开源具体的数据？有没有可参考的基于 CodeLlama 或者 Wizardcoder 微调的样例？

**Comment by xiaohangguo** [comment]
wizardcoder是可以跑的，codellama的话我还没试

**Comment by xiaohangguo** [comment]
> wizardcoder是可以跑的，codellama的话我还没试

两个应该都是没问题的
