### ISSUE TITLE
[Misc] global_batch_size, accumulative_counts 和 ThroughputHook

### ISSUE THREAD

**Issue by CokeDong** [InternLM/xtuner#967]
有几个问题需要确认下：
以[mixtral_8x7b_instruct_full_oasst1_e3.py](https://github.com/InternLM/xtuner/blob/main/xtuner/configs/mixtral/mixtral_8x7b_instruct/mixtral_8x7b_instruct_full_oasst1_e3.py)
为例
```
# Data
data_path = 'timdettmers/openassistant-guanaco'
prompt_template = PROMPT_TEMPLATE.mixtral
max_length = 2048
pack_to_max_length = True

# parallel
sequence_parallel_size = 1

# Scheduler & Optimizer
batch_size = 1  # per_device
accumulative_counts = 16
accumulative_counts *= sequence_parallel_size
dataloader_num_workers = 0
max_epochs = 3
optim_type = AdamW
lr = 2e-5
betas = (0.9, 0.999)
weight_decay = 0
max_norm = 1  # grad clip
warmup_ratio = 0.03

```
训练命令：
```
srun -p $PARTITION --job-name=mixtral --nodes=2 --gres=gpu:8 --ntasks-per-node=8 xtuner train mixtral_8x7b_instruct_full_oasst1_e3 --deepspeed deepspeed_zero3 --launcher slurm
```
即 `num_of_gpus` = 16

1. xtuner在训练时，`global_batch_size`是怎么计算的？是否也等于：`batch_size`  * `accumulative_counts` *  `data_parallel_world_size`? `data_parallel_world_size` 等于 `num_of_gpus` / `sequence_parallel_size `?
2. ThroughputHook中的[tokens_per_sec_per_gpu ](https://github.com/InternLM/xtuner/blob/main/xtuner/engine/hooks/throughput_hook.py#L145C9-L145C32)看起来没有考虑`accumulative_counts`？这里是[`TGS'](https://xtuner.readthedocs.io/zh-cn/latest/acceleration/benchmark.html)的定义吗？

**Comment by CokeDong** [comment]
2.已解决 使用一个iter的tgs，而不是一个optimizer step内的tgs

**Comment by HIT-cwh** [comment]
当设置 `pack_to_max_length = True` 后，XTuner 中一次梯度更新消耗的总 token 数为：

`batch_size (per device) * n_gpus * (max_length / sp_size) * accumulative_counts`

`max_length / sp_size` 是因为我们会在计算前把一条长序列 (max_length) 切分为 sp_size 个短序列，每长卡上都只计算 `max_length / sp_size` 长度的序列。由于序列并行会影响 dp_size ，所以当开启序列并行之后如果想要维持 `一次梯度更新消耗的总 token 数` 不变，就需要把 accumulative_counts 设置为原来的 sp_size 倍。因此配置文件中有 `accumulative_counts *= sequence_parallel_size` 的设置。
